name = "strata-generators"
version = "0.1.0"
defaultTargets = ["strata-generators"]

[[require]]
name = "Strata"
git = "https://github.com/strata-org/strata"
rev = "main"

[[require]]
name = "basalt"
git = "https://github.com/hgoldstein95/basalt"
rev = "main"

[[lean_lib]]
name = "StrataGenerators"

[[lean_exe]]
name = "strata-generators"
root = "Main"
