import Basalt.Gen
import Basalt.IO
import Basalt.Combinators
import Basalt.Examples.ArbString.Def
import Strata.Languages.Core.Function
import StrataGenerators.HasTypeAGen.Core

open Lambda RandomChoice Core Imperative ArbString

/-!
# Core generator definitions for well-typed Strata Core `Function`s

This file contains the canonical definition of `genFunction`, a generator of
well-typed Strata Core functions (`Function = LFunc CoreLParams`) satisfying the
`FuncHasTypeA` relation of `Strata.Languages.Core.FunctionTypeSpec`.

The generator reuses `genLExpr` from `HasTypeAGen/Core.lean` to generate
well-typed expressions for the function body and (optional) termination measure,
and `genLMonoTy` to generate the input/output types.

A generated `Function` is well-typed in the sense of `FuncHasTypeA` because:
1. Its `typeArgs` and its `inputs.keys` are produced via `List.dedup`, hence
   `Nodup`.
2. Its input and output types are produced by `genLMonoTy typeArgs`, hence every
   free type variable in the signature is drawn from `typeArgs`
   (`noUndeclaredVars`).
3. Its body (when present) is produced by `genLExpr ... output`, hence has the
   declared return type. Note the annotated typing spec `instHasTypeA` *ignores*
   the ambient typing context, so `bodyTyped` reduces to `HasTypeA [] body output`.
4. Its measure (when present) is produced by `genLExpr ... .int`, hence has type
   `int`.
-/

-- ── Name / type-argument generation ─────────────────────────────────────

/-- Generate a random list of alphanumeric names of length ≤ `depth`. -/
def genNameList [Gen G] (depth : Nat) : G (List String) := do
  let k ← choose 0 depth (by omega)
  List.mapM (fun _ => String.arbitrary) (List.range k.down.val)

/-- Generate a list of *distinct* type-argument names. Distinctness is
    guaranteed by `List.dedup`. -/
def genTypeArgs [Gen G] (depth : Nat) : G (List TyIdentifier) :=
  List.dedup <$> genNameList depth

/-- Generate a list of *distinct* input identifiers. Distinctness of the
    underlying names (and hence of the identifiers, since `⟨·, ()⟩` is injective)
    is guaranteed by `List.dedup`. -/
def genIdents [Gen G] (depth : Nat) : G (List (Identifier Unit)) :=
  (fun names => (names.map (fun s => (⟨s, ()⟩ : Identifier Unit))).dedup) <$> genNameList depth

-- ── Input signature generation ──────────────────────────────────────────

/-- Generate the formal-parameter signature: a `ListMap` from distinct
    identifiers to monotypes, where every type is drawn from `genLMonoTy tvars`
    (so its free type variables all lie in `tvars`). -/
def genInputs [Gen G] (tvars : List TyIdentifier) (depth : Nat) :
    G (ListMap (Identifier Unit) LMonoTy) := do
  let idents ← genIdents depth
  idents.mapM (fun x => do
    let ty ← genLMonoTy tvars depth
    pure (x, ty))

-- ── Optional body / measure generation ──────────────────────────────────

/-- Generate an optional well-typed expression of type `τ`: either `none`, or
    `some e` for `e` generated by `genLExpr` at type `τ` (empty bvar context,
    empty polymorphic-op context). -/
def genOptExpr [Gen G] (fctx : FVarCtx) (octx : OpCtx) (tvars : List TyIdentifier)
    (depth : Nat) (τ : LMonoTy) : G (Option LExpr') :=
  pick
    (fun () => pure none)
    (fun () => (fun e => some e) <$> genLExpr fctx octx [] tvars [] depth τ)

-- ── Main function generator ─────────────────────────────────────────────

/-- Generate a well-typed `Function` (i.e. `LFunc CoreLParams`).

    The generated function satisfies `FuncHasTypeA C Γ` for any ambient context
    `Γ` (see `genFunction_sound`).

    Components generated:
    - `typeArgs` — a `Nodup` list of type-variable names,
    - `inputs`   — a `Nodup`-keyed signature with types over `typeArgs`,
    - `output`   — a type over `typeArgs`,
    - `body`     — an optional expression of type `output`,
    - `measure`  — an optional expression of type `int`.

    All fields not constrained by the typing spec (`isConstr`, `isRecursive`,
    `attr`, `concreteEval`, `axioms`, `preconditions`) are left at their default
    values. -/
def genFunction [Gen G] (fctx : FVarCtx) (octx : OpCtx) (depth : Nat) : G Function := do
  let name ← String.arbitrary
  let typeArgs ← genTypeArgs depth
  let inputs ← genInputs typeArgs depth
  let output ← genLMonoTy typeArgs depth
  let body ← genOptExpr fctx octx typeArgs depth output
  let measure ← genOptExpr fctx octx typeArgs depth .int
  pure {
    name := ⟨name, ()⟩,
    typeArgs := typeArgs,
    inputs := inputs,
    output := output,
    body := body,
    measure := measure
  }
