import StrataGenerators.SetGen
import StrataGenerators.HasTypeAGen.Core
import Mathlib.Tactic

open Lambda RandomChoice ArbNat SetGen

/-!
# Generator of well-typed terms satisfying `HasTypeA`

A Basalt `SetGen`-based random generator for well-typed Strata `LExpr`s
that satisfy the `HasTypeA` relation.
We work with the `LExprParams` instantiation `LExprParams.mono ⟨Unit, Unit⟩` (unit
metadata and identifier-metadata, monotype annotations).

## Contents

- `HasTypeA'` — the typing judgement `HasTypeA`, with `LExprParams` instantiated
- `SimpleType` — types generated by `genLMonoTy`
- `genLMonoTy` — generates simple mono-types (bool, int, arrow)
- `genLExpr` — generates well-typed `LExpr`s for a given type and depth budget
- Soundness of `genLExpr` (every generated expression is well-typed)
- `SetGen.IsSoundAndComplete` instance for `genLMonoTy`
-/

-- ── bvarsOfType spec ──────────────────────────────────────────────────

/-- Characterization of `bvarsOfType.go`: index `i` is in the result iff
    it corresponds to a position in `bctx` with type `τ`, offset by `base`. -/
private theorem bvarsOfType_go_spec (τ : LMonoTy) :
    ∀ (bctx : BVarCtx) (base i : Nat),
      i ∈ bvarsOfType.go τ bctx base ↔
        ∃ k, k < bctx.length ∧ i = base + k ∧ bctx[k]? = some τ := by
  intro bctx
  induction bctx with
  | nil => simp [bvarsOfType.go]
  | cons τ' rest ih =>
    intro base i
    simp only [bvarsOfType.go]
    split
    · rename_i heq
      have hτeq : τ' = τ := beq_iff_eq.mp heq
      simp only [List.mem_cons]; rw [ih]
      constructor
      · rintro (rfl | ⟨k, hk, rfl, hget⟩)
        · exact ⟨0, by simp, by omega, by simp [hτeq]⟩
        · exact ⟨k + 1, by simp; omega, by omega,
            by simp [List.getElem?_cons_succ]; exact hget⟩
      · rintro ⟨k, hk, hx, hget⟩
        match k with
        | 0 => simp at hget; left; omega
        | k + 1 =>
          right; exact ⟨k, by simp at hk; omega, by omega,
            by simp [List.getElem?_cons_succ] at hget; exact hget⟩
    · rename_i heq
      have hτne : τ' ≠ τ := fun h => absurd (beq_iff_eq.mpr h) heq
      rw [ih]
      constructor
      · rintro ⟨k, hk, rfl, hget⟩
        exact ⟨k + 1, by simp; omega, by omega,
          by simp [List.getElem?_cons_succ]; exact hget⟩
      · rintro ⟨k, hk, hx, hget⟩
        match k with
        | 0 =>
          simp at hget
          exact absurd hget hτne
        | k + 1 =>
          exact ⟨k, by simp at hk; omega, by omega,
            by simp [List.getElem?_cons_succ] at hget; exact hget⟩

/-- `i ∈ bvarsOfType bctx τ` iff `bctx[i]? = some τ`. -/
private theorem bvarsOfType_mem_iff (bctx : BVarCtx) (τ : LMonoTy) (i : Nat) :
    i ∈ bvarsOfType bctx τ ↔ bctx[i]? = some τ := by
  unfold bvarsOfType
  rw [bvarsOfType_go_spec]
  constructor
  · rintro ⟨k, _, rfl, hget⟩; simpa using hget
  · intro hget
    have hlt : i < bctx.length := by
      rw [List.getElem?_eq_some_iff] at hget; exact hget.1
    exact ⟨i, hlt, by omega, hget⟩

-- ── pickBVar soundness/completeness ───────────────────────────────────

/-- Soundness of `pickBVar`: every generated bvar expression is well-typed. -/
private theorem pickBVar_sound (bctx : BVarCtx) (τ : LMonoTy)
    (hv : (bvarsOfType bctx τ).length > 0) (e : LExpr')
    (he : e ∈ SetGen.support (pickBVar (G := SetGen.Set) bctx τ hv)) :
    HasTypeA' bctx e τ := by
  simp only [pickBVar, mem_support_iff, Set.mem_bind, Set.mem_pure] at he
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := he
  subst heq
  apply LExpr.HasTypeA.bvar
  rw [← bvarsOfType_mem_iff]
  set indices := bvarsOfType bctx τ
  have hlt : idx.down < indices.length := by omega
  have : indices.getD idx.down 0 = indices[idx.down] := by
    simp [List.getD, List.getElem?_eq_getElem hlt]
  rw [this]
  exact List.getElem_mem hlt

/-- Completeness of `pickBVar`: any bvar with the right type is in the support. -/
private theorem pickBVar_complete (bctx : BVarCtx) (τ : LMonoTy) (i : Nat)
    (hget : bctx[i]? = some τ)
    (hv : (bvarsOfType bctx τ).length > 0) :
    .bvar () i ∈ SetGen.support (pickBVar (G := SetGen.Set) bctx τ hv) := by
  simp only [pickBVar, mem_support_iff, Set.mem_bind, Set.mem_pure]
  have hmem : i ∈ bvarsOfType bctx τ := (bvarsOfType_mem_iff bctx τ i).mpr hget
  obtain ⟨idx, hidx_lt, hidx_eq⟩ := List.getElem_of_mem hmem
  have : idx ≤ (bvarsOfType bctx τ).length - 1 := by omega
  refine ⟨⟨idx⟩, ⟨Nat.zero_le _, this⟩, ?_⟩
  simp [List.getD, List.getElem?_eq_getElem hidx_lt, hidx_eq]

-- ── pickFVar soundness/completeness ───────────────────────────────────

/-- `x ∈ fvarsOfType fctx τ` iff `(x, τ) ∈ fctx`. -/
private theorem fvarsOfType_mem_iff (fctx : FVarCtx) (τ : LMonoTy) (x : String) :
    x ∈ fvarsOfType fctx τ ↔ (x, τ) ∈ fctx := by
  simp only [fvarsOfType, List.mem_filterMap]
  constructor
  · rintro ⟨⟨y, ty⟩, hmem, hif⟩
    simp only at hif
    split at hif
    · rename_i heq
      have := beq_iff_eq.mp heq
      simp at hif; subst hif; subst this; exact hmem
    · simp at hif
  · intro hmem
    refine ⟨(x, τ), hmem, ?_⟩
    simp only
    split
    · simp
    · rename_i hne; exact absurd (beq_iff_eq.mpr rfl) hne

/-- Soundness of `pickFVar`: every generated fvar expression is well-typed. -/
private theorem pickFVar_sound (fctx : FVarCtx) (τ : LMonoTy)
    (hv : (fvarsOfType fctx τ).length > 0) (e : LExpr')
    (he : e ∈ SetGen.support (pickFVar (G := SetGen.Set) fctx τ hv)) :
    HasTypeA' bctx e τ := by
  simp only [pickFVar, mem_support_iff, Set.mem_bind, Set.mem_pure] at he
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := he
  subst heq
  exact .fvar

/-- Completeness of `pickFVar`: any fvar with the right type is in the support. -/
private theorem pickFVar_complete (fctx : FVarCtx) (τ : LMonoTy) (x : String)
    (hmem : (x, τ) ∈ fctx)
    (hv : (fvarsOfType fctx τ).length > 0) :
    .fvar () ⟨x, ()⟩ (some τ) ∈ SetGen.support (pickFVar (G := SetGen.Set) fctx τ hv) := by
  simp only [pickFVar, mem_support_iff, Set.mem_bind, Set.mem_pure]
  have hmem' : x ∈ fvarsOfType fctx τ := (fvarsOfType_mem_iff fctx τ x).mpr hmem
  obtain ⟨idx, hidx_lt, hidx_eq⟩ := List.getElem_of_mem hmem'
  have : idx ≤ (fvarsOfType fctx τ).length - 1 := by omega
  refine ⟨⟨idx⟩, ⟨Nat.zero_le _, this⟩, ?_⟩
  simp [List.getD, List.getElem?_eq_getElem hidx_lt, hidx_eq]

-- ── pickOp soundness/completeness ─────────────────────────────────────

/-- `x ∈ opsOfType octx τ` iff `(x, τ) ∈ octx`. -/
private theorem opsOfType_mem_iff (octx : OpCtx) (τ : LMonoTy) (x : String) :
    x ∈ opsOfType octx τ ↔ (x, τ) ∈ octx := by
  simp only [opsOfType, List.mem_filterMap]
  constructor
  · rintro ⟨⟨y, ty⟩, hmem, hif⟩
    simp only at hif
    split at hif
    · rename_i heq
      have := beq_iff_eq.mp heq
      simp at hif; subst hif; subst this; exact hmem
    · simp at hif
  · intro hmem
    refine ⟨(x, τ), hmem, ?_⟩
    simp only
    split
    · simp
    · rename_i hne; exact absurd (beq_iff_eq.mpr rfl) hne

/-- Soundness of `pickOp`: every generated op expression is well-typed. -/
private theorem pickOp_sound (octx : OpCtx) (τ : LMonoTy)
    (hv : (opsOfType octx τ).length > 0) (e : LExpr')
    (he : e ∈ SetGen.support (pickOp (G := SetGen.Set) octx τ hv)) :
    HasTypeA' bctx e τ := by
  simp only [pickOp, mem_support_iff, Set.mem_bind, Set.mem_pure] at he
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := he
  subst heq
  exact .op

/-- Completeness of `pickOp`: any op with the right type is in the support. -/
private theorem pickOp_complete (octx : OpCtx) (τ : LMonoTy) (x : String)
    (hmem : (x, τ) ∈ octx)
    (hv : (opsOfType octx τ).length > 0) :
    .op () ⟨x, ()⟩ (some τ) ∈ SetGen.support (pickOp (G := SetGen.Set) octx τ hv) := by
  simp only [pickOp, mem_support_iff, Set.mem_bind, Set.mem_pure]
  have hmem' : x ∈ opsOfType octx τ := (opsOfType_mem_iff octx τ x).mpr hmem
  obtain ⟨idx, hidx_lt, hidx_eq⟩ := List.getElem_of_mem hmem'
  have : idx ≤ (opsOfType octx τ).length - 1 := by omega
  refine ⟨⟨idx⟩, ⟨Nat.zero_le _, this⟩, ?_⟩
  simp [List.getD, List.getElem?_eq_getElem hidx_lt, hidx_eq]

-- ── pickBiased support lemma ──────────────────────────────────────────

namespace SetGen

@[simp] theorem pickBiased_mem_iff {x y : Set α} (a : α) :
    a ∈ (RandomChoice.pickBiased (fun () => x) (fun () => y) : Set α) ↔ a ∈ x ∨ a ∈ y := by
  simp only [RandomChoice.pickBiased, SetGen.Set.mem_bind]
  constructor
  · rintro ⟨b, _, ha⟩
    cases b with
    | true => left; simpa using ha
    | false => right; simpa using ha
  · intro h
    have htrue : true ∈ (RandomChoice.coin (1 / 10) : Set Bool) := by
      simp only [RandomChoice.coin, Bind.bind, RandomChoice.choose]
      refine ⟨⟨0⟩, ⟨Nat.zero_le _, Nat.zero_le _⟩, ?_⟩
      norm_num [Pure.pure]
    have hfalse : false ∈ (RandomChoice.coin (1 / 10) : Set Bool) := by
      simp only [RandomChoice.coin, Bind.bind, RandomChoice.choose]
      refine ⟨⟨10⟩, ⟨Nat.zero_le _, by norm_num⟩, ?_⟩
      norm_num [Pure.pure]
    cases h with
    | inl hx => exact ⟨true, htrue, by simpa⟩
    | inr hy => exact ⟨false, hfalse, by simpa⟩

@[simp] theorem mem_support_pickBiased_iff {x y : Set α} :
    a ∈ support (RandomChoice.pickBiased (fun () => x) (fun () => y)) ↔
    a ∈ support x ∨ a ∈ support y := by
  simp [support, pickBiased_mem_iff]

end SetGen

-- ── genLMonoTy support ────────────────────────────────────────────────

/-- All ftvar names in a type belong to `tvars`. -/
def allFtvarsIn (tvars : List TyIdentifier) : LMonoTy → Prop
  | .ftvar name => name ∈ tvars
  | .tcons _ args => ∀ a ∈ args, allFtvarsIn tvars a
  | .bitvec _ => True

/-- Soundness of `pickTyVar`: any type in the support is `.ftvar name` for some `name ∈ tvars`. -/
private theorem pickTyVar_mem (tvars : List TyIdentifier) (h : tvars.length > 0) (τ : LMonoTy)
    (hτ : τ ∈ SetGen.support (pickTyVar (G := SetGen.Set) tvars h)) :
    ∃ name, name ∈ tvars ∧ τ = .ftvar name := by
  simp only [pickTyVar, mem_support_bind_iff, mem_support_choose_iff,
             mem_support_pure_iff] at hτ
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := hτ
  subst heq
  have hlt : idx.down < tvars.length := by omega
  refine ⟨tvars.getD idx.down "", ?_, rfl⟩
  have : tvars.getD idx.down "" = tvars[idx.down] := by
    simp [List.getD, List.getElem?_eq_getElem hlt]
  rw [this]
  exact List.getElem_mem hlt

/-- Completeness of `pickTyVar`: `.ftvar name` is in the support for any `name ∈ tvars`. -/
private theorem pickTyVar_complete (tvars : List TyIdentifier)
    (h : tvars.length > 0) (name : TyIdentifier)
    (hmem : name ∈ tvars) :
    LMonoTy.ftvar name ∈ SetGen.support (pickTyVar (G := SetGen.Set) tvars h) := by
  simp only [pickTyVar, mem_support_bind_iff, mem_support_choose_iff,
             mem_support_pure_iff]
  obtain ⟨idx, hidx_lt, hidx_eq⟩ := List.getElem_of_mem hmem
  have hle : idx ≤ tvars.length - 1 := by omega
  refine ⟨⟨idx⟩, ⟨Nat.zero_le _, hle⟩, ?_⟩
  simp [List.getD, List.getElem?_eq_getElem hidx_lt, hidx_eq]

/-- `allFtvarsIn` is vacuously true for `.bool` (no ftvars). -/
private theorem allFtvarsIn_bool (tvars : List TyIdentifier) :
    allFtvarsIn tvars .bool := by simp [allFtvarsIn, LMonoTy.bool]
/-- `allFtvarsIn` is vacuously true for `.int` (no ftvars). -/
private theorem allFtvarsIn_int (tvars : List TyIdentifier) :
    allFtvarsIn tvars .int := by simp [allFtvarsIn, LMonoTy.int]
/-- Introduce `allFtvarsIn` for an ftvar from list membership. -/
private theorem allFtvarsIn_ftvar {tvars : List TyIdentifier} {name : TyIdentifier}
    (h : name ∈ tvars) : allFtvarsIn tvars (.ftvar name) := by
  unfold allFtvarsIn; exact h
/-- Eliminate `allFtvarsIn` for an ftvar to list membership. -/
private theorem allFtvarsIn_ftvar_inv {tvars : List TyIdentifier} {name : TyIdentifier}
    (h : allFtvarsIn tvars (.ftvar name)) : name ∈ tvars := by
  unfold allFtvarsIn at h; exact h
/-- `allFtvarsIn` for an arrow type splits into a conjunction over its components. -/
private theorem allFtvarsIn_arrow {tvars : List TyIdentifier} {τ₁ τ₂ : LMonoTy} :
    allFtvarsIn tvars (.arrow τ₁ τ₂) ↔ allFtvarsIn tvars τ₁ ∧ allFtvarsIn tvars τ₂ := by
  simp [allFtvarsIn, LMonoTy.arrow]

/-- Support characterization of `genLMonoTy` at depth 0. -/
private theorem genLMonoTy_zero_mem (tvars : List TyIdentifier) (τ : LMonoTy) :
    τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) tvars 0) ↔
      SimpleType τ ∧ monoTyDepth τ ≤ 0 ∧ allFtvarsIn tvars τ := by
  simp only [genLMonoTy, mem_support_dite_iff, mem_support_pick_iff,
             mem_support_pure_iff]
  constructor
  · intro he
    rcases he with (⟨htv, (rfl | (rfl | hftv))⟩ | ⟨htv, (rfl | rfl)⟩)
    · exact ⟨SimpleType.bool, Nat.le_refl _, allFtvarsIn_bool _⟩
    · exact ⟨SimpleType.int, Nat.le_refl _, allFtvarsIn_int _⟩
    · obtain ⟨name, hmem, rfl⟩ := pickTyVar_mem tvars htv _ hftv
      exact ⟨SimpleType.ftvar, Nat.le_refl _, allFtvarsIn_ftvar hmem⟩
    · exact ⟨SimpleType.bool, Nat.le_refl _, allFtvarsIn_bool _⟩
    · exact ⟨SimpleType.int, Nat.le_refl _, allFtvarsIn_int _⟩
  · intro ⟨hs, hd, hftv⟩
    by_cases htv : tvars.length > 0
    · left; refine ⟨htv, ?_⟩
      cases hs with
      | bool => left; rfl
      | int => right; left; rfl
      | ftvar =>
        rename_i name
        right; right; exact pickTyVar_complete tvars htv name (allFtvarsIn_ftvar_inv hftv)
      | arrow => simp [monoTyDepth, LMonoTy.arrow] at hd
    · right; refine ⟨htv, ?_⟩
      cases hs with
      | bool => left; rfl
      | int => right; rfl
      | ftvar =>
        rename_i name
        exact absurd (List.length_pos_of_mem (allFtvarsIn_ftvar_inv hftv)) (by omega)
      | arrow => simp [monoTyDepth, LMonoTy.arrow] at hd

/-- Support characterization of `genLMonoTy` at depth `n + 1` (inductive step). -/
private theorem genLMonoTy_succ_mem (tvars : List TyIdentifier) (n : Nat) (τ : LMonoTy)
    (ih : ∀ τ, τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) tvars n) ↔
      SimpleType τ ∧ monoTyDepth τ ≤ n ∧ allFtvarsIn tvars τ) :
    τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) tvars (n + 1)) ↔
      SimpleType τ ∧ monoTyDepth τ ≤ n + 1 ∧ allFtvarsIn tvars τ := by
  simp only [genLMonoTy, mem_support_dite_iff, mem_support_pickBiased_iff, mem_support_pick_iff,
             mem_support_pure_iff, mem_support_bind_iff]
  constructor
  · intro he
    rcases he with (⟨htv, ((rfl | rfl) | (⟨τ₁, hτ₁, τ₂, hτ₂, rfl⟩ | hftv))⟩ |
                    ⟨htv, ((rfl | rfl) | ⟨τ₁, hτ₁, τ₂, hτ₂, rfl⟩)⟩)
    · exact ⟨SimpleType.bool, Nat.zero_le _, allFtvarsIn_bool _⟩
    · exact ⟨SimpleType.int, Nat.zero_le _, allFtvarsIn_int _⟩
    · have ⟨hs₁, hd₁, hf₁⟩ := (ih τ₁).mp hτ₁
      have ⟨hs₂, hd₂, hf₂⟩ := (ih τ₂).mp hτ₂
      refine ⟨SimpleType.arrow hs₁ hs₂, ?_, allFtvarsIn_arrow.mpr ⟨hf₁, hf₂⟩⟩
      show max (monoTyDepth τ₁) (monoTyDepth τ₂) + 1 ≤ n + 1; omega
    · obtain ⟨name, hmem, rfl⟩ := pickTyVar_mem tvars htv _ hftv
      exact ⟨SimpleType.ftvar, Nat.zero_le _, allFtvarsIn_ftvar hmem⟩
    · exact ⟨SimpleType.bool, Nat.zero_le _, allFtvarsIn_bool _⟩
    · exact ⟨SimpleType.int, Nat.zero_le _, allFtvarsIn_int _⟩
    · have ⟨hs₁, hd₁, hf₁⟩ := (ih τ₁).mp hτ₁
      have ⟨hs₂, hd₂, hf₂⟩ := (ih τ₂).mp hτ₂
      refine ⟨SimpleType.arrow hs₁ hs₂, ?_, allFtvarsIn_arrow.mpr ⟨hf₁, hf₂⟩⟩
      show max (monoTyDepth τ₁) (monoTyDepth τ₂) + 1 ≤ n + 1; omega
  · intro ⟨hs, hd, hftv⟩
    by_cases htv : tvars.length > 0
    · left; refine ⟨htv, ?_⟩
      cases hs with
      | bool => left; left; rfl
      | int => left; right; rfl
      | arrow hs₁ hs₂ =>
        right; left
        rename_i τ₁ τ₂
        have hd' : max (monoTyDepth τ₁) (monoTyDepth τ₂) + 1 ≤ n + 1 := hd
        have ⟨hf₁, hf₂⟩ := allFtvarsIn_arrow.mp hftv
        exact ⟨τ₁, (ih τ₁).mpr ⟨hs₁, by omega, hf₁⟩,
               τ₂, (ih τ₂).mpr ⟨hs₂, by omega, hf₂⟩, rfl⟩
      | ftvar =>
        rename_i name
        right; right; exact pickTyVar_complete tvars htv name (allFtvarsIn_ftvar_inv hftv)
    · right; refine ⟨htv, ?_⟩
      cases hs with
      | bool => left; left; rfl
      | int => left; right; rfl
      | arrow hs₁ hs₂ =>
        right
        rename_i τ₁ τ₂
        have hd' : max (monoTyDepth τ₁) (monoTyDepth τ₂) + 1 ≤ n + 1 := hd
        have ⟨hf₁, hf₂⟩ := allFtvarsIn_arrow.mp hftv
        exact ⟨τ₁, (ih τ₁).mpr ⟨hs₁, by omega, hf₁⟩,
               τ₂, (ih τ₂).mpr ⟨hs₂, by omega, hf₂⟩, rfl⟩
      | ftvar =>
        rename_i name
        exact absurd (List.length_pos_of_mem (allFtvarsIn_ftvar_inv hftv)) (by omega)

/-- Full support characterization of `genLMonoTy`: it generates exactly the simple types
    of depth ≤ `n` whose ftvar names all belong to `tvars`. -/
theorem genLMonoTy_support (tvars : List TyIdentifier) (n : Nat) (τ : LMonoTy) :
    τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) tvars n) ↔
      SimpleType τ ∧ monoTyDepth τ ≤ n ∧ allFtvarsIn tvars τ := by
  induction n generalizing τ with
  | zero => exact genLMonoTy_zero_mem tvars τ
  | succ n ih => exact genLMonoTy_succ_mem tvars n τ ih

/-- Corollary: anything generated by `genLMonoTy` is a `SimpleType`. -/
theorem genLMonoTy_simple (tvars : List TyIdentifier) (n : Nat) (τ : LMonoTy)
    (h : τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) tvars n)) : SimpleType τ :=
  ((genLMonoTy_support tvars n τ).mp h).1

-- ── Soundness for genLExpr ────────────────────────────────────────────

-- `LMonoTy.bool`, `.int`, `.arrow` are abbreviations for `.tcons "bool" []` etc.
-- In Strata, they're defined as abbreviations via the `abbrev` keyword,
-- e.g. `abbrev LMonoTy.arrow τ₁ τ₂ := .tcons "arrow" [τ₁, τ₂]`.
-- Now, when we define `genLExpr` via pattern-matching,
-- Lean's automatically generated equational lemmas are defined in terms of the expanded constructor,
-- i.e. `LmonoTy.tcons "arrow" [τ₁, τ₂]` instead of `LMonoTy.arrow τ₁ τ₂`.
-- Thus, when we have a hypothesis that mentions `genLExpr`, e.g. `he : e ∈ support (genLExpr fctx octx tvars bctx 0 (LMonoTy.arrow τ₁ τ₂))`,
-- when we try to naively do `simp only [genLExpr]`,
-- Lean tries to match `LMonoTy.tcons "arrow" [τ₁, τ₂]` against the subterm `LMonoTy.arrow τ₁ τ₂` in the hypothesis.
-- Even though the two terms are definitionally equal, the `simp/rw` tactics require syntactic equality,
-- so we have to add the following rewrite lemmas which normalize the abbreviation,
-- so that the equation lemmas can match.
/-- Normalize `.bool` abbreviation so `simp [genLExpr]` equation lemmas can match. -/
private theorem norm_bool : LMonoTy.bool = LMonoTy.tcons "bool" [] := rfl
/-- Normalize `.int` abbreviation so `simp [genLExpr]` equation lemmas can match. -/
private theorem norm_int : LMonoTy.int = LMonoTy.tcons "int" [] := rfl
/-- Normalize `.arrow` abbreviation so `simp [genLExpr]` equation lemmas can match. -/
private theorem norm_arrow (τ₁ τ₂ : LMonoTy) :
    LMonoTy.arrow τ₁ τ₂ = LMonoTy.tcons "arrow" [τ₁, τ₂] := rfl


set_option maxHeartbeats 800000 in
/-- Every expression in the support of `genLExpr fctx octx tvars bctx depth τ` is
    well-typed whenever `τ` is a `SimpleType`. -/
theorem genLExprBase_sound (fctx : FVarCtx) (octx : OpCtx)
    (tvars : List TyIdentifier)
    (bctx : BVarCtx) (depth : Nat) (τ : LMonoTy)
    (hτ : SimpleType τ) (e : LExpr')
    (he : e ∈ SetGen.support (genLExprBase (G := SetGen.Set) fctx octx tvars bctx depth τ)) :
    HasTypeA' bctx e τ := by
  match depth, τ, hτ with
  | 0, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExprBase, pick_mem_iff,
      mem_support_iff, SetGen.mem_dite] at he
    rcases he with (rfl | rfl) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | (⟨_, h⟩ | ⟨_, rfl | rfl⟩)))
    all_goals first
      | exact (by unfold LExpr.boolConst; exact .const)
      | exact pickBVar_sound bctx .bool _ _ h
      | exact pickFVar_sound fctx .bool _ _ h
      | exact pickOp_sound octx .bool _ _ h
  | 0, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨k, _, rfl⟩ | ⟨k, _, rfl⟩) | ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | (⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩)))
    all_goals first
      | exact (by unfold LExpr.intConst; exact .const)
      | exact pickBVar_sound bctx .int _ _ h
      | exact pickFVar_sound fctx .int _ _ h
      | exact pickOp_sound octx .int _ _ h
  | 0, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExprBase, pick_mem_iff,
      mem_support_iff, SetGen.mem_dite, bot_mem_iff] at he
    rcases he with (⟨_, h⟩ | ⟨_, h⟩) | ((⟨_, h⟩ | ⟨_, h⟩) | (⟨_, h⟩ | ⟨_, h⟩))
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact absurd h (by simp)
  | n + 1, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExprBase, pickBiased_mem_iff, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (rfl | rfl) | ⟨c, hc, t, ht, e', he', rfl⟩ | ⟨τ', hτ'm, e₁, he₁, e₂, he₂, rfl⟩ |
      ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | (⟨_, h⟩ | ⟨_, rfl | rfl⟩)))
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact .ite (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.bool _ ht)
                  (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.bool _ he')
    · exact .eq (genLExprBase_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ he₁)
                 (genLExprBase_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ he₂)
    · exact .app (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.bool) _ hfn)
                  (genLExprBase_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .quant (genLExprBase_sound fctx octx tvars (τ' :: bctx) n _ (genLMonoTy_simple tvars n _ hτ_tr_m) _ htr)
                    (genLExprBase_sound fctx octx tvars (τ' :: bctx) n _ SimpleType.bool _ hbody)
    · exact .quant (genLExprBase_sound fctx octx tvars (τ' :: bctx) n _ (genLMonoTy_simple tvars n _ hτ_tr_m) _ htr)
                    (genLExprBase_sound fctx octx tvars (τ' :: bctx) n _ SimpleType.bool _ hbody)
    all_goals first
      | exact pickBVar_sound bctx .bool _ _ h
      | exact pickFVar_sound fctx .bool _ _ h
      | exact pickOp_sound octx .bool _ _ h
      | exact (by unfold LExpr.boolConst; exact .const)
  | n + 1, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExprBase, pickBiased_mem_iff, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨k, _, rfl⟩ | ⟨k, _, rfl⟩) | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | (⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩)))
    · exact (by unfold LExpr.intConst; exact .const)
    · exact (by unfold LExpr.intConst; exact .const)
    · exact .app (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.int) _ hfn)
                  (genLExprBase_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .ite (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.int _ ht)
                  (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.int _ he')
    all_goals first
      | exact pickBVar_sound bctx .int _ _ h
      | exact pickFVar_sound fctx .int _ _ h
      | exact pickOp_sound octx .int _ _ h
      | exact (by unfold LExpr.intConst; exact .const)
  | n + 1, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with ⟨body, hbody, rfl⟩ | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | ((⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | (⟨_, h⟩ | ⟨_, body, hbody, rfl⟩)))
    · exact .abs (genLExprBase_sound fctx octx tvars (τ₁ :: bctx) n _ hs₂ _ hbody)
    · exact .app (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) (SimpleType.arrow hs₁ hs₂)) _ hfn)
                  (genLExprBase_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .ite (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow hs₁ hs₂) _ ht)
                  (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow hs₁ hs₂) _ he')
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact .abs (genLExprBase_sound fctx octx tvars (τ₁ :: bctx) n _ hs₂ _ hbody)
  | 0, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExprBase, pick_mem_iff, mem_support_iff, SetGen.mem_dite,
               bot_mem_iff] at he
    rcases he with (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
      ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
       (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩))
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact absurd h (by simp)
  | n + 1, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
               mem_support_iff, SetGen.mem_dite, bot_mem_iff] at he
    rcases he with ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
       ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩) |
        (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩)))
    · exact .app (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.ftvar) _ hfn)
                  (genLExprBase_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .ite (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.ftvar _ ht)
                  (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.ftvar _ he')
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact absurd h (by simp)
  termination_by (depth, sizeOf τ)
  decreasing_by all_goals simp_wf; omega

-- The commented proof sketch for `genLExprBase_termDepth_bound` has been moved
-- below the `termDepth` definition. See `genLExprBase_termDepth_bound` after
-- the completeness proof section.

/-  Old proof sketch for genLExprBase_termDepth_bound (reference only)
  match depth, τ, hτ with
  | 0, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExprBase, pick_mem_iff,
      mem_support_iff, SetGen.mem_dite] at he
    rcases he with (rfl | rfl) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | (⟨_, h⟩ | ⟨_, rfl | rfl⟩)))
    all_goals first | rfl | (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _))
  | 0, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨k, _, rfl⟩ | ⟨k, _, rfl⟩) | ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | (⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩)))
    all_goals first | rfl | (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _))
  | 0, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExprBase, pick_mem_iff,
      mem_support_iff, SetGen.mem_dite, bot_mem_iff] at he
    rcases he with (⟨_, h⟩ | ⟨_, h⟩) | ((⟨_, h⟩ | ⟨_, h⟩) | (⟨_, h⟩ | ⟨_, h⟩))
    all_goals (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | exact absurd h (by simp))
  | n + 1, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (rfl | rfl) | ⟨c, hc, t, ht, e', he', rfl⟩ | ⟨τ', hτ'm, e₁, he₁, e₂, he₂, rfl⟩ |
      ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | (⟨_, h⟩ | ⟨_, rfl | rfl⟩)))
    · exact Nat.zero_le _
    · exact Nat.zero_le _
    · show termDepth bctx (.ite () c t e') ≤ n + 1
      unfold termDepth
      have hc' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ hc
      have ht' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ ht
      have he'' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ he'
      omega
    · show termDepth bctx (.eq () e₁ e₂) ≤ n + 1
      unfold termDepth
      have h₁ := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ he₁
      have h₂ := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ he₂
      omega
    · show termDepth bctx (.app () fn arg) ≤ n + 1
      unfold termDepth
      have hfn' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.bool) _ hfn
      have harg' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg
      omega
    · show termDepth bctx (.quant () .all "" (some τ') tr body) ≤ n + 1
      unfold termDepth
      have htr' := genLExprBase_termDepth_bound fctx octx tvars (τ' :: bctx) n _ (genLMonoTy_simple tvars n _ hτ_tr_m) _ htr
      have hbody' := genLExprBase_termDepth_bound fctx octx tvars (τ' :: bctx) n _ SimpleType.bool _ hbody
      have hd := ((genLMonoTy_support tvars n τ').mp hτ'm).2.1
      omega
    · show termDepth bctx (.quant () .exist "" (some τ') tr body) ≤ n + 1
      unfold termDepth
      have htr' := genLExprBase_termDepth_bound fctx octx tvars (τ' :: bctx) n _ (genLMonoTy_simple tvars n _ hτ_tr_m) _ htr
      have hbody' := genLExprBase_termDepth_bound fctx octx tvars (τ' :: bctx) n _ SimpleType.bool _ hbody
      have hd := ((genLMonoTy_support tvars n τ').mp hτ'm).2.1
      omega
    all_goals first | exact Nat.zero_le _ | (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _))
  | n + 1, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨k, _, rfl⟩ | ⟨k, _, rfl⟩) | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | (⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩)))
    · exact Nat.zero_le _
    · exact Nat.zero_le _
    · show termDepth bctx (.app () fn arg) ≤ n + 1
      unfold termDepth
      have hfn' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.int) _ hfn
      have harg' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg
      omega
    · show termDepth bctx (.ite () c t e') ≤ n + 1
      unfold termDepth
      have hc' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ hc
      have ht' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.int _ ht
      have he'' := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.int _ he'
      omega
    all_goals first | exact Nat.zero_le _ | (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _))
  | n + 1, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with ⟨body, hbody, rfl⟩ | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | ((⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | (⟨_, h⟩ | ⟨_, body, hbody, rfl⟩)))
    · exact .abs (genLExprBase_sound fctx octx tvars (τ₁ :: bctx) n _ hs₂ _ hbody)
    · exact .app (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) (SimpleType.arrow hs₁ hs₂)) _ hfn)
                  (genLExprBase_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .ite (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow hs₁ hs₂) _ ht)
                  (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow hs₁ hs₂) _ he')
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact .abs (genLExprBase_sound fctx octx tvars (τ₁ :: bctx) n _ hs₂ _ hbody)
  | 0, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExprBase, pick_mem_iff, mem_support_iff, SetGen.mem_dite,
               bot_mem_iff] at he
    rcases he with (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
      ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
       (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩))
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact absurd h (by simp)
  | n + 1, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
               mem_support_iff, SetGen.mem_dite, bot_mem_iff] at he
    rcases he with ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
       ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩) |
        (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩)))
    · exact .app (genLExprBase_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.ftvar) _ hfn)
                  (genLExprBase_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .ite (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.ftvar _ ht)
                  (genLExprBase_sound fctx octx tvars bctx n _ SimpleType.ftvar _ he')
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact absurd h (by simp)
  termination_by (depth, sizeOf τ)
  decreasing_by all_goals simp_wf; omega
-/

-- ── Nat.arbitrary support for SetGen.Set ──────────────────────────────

/-- Every natural number is in the support of `Nat.arbitrary` at `SetGen.Set`. -/
private theorem Nat_arbitrary_support_set (n : Nat) :
    n ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)) := by
  induction n with
  | zero =>
    simp only [SetGen.support]
    rw [Nat.arbitrary]
    simp [pick_mem_iff]
  | succ n ih =>
    simp only [SetGen.support] at ih ⊢
    rw [Nat.arbitrary]
    simp only [pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure]
    right
    exact ⟨n, ih, rfl⟩

/-- Every integer is reachable via `pick` between `(k : Int)` and `-(k+1)`. -/
private theorem Int_cover (z : Int) :
    (∃ k : Nat, k ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)) ∧ (↑k : Int) = z) ∨
    (∃ k : Nat, k ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)) ∧ (-(↑k + 1 : Int)) = z) := by
  cases z with
  | ofNat n => left; exact ⟨n, Nat_arbitrary_support_set n, rfl⟩
  | negSucc n => right; exact ⟨n, Nat_arbitrary_support_set n, by simp [Int.negSucc_eq]⟩

-- ── emptyNames predicate ──────────────────────────────────────────────

/-- All binder names in the expression are empty strings. -/
def emptyNames : LExpr' → Prop
  | .boolConst () _                  => True
  | .intConst () _                   => True
  | .bvar () _                       => True
  | .fvar () _ _                     => True
  | .op () _ _                       => True
  | .abs () name _ body              => name = "" ∧ emptyNames body
  | .app () fn arg                   => emptyNames fn ∧ emptyNames arg
  | .ite () c t e                    => emptyNames c ∧ emptyNames t ∧ emptyNames e
  | .eq () e₁ e₂                     => emptyNames e₁ ∧ emptyNames e₂
  | .quant () _ name _ tr body       => name = "" ∧ emptyNames tr ∧ emptyNames body
  | .const () _                      => True

-- ── termDepth measure ─────────────────────────────────────────────────

/-- The tree depth of a term: the minimum `depth` parameter for which
    `genLExpr` can produce the term. This coincides with the generator's
    fuel consumption because:
    - Leaf expressions (bvar, fvar, op, const) have depth 0.
    - Each compound constructor (abs, app, ite, eq, quant) adds 1.
    - The generator recurses at `depth - 1` for each child.
    - The `quant` case also incorporates `monoTyDepth τ` since the generator
      calls `genLMonoTy (depth - 1)` which requires `monoTyDepth τ ≤ depth - 1`. -/
def termDepth (bctx : BVarCtx) : LExpr' → Nat
  | .boolConst () _       => 0
  | .intConst () _        => 0
  | .bvar () _            => 0
  | .fvar () _ _          => 0
  | .op () _ _            => 0
  | .abs () _ (some τ₁) body => termDepth (τ₁ :: bctx) body + 1
  | .app () fn arg        => max (termDepth bctx fn) (termDepth bctx arg) + 1
  | .ite () c t e         => max (termDepth bctx c) (max (termDepth bctx t) (termDepth bctx e)) + 1
  | .eq () e₁ e₂          => max (termDepth bctx e₁) (termDepth bctx e₂) + 1
  | .quant () _ _ (some τ) tr body =>
      max (monoTyDepth τ) (max (termDepth (τ :: bctx) tr) (termDepth (τ :: bctx) body)) + 1
  | _                     => 0

/-- All type annotations occurring in an expression are simple, have depth bounded
    appropriately, and have all ftvar names drawn from `tvars`.
    The `n` parameter decreases by 1 at each compound expression level,
    matching the generator's fuel consumption. At level `n+1`, intermediate types
    produced by `genLMonoTy n` have depth ≤ `n`, and sub-expressions need `AllTypesSimple n`. -/
inductive AllTypesSimple (tvars : List TyIdentifier) : Nat → BVarCtx → LExpr' → Prop where
  | boolConst : AllTypesSimple tvars n bctx (.boolConst () b)
  | intConst  : AllTypesSimple tvars n bctx (.intConst () k)
  | bvar      : AllTypesSimple tvars n bctx (.bvar () i)
  | fvar      : AllTypesSimple tvars n bctx (.fvar () x (some τ))
  | op        : AllTypesSimple tvars n bctx (.op () o (some τ))
  | abs       : SimpleType τ₁ → monoTyDepth τ₁ ≤ n → allFtvarsIn tvars τ₁ →
                AllTypesSimple tvars n (τ₁ :: bctx) body →
                AllTypesSimple tvars (n + 1) bctx (.abs () "" (some τ₁) body)
  | app       : (τ' : LMonoTy) →
                HasTypeA' bctx arg τ' →
                SimpleType τ' → monoTyDepth τ' ≤ n → allFtvarsIn tvars τ' →
                AllTypesSimple tvars n bctx fn → AllTypesSimple tvars n bctx arg →
                AllTypesSimple tvars (n + 1) bctx (.app () fn arg)
  | ite       : AllTypesSimple tvars n bctx c → AllTypesSimple tvars n bctx t →
                AllTypesSimple tvars n bctx e →
                AllTypesSimple tvars (n + 1) bctx (.ite () c t e)
  | eq        : (τ' : LMonoTy) →
                HasTypeA' bctx e₁ τ' → HasTypeA' bctx e₂ τ' →
                SimpleType τ' → monoTyDepth τ' ≤ n → allFtvarsIn tvars τ' →
                AllTypesSimple tvars n bctx e₁ → AllTypesSimple tvars n bctx e₂ →
                AllTypesSimple tvars (n + 1) bctx (.eq () e₁ e₂)
  | quant     : SimpleType τ → monoTyDepth τ ≤ n → allFtvarsIn tvars τ →
                (τ_tr : LMonoTy) → SimpleType τ_tr → monoTyDepth τ_tr ≤ n →
                allFtvarsIn tvars τ_tr →
                HasTypeA' (τ :: bctx) tr τ_tr →
                AllTypesSimple tvars n (τ :: bctx) tr →
                AllTypesSimple tvars n (τ :: bctx) body →
                AllTypesSimple tvars (n + 1) bctx (.quant () k "" (some τ) tr body)

-- ── termDepth bound for genLExpr ──────────────────────────────────────

set_option maxHeartbeats 1600000 in
/-- Every expression in the support of `genLExpr` at depth `depth` has
    `termDepth ≤ depth`. This is the "bounded soundness" theorem that,
    combined with `genLExprBase_sound` and `genLExprBase_complete`,
    characterize the generator's support. -/
theorem genLExprBase_termDepth_bound (fctx : FVarCtx) (octx : OpCtx)
    (tvars : List TyIdentifier) (bctx : BVarCtx)
    (depth : Nat) (τ : LMonoTy)
    (hτ : SimpleType τ) (e : LExpr')
    (he : e ∈ SetGen.support (genLExprBase (G := SetGen.Set) fctx octx tvars bctx depth τ)) :
    termDepth bctx e ≤ depth := by
  match depth, τ, hτ with
  | 0, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExprBase, pick_mem_iff,
      mem_support_iff, SetGen.mem_dite] at he
    rcases he with (rfl | rfl) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | (⟨_, h⟩ | ⟨_, rfl | rfl⟩)))
    all_goals first | rfl | (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl))
  | 0, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨_, _, rfl⟩ | ⟨_, _, rfl⟩) | ((⟨_, h⟩ | ⟨_, ⟨_, _, rfl⟩ | ⟨_, _, rfl⟩⟩) | ((⟨_, h⟩ | ⟨_, ⟨_, _, rfl⟩ | ⟨_, _, rfl⟩⟩) | (⟨_, h⟩ | ⟨_, ⟨_, _, rfl⟩ | ⟨_, _, rfl⟩⟩)))
    all_goals first | rfl | (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl))
  | 0, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExprBase, pick_mem_iff,
      mem_support_iff, SetGen.mem_dite, bot_mem_iff] at he
    rcases he with (⟨_, h⟩ | ⟨_, h⟩) | ((⟨_, h⟩ | ⟨_, h⟩) | (⟨_, h⟩ | ⟨_, h⟩))
    all_goals (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | exact absurd h (by simp))
  | n + 1, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExprBase, pickBiased_mem_iff, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (rfl | rfl) | ⟨c, hc, t, ht, e', he', rfl⟩ | ⟨τ', hτ'm, e₁, he₁, e₂, he₂, rfl⟩ |
      ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | (⟨_, h⟩ | ⟨_, rfl | rfl⟩)))
    · exact Nat.zero_le _
    · exact Nat.zero_le _
    · show termDepth bctx (.ite () c t e') ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ hc
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ ht
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ he'
      omega
    · show termDepth bctx (.eq () e₁ e₂) ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ he₁
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ he₂
      omega
    · show termDepth bctx (.app () fn arg) ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.bool) _ hfn
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg
      omega
    · show termDepth bctx (.quant () .all "" (some τ') tr body) ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars (τ' :: bctx) n _ (genLMonoTy_simple tvars n _ hτ_tr_m) _ htr
      have := genLExprBase_termDepth_bound fctx octx tvars (τ' :: bctx) n _ SimpleType.bool _ hbody
      have := ((genLMonoTy_support tvars n τ').mp hτ'm).2.1
      omega
    · show termDepth bctx (.quant () .exist "" (some τ') tr body) ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars (τ' :: bctx) n _ (genLMonoTy_simple tvars n _ hτ_tr_m) _ htr
      have := genLExprBase_termDepth_bound fctx octx tvars (τ' :: bctx) n _ SimpleType.bool _ hbody
      have := ((genLMonoTy_support tvars n τ').mp hτ'm).2.1
      omega
    all_goals first | exact Nat.zero_le _ | (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _))
  | n + 1, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExprBase, pickBiased_mem_iff, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨_, _, rfl⟩ | ⟨_, _, rfl⟩) | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, ⟨_, _, rfl⟩ | ⟨_, _, rfl⟩⟩) | ((⟨_, h⟩ | ⟨_, ⟨_, _, rfl⟩ | ⟨_, _, rfl⟩⟩) | (⟨_, h⟩ | ⟨_, ⟨_, _, rfl⟩ | ⟨_, _, rfl⟩⟩)))
    · exact Nat.zero_le _
    · exact Nat.zero_le _
    · show termDepth bctx (.app () fn arg) ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.int) _ hfn
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg
      omega
    · show termDepth bctx (.ite () c t e') ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ hc
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.int _ ht
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.int _ he'
      omega
    all_goals first | exact Nat.zero_le _ | (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _))
  | n + 1, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with ⟨body, hbody, rfl⟩ | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | ((⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | (⟨_, h⟩ | ⟨_, body, hbody, rfl⟩)))
    · show termDepth bctx (.abs () "" (some τ₁) body) ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars (τ₁ :: bctx) n _ hs₂ _ hbody
      omega
    · show termDepth bctx (.app () fn arg) ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) (SimpleType.arrow hs₁ hs₂)) _ hfn
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg
      omega
    · show termDepth bctx (.ite () c t e') ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ hc
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (SimpleType.arrow hs₁ hs₂) _ ht
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (SimpleType.arrow hs₁ hs₂) _ he'
      omega
    all_goals (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (show termDepth bctx (.abs () "" (some τ₁) body) ≤ n + 1; unfold termDepth
         have := genLExprBase_termDepth_bound fctx octx tvars (τ₁ :: bctx) n _ hs₂ _ hbody
         omega))
  | 0, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExprBase, pick_mem_iff, mem_support_iff, SetGen.mem_dite,
               bot_mem_iff] at he
    rcases he with (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
      ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
       (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩))
    all_goals (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; rfl)
      | exact absurd h (by simp))
  | n + 1, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
               mem_support_iff, SetGen.mem_dite, bot_mem_iff] at he
    rcases he with ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
       ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩) |
        (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩)))
    · show termDepth bctx (.app () fn arg) ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.ftvar) _ hfn
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg
      omega
    · show termDepth bctx (.ite () c t e') ≤ n + 1; unfold termDepth
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.bool _ hc
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.ftvar _ ht
      have := genLExprBase_termDepth_bound fctx octx tvars bctx n _ SimpleType.ftvar _ he'
      omega
    all_goals (
      first
      | (simp only [pickBVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickFVar, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | (simp only [pickOp, Set.mem_bind, Set.mem_pure] at h
         obtain ⟨_, _, rfl⟩ := h; exact Nat.zero_le _)
      | exact absurd h (by simp))
  termination_by (depth, sizeOf τ)
  decreasing_by all_goals simp_wf; omega

-- ── Completeness for genLExpr ─────────────────────────────────────────

/-- Inversion lemma: if `.eq () e₁ e₂` has type `τ`, then `τ = .bool`. -/
private theorem eq_hasType_bool {bctx : BVarCtx} {τ : LMonoTy} {e₁ e₂ : LExpr'}
    (h : HasTypeA' bctx (.eq () e₁ e₂) τ) : τ = .bool := by cases h with | eq _ _ => rfl

/-- Inversion lemma: if `.quant () k name (some qty) tr body` has type `τ`, then `τ = .bool`. -/
private theorem quant_hasType_bool {bctx : BVarCtx} {τ : LMonoTy} {k name qty tr body}
    (h : HasTypeA' bctx (.quant () k name (some qty) tr body) τ) : τ = .bool := by
  cases h with | quant _ _ => rfl

/-- Predicate asserting that all fvar names in the expression are in `fctx`
    (with the correct type) and all op names are in the factory `F`. -/
def allVarsInCtx (fctx : FVarCtx) (octx : OpCtx) : LExpr' → Prop
  | .boolConst () _              => True
  | .intConst () _               => True
  | .bvar () _                   => True
  | .fvar () x (some τ)         => (x.name, τ) ∈ fctx
  | .fvar () _ none              => True
  | .op () o (some τ)           => (o.name, τ) ∈ octx
  | .op () _ none                => True
  | .abs () _ _ body             => allVarsInCtx fctx octx body
  | .app () fn arg               => allVarsInCtx fctx octx fn ∧ allVarsInCtx fctx octx arg
  | .ite () c t e                => allVarsInCtx fctx octx c ∧ allVarsInCtx fctx octx t ∧ allVarsInCtx fctx octx e
  | .eq () e₁ e₂                 => allVarsInCtx fctx octx e₁ ∧ allVarsInCtx fctx octx e₂
  | .quant () _ _ _ tr body      => allVarsInCtx fctx octx tr ∧ allVarsInCtx fctx octx body
  | .const () _                  => True

set_option linter.unusedSimpArgs false in
set_option maxHeartbeats 1600000 in
/-- Completeness of `genLExpr`: every well-typed expression whose `termDepth`
    fits within the depth budget is in the support. The `hdepth` precondition
    is tight: the generator provably never produces
    terms exceeding the depth budget (see `genLExprBase_termDepth_bound`),
    so this precondition exactly characterizes reachability. -/
theorem genLExprBase_complete (fctx : FVarCtx) (octx : OpCtx)
    (tvars : List TyIdentifier)
    (bctx : BVarCtx) (depth : Nat) (τ : LMonoTy)
    (hτ : SimpleType τ)
    (e : LExpr')
    (hwt : HasTypeA' bctx e τ)
    (hnames : emptyNames e)
    (hvars : allVarsInCtx fctx octx e)
    (hats : AllTypesSimple tvars depth bctx e)
    (hdepth : termDepth bctx e ≤ depth) :
    e ∈ SetGen.support (genLExprBase (G := SetGen.Set) fctx octx tvars bctx depth τ) := by
  match depth, τ, hτ with
  | 0, _, SimpleType.bool =>
    rw [norm_bool]
    simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | @boolConst _ _ b =>
      cases hwt with
      | const =>
        left
        cases b with
        | true => left; rfl
        | false => right; rfl
    | intConst =>
      exact absurd (HasTypeA_unique hwt .const)
        (by simp [LConst.ty, LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; left; left
        have hlen : (bvarsOfType bctx .bool).length > 0 := by
          have := (bvarsOfType_mem_iff bctx .bool _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx .bool _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx .bool).length > 0 := by
          have := (fvarsOfType_mem_iff fctx .bool _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx .bool _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx .bool).length > 0 := by
          have := (opsOfType_mem_iff octx .bool _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx .bool _ hmem hlen⟩
  | 0, _, SimpleType.int =>
    rw [norm_int]
    simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | intConst =>
      cases hwt with
      | const =>
        left
        have hic := Int_cover (by assumption : Int)
        rcases hic with ⟨k, hk, rfl⟩ | ⟨k, hk, rfl⟩
        · left; exact ⟨k, hk, rfl⟩
        · right; exact ⟨k, hk, rfl⟩
    | boolConst =>
      exact absurd (HasTypeA_unique hwt .const)
        (by simp [LConst.ty, LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; left; left
        have hlen : (bvarsOfType bctx .int).length > 0 := by
          have := (bvarsOfType_mem_iff bctx .int _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx .int _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx .int).length > 0 := by
          have := (fvarsOfType_mem_iff fctx .int _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx .int _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx .int).length > 0 := by
          have := (opsOfType_mem_iff octx .int _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx .int _ hmem hlen⟩
  | 0, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow]
    simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite, bot_mem_iff]
    cases hats with
    | boolConst =>
      exact absurd (HasTypeA_unique hwt .const)
        (by simp [LConst.ty, LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | intConst =>
      exact absurd (HasTypeA_unique hwt .const)
        (by simp [LConst.ty, LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | bvar =>
      cases hwt with
      | bvar hget =>
        left; left
        have hlen : (bvarsOfType bctx (.arrow τ₁ τ₂)).length > 0 := by
          have := (bvarsOfType_mem_iff bctx (.arrow τ₁ τ₂) _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx (.arrow τ₁ τ₂) _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx (.arrow τ₁ τ₂)).length > 0 := by
          have := (fvarsOfType_mem_iff fctx (.arrow τ₁ τ₂) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx (.arrow τ₁ τ₂) _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx (.arrow τ₁ τ₂)).length > 0 := by
          have := (opsOfType_mem_iff octx (.arrow τ₁ τ₂) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx (.arrow τ₁ τ₂) _ hmem hlen⟩
  | n + 1, _, SimpleType.bool =>
    rw [norm_bool]
    simp only [genLExprBase, pickBiased_mem_iff, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | boolConst =>
      cases hwt with
      | const => left; cases (by assumption : Bool) <;> simp [LExpr.boolConst]
    | intConst =>
      exact absurd (HasTypeA_unique hwt .const)
        (by simp [LConst.ty, LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | abs _ _ _ _ =>
      exact absurd (LExpr.HasTypeA_to_typeCheck hwt)
        (by simp [LExpr.typeCheck, bind, Option.bind]
            split <;> simp_all [LMonoTy.arrow, LMonoTy.bool, LMonoTy.int])
    | ite hc ht he_ =>
      cases hwt with
      | ite hcw htw hew =>
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; left
        refine ⟨_, genLExprBase_complete fctx octx tvars bctx n .bool SimpleType.bool _ hcw hnames.1 hvars.1 hc (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n .bool SimpleType.bool _ htw hnames.2.1 hvars.2.1 ht (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n .bool SimpleType.bool _ hew hnames.2.2 hvars.2.2 he_ (by omega), rfl⟩
    | eq τ' he1w he2w hsτ' hdτ' hftv' hats1 hats2 =>
      cases hwt with
      | eq hwt1 hwt2 =>
        have hτeq := HasTypeA_unique he1w hwt1
        subst hτeq
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; right; left
        refine ⟨τ', (genLMonoTy_support tvars n τ').mpr ⟨hsτ', hdτ', hftv'⟩,
               _, genLExprBase_complete fctx octx tvars bctx n τ' hsτ' _ hwt1 hnames.1 hvars.1 hats1 (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n τ' hsτ' _ hwt2 hnames.2 hvars.2 hats2 (by omega), rfl⟩
    | app τ' hargw hsτ' hdτ' hftv' hfn_ats harg_ats =>
      cases hwt with
      | app hfnw hargw' =>
        have hτeq := HasTypeA_unique hargw hargw'
        subst hτeq
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; right; right; left
        refine ⟨τ', (genLMonoTy_support tvars n τ').mpr ⟨hsτ', hdτ', hftv'⟩,
               _, genLExprBase_complete fctx octx tvars bctx n τ' hsτ' _ hargw' hnames.2 hvars.2 harg_ats (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n (.arrow τ' .bool) (SimpleType.arrow hsτ' SimpleType.bool) _ hfnw hnames.1 hvars.1 hfn_ats (by omega), rfl⟩
    | quant hsτ' hdτ' hftv' τ_tr hsτ_tr hdτ_tr hftv_tr htrw htr_ats hbody_ats =>
      cases hwt with
      | quant htrw' hbodyw =>
        have hτ_tr_eq := HasTypeA_unique htrw htrw'
        subst hτ_tr_eq
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        rename_i k
        cases k with
        | all =>
          right; right; right; right; left
          refine ⟨_, (genLMonoTy_support tvars n _).mpr ⟨hsτ', hdτ', hftv'⟩,
                 _, (genLMonoTy_support tvars n _).mpr ⟨hsτ_tr, hdτ_tr, hftv_tr⟩,
                 _, genLExprBase_complete fctx octx tvars (_ :: bctx) n τ_tr hsτ_tr _ htrw' hnames.2.1 hvars.1 htr_ats (by omega),
                 _, genLExprBase_complete fctx octx tvars (_ :: bctx) n .bool SimpleType.bool _ hbodyw hnames.2.2 hvars.2 hbody_ats (by omega), rfl⟩
        | exist =>
          right; right; right; right; right; left
          refine ⟨_, (genLMonoTy_support tvars n _).mpr ⟨hsτ', hdτ', hftv'⟩,
                 _, (genLMonoTy_support tvars n _).mpr ⟨hsτ_tr, hdτ_tr, hftv_tr⟩,
                 _, genLExprBase_complete fctx octx tvars (_ :: bctx) n τ_tr hsτ_tr _ htrw' hnames.2.1 hvars.1 htr_ats (by omega),
                 _, genLExprBase_complete fctx octx tvars (_ :: bctx) n .bool SimpleType.bool _ hbodyw hnames.2.2 hvars.2 hbody_ats (by omega), rfl⟩
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; right; right; right; right; right; left; left
        have hlen : (bvarsOfType bctx .bool).length > 0 := by
          have := (bvarsOfType_mem_iff bctx .bool _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx .bool _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; right; right; right; right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx .bool).length > 0 := by
          have := (fvarsOfType_mem_iff fctx .bool _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx .bool _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; right; right; right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx .bool).length > 0 := by
          have := (opsOfType_mem_iff octx .bool _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx .bool _ hmem hlen⟩
  | n + 1, _, SimpleType.int =>
    rw [norm_int]
    simp only [genLExprBase, pickBiased_mem_iff, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | intConst =>
      cases hwt with
      | const =>
        left
        have hic := Int_cover (by assumption : Int)
        rcases hic with ⟨k, hk, rfl⟩ | ⟨k, hk, rfl⟩
        · left; exact ⟨k, hk, rfl⟩
        · right; exact ⟨k, hk, rfl⟩
    | boolConst =>
      exact absurd (HasTypeA_unique hwt .const)
        (by simp [LConst.ty, LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | abs _ _ _ _ =>
      exact absurd (LExpr.HasTypeA_to_typeCheck hwt)
        (by simp [LExpr.typeCheck, bind, Option.bind]
            split <;> simp_all [LMonoTy.arrow, LMonoTy.bool, LMonoTy.int])
    | eq _ _ _ _ _ _ _ _ =>
      exact absurd (eq_hasType_bool hwt)
        (by simp [LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | quant _ _ _ _ _ _ _ _ _ _ =>
      exact absurd (quant_hasType_bool hwt)
        (by simp [LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | app τ' hargw hsτ' hdτ' hftv' hfn_ats harg_ats =>
      cases hwt with
      | app hfnw hargw' =>
        have hτeq := HasTypeA_unique hargw hargw'
        subst hτeq
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; left
        refine ⟨τ', (genLMonoTy_support tvars n τ').mpr ⟨hsτ', hdτ', hftv'⟩,
               _, genLExprBase_complete fctx octx tvars bctx n τ' hsτ' _ hargw' hnames.2 hvars.2 harg_ats (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n (.arrow τ' .int) (SimpleType.arrow hsτ' SimpleType.int) _ hfnw hnames.1 hvars.1 hfn_ats (by omega), rfl⟩
    | ite hc ht he_ =>
      cases hwt with
      | ite hcw htw hew =>
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; right; left
        refine ⟨_, genLExprBase_complete fctx octx tvars bctx n .bool SimpleType.bool _ hcw hnames.1 hvars.1 hc (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n .int SimpleType.int _ htw hnames.2.1 hvars.2.1 ht (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n .int SimpleType.int _ hew hnames.2.2 hvars.2.2 he_ (by omega), rfl⟩
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; right; right; left; left
        have hlen : (bvarsOfType bctx .int).length > 0 := by
          have := (bvarsOfType_mem_iff bctx .int _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx .int _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx .int).length > 0 := by
          have := (fvarsOfType_mem_iff fctx .int _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx .int _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx .int).length > 0 := by
          have := (opsOfType_mem_iff octx .int _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx .int _ hmem hlen⟩
  | n + 1, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow]
    simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | boolConst =>
      exact absurd (HasTypeA_unique hwt .const)
        (by simp [LConst.ty, LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | intConst =>
      exact absurd (HasTypeA_unique hwt .const)
        (by simp [LConst.ty, LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | eq _ _ _ _ _ _ _ _ =>
      exact absurd (eq_hasType_bool hwt)
        (by simp [LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | quant _ _ _ _ _ _ _ _ _ _ =>
      exact absurd (quant_hasType_bool hwt)
        (by simp [LMonoTy.bool, LMonoTy.int, LMonoTy.arrow])
    | abs hsτ₁ hdτ₁ _ hbody_ats =>
      cases hwt with
      | abs hbody_wt =>
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        left
        refine ⟨_, genLExprBase_complete fctx octx tvars (τ₁ :: bctx) n τ₂ hs₂ _ hbody_wt
          hnames.2 hvars hbody_ats (by omega), rfl⟩
    | app τ' hargw hsτ' hdτ' hftv' hfn_ats harg_ats =>
      cases hwt with
      | app hfnw hargw' =>
        have hτeq := HasTypeA_unique hargw hargw'
        subst hτeq
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; left
        refine ⟨τ', (genLMonoTy_support tvars n τ').mpr ⟨hsτ', hdτ', hftv'⟩,
               _, genLExprBase_complete fctx octx tvars bctx n τ' hsτ' _ hargw' hnames.2 hvars.2 harg_ats (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n (.arrow τ' (.arrow τ₁ τ₂)) (SimpleType.arrow hsτ' (SimpleType.arrow hs₁ hs₂)) _ hfnw hnames.1 hvars.1 hfn_ats (by omega), rfl⟩
    | ite hc ht he_ =>
      cases hwt with
      | ite hcw htw hew =>
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; right; left
        refine ⟨_, genLExprBase_complete fctx octx tvars bctx n .bool SimpleType.bool _ hcw hnames.1 hvars.1 hc (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n (.arrow τ₁ τ₂) (SimpleType.arrow hs₁ hs₂) _ htw hnames.2.1 hvars.2.1 ht (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n (.arrow τ₁ τ₂) (SimpleType.arrow hs₁ hs₂) _ hew hnames.2.2 hvars.2.2 he_ (by omega), rfl⟩
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; right; right; left; left
        have hlen : (bvarsOfType bctx (.arrow τ₁ τ₂)).length > 0 := by
          have := (bvarsOfType_mem_iff bctx (.arrow τ₁ τ₂) _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx (.arrow τ₁ τ₂) _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx (.arrow τ₁ τ₂)).length > 0 := by
          have := (fvarsOfType_mem_iff fctx (.arrow τ₁ τ₂) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx (.arrow τ₁ τ₂) _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx (.arrow τ₁ τ₂)).length > 0 := by
          have := (opsOfType_mem_iff octx (.arrow τ₁ τ₂) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx (.arrow τ₁ τ₂) _ hmem hlen⟩
  | 0, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExprBase, pick_mem_iff, mem_support_iff, SetGen.mem_dite, bot_mem_iff]
    cases hats with
    | boolConst =>
      exact absurd (HasTypeA_unique hwt .const) (by intro h; simp [LConst.ty, LMonoTy.bool] at h)
    | intConst =>
      exact absurd (HasTypeA_unique hwt .const) (by intro h; simp [LConst.ty, LMonoTy.int] at h)
    | bvar =>
      cases hwt with
      | bvar hget =>
        left; left
        have hlen : (bvarsOfType bctx (.ftvar name)).length > 0 := by
          have := (bvarsOfType_mem_iff bctx (.ftvar name) _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx (.ftvar name) _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx (.ftvar name)).length > 0 := by
          have := (fvarsOfType_mem_iff fctx (.ftvar name) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx (.ftvar name) _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx (.ftvar name)).length > 0 := by
          have := (opsOfType_mem_iff octx (.ftvar name) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx (.ftvar name) _ hmem hlen⟩
  | n + 1, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExprBase, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite, bot_mem_iff]
    cases hats with
    | boolConst =>
      exact absurd (HasTypeA_unique hwt .const) (by intro h; simp [LConst.ty, LMonoTy.bool] at h)
    | intConst =>
      exact absurd (HasTypeA_unique hwt .const) (by intro h; simp [LConst.ty, LMonoTy.int] at h)
    | abs _ _ _ _ =>
      exact absurd (LExpr.HasTypeA_to_typeCheck hwt)
        (by simp [LExpr.typeCheck, bind, Option.bind]
            split <;> simp_all [LMonoTy.arrow, LMonoTy.bool, LMonoTy.int])
    | eq _ _ _ _ _ _ _ _ =>
      exact absurd (eq_hasType_bool hwt) (by intro h; simp [LMonoTy.bool] at h)
    | quant _ _ _ _ _ _ _ _ _ _ =>
      exact absurd (quant_hasType_bool hwt) (by intro h; simp [LMonoTy.bool] at h)
    | app τ' hargw hsτ' hdτ' hftv' hfn_ats harg_ats =>
      cases hwt with
      | app hfnw hargw' =>
        have hτeq := HasTypeA_unique hargw hargw'
        subst hτeq
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        left
        refine ⟨τ', (genLMonoTy_support tvars n τ').mpr ⟨hsτ', hdτ', hftv'⟩,
               _, genLExprBase_complete fctx octx tvars bctx n τ' hsτ' _ hargw' hnames.2 hvars.2 harg_ats (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n (.arrow τ' (.ftvar name)) (SimpleType.arrow hsτ' SimpleType.ftvar) _ hfnw hnames.1 hvars.1 hfn_ats (by omega), rfl⟩
    | ite hc ht he_ =>
      cases hwt with
      | ite hcw htw hew =>
        simp [termDepth] at hdepth
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; left
        refine ⟨_, genLExprBase_complete fctx octx tvars bctx n .bool SimpleType.bool _ hcw hnames.1 hvars.1 hc (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n (.ftvar name) SimpleType.ftvar _ htw hnames.2.1 hvars.2.1 ht (by omega),
               _, genLExprBase_complete fctx octx tvars bctx n (.ftvar name) SimpleType.ftvar _ hew hnames.2.2 hvars.2.2 he_ (by omega), rfl⟩
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; right; left; left
        have hlen : (bvarsOfType bctx (.ftvar name)).length > 0 := by
          have := (bvarsOfType_mem_iff bctx (.ftvar name) _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx (.ftvar name) _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx (.ftvar name)).length > 0 := by
          have := (fvarsOfType_mem_iff fctx (.ftvar name) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx (.ftvar name) _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx (.ftvar name)).length > 0 := by
          have := (opsOfType_mem_iff octx (.ftvar name) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx (.ftvar name) _ hmem hlen⟩
  termination_by (depth, sizeOf τ)
  decreasing_by all_goals simp_wf; omega

-- ── IsSoundAndComplete for genLMonoTy ─────────────────────────────────

/-- `genLMonoTy tvars n` is sound and complete with respect to
    `fun τ => SimpleType τ ∧ monoTyDepth τ ≤ n ∧ allFtvarsIn tvars τ`. -/
instance {tvars : List TyIdentifier} {n : Nat} :
    SetGen.IsSoundAndComplete
      (genLMonoTy (G := SetGen.Set) tvars n)
      (fun τ => SimpleType τ ∧ monoTyDepth τ ≤ n ∧ allFtvarsIn tvars τ) where
  support_iff τ := genLMonoTy_support tvars n τ

-- ── Quick test ────────────────────────────────────────────────────────

-- We need this `ToFormat` instance in order to pretty-print the generated `LExpr`s
-- before (since our metadata type is `Unit`)
open Std in
instance : ToFormat Unit where
  format _ := .nil

-- Print 5 randomly generated expressions
-- Some example generated exprs:
-- (if (if #true then #true else #true) then #true else #true)
-- ((λ (bvar:bool) #true) ((λ (bvar:bool) %0) #true))
#guard_msgs(drop warning, drop all) in
#eval (for _ in [:5] do
  IO.println <| Std.format (← genClosedLExpr [] 3) |>.pretty : IO Unit)

-- Test with a bound variable of type `ftvar "a"` to exercise the ftvar case
#guard_msgs(drop warning, drop all) in
#eval (for _ in [:5] do
  IO.println <| Std.format (← genLExpr [] [] [] ["a"] [.ftvar "a"] 3 (.ftvar "a")) |>.pretty : IO Unit)

-- Test with polymorphic operators (IndirPoly rule)
-- id : ∀ a. a → a
-- const : ∀ a b. a → b → a
#guard_msgs(drop warning, drop all) in
#eval (for _ in [:5] do
  let pctx : PolyOpCtx := [
    ("id", .forAll ["a"] (.arrow (.ftvar "a") (.ftvar "a"))),
    ("const", .forAll ["a", "b"] (.arrow (.ftvar "a") (.arrow (.ftvar "b") (.ftvar "a"))))
  ]
  IO.println <| Std.format (← genLExpr [] [] pctx [] [] 3 .bool) |>.pretty : IO Unit)

-- ── Indir rule soundness ─────────────────────────────────────────────

/-- Inversion lemma for `SimpleType` at an arrow type. -/
private theorem SimpleType_arrow_inv {τ₁ τ₂ : LMonoTy}
    (h : SimpleType (.arrow τ₁ τ₂)) : SimpleType τ₁ ∧ SimpleType τ₂ :=
  h.casesOn (motive := fun ty _ => ty = .arrow τ₁ τ₂ → SimpleType τ₁ ∧ SimpleType τ₂)
    (fun heq => by simp [LMonoTy.bool, LMonoTy.arrow] at heq)
    (fun heq => by simp [LMonoTy.int, LMonoTy.arrow] at heq)
    (fun h₁ h₂ heq => by simp [LMonoTy.arrow] at heq; exact heq.1 ▸ heq.2 ▸ ⟨h₁, h₂⟩)
    (fun heq => by simp [LMonoTy.arrow] at heq)
    rfl

/-- If `argsForResult fullTy τ = some args`, then
    `fullTy = args.foldr (fun σ acc => .arrow σ acc) τ`. -/
theorem argsForResult_eq (fullTy τ : LMonoTy) (args : List LMonoTy)
    (h : argsForResult fullTy τ = some args) :
    fullTy = args.foldr (fun σ acc => LMonoTy.arrow σ acc) τ := by
  unfold argsForResult at h
  split at h
  · rename_i σ rest
    split at h
    · rename_i args' hrest
      simp at h; subst h
      simp only [List.foldr]
      show LMonoTy.arrow σ rest = LMonoTy.arrow σ (List.foldr _ τ args')
      congr 1
      exact argsForResult_eq rest τ args' hrest
    · simp at h
  · split at h
    · rename_i heq
      have heq' := beq_iff_eq.mp heq
      simp at h; subst h; simp [heq']
    · simp at h
  termination_by sizeOf fullTy

/-- If `σ₁ → σ₂ → ... → σₙ → τ` is a `SimpleType`, then each `σᵢ` is too. -/
private theorem simpleType_of_foldr_mem (args : List LMonoTy) (τ : LMonoTy)
    (h : SimpleType (args.foldr (fun σ acc => LMonoTy.arrow σ acc) τ))
    (σ : LMonoTy) (hσ : σ ∈ args) : SimpleType σ := by
  induction args with
  | nil => simp at hσ
  | cons a rest ih =>
    simp only [List.foldr] at h
    have ⟨h₁, h₂⟩ := SimpleType_arrow_inv h
    rcases List.mem_cons.mp hσ with rfl | hmem
    · exact h₁
    · exact ih h₂ hmem

/-- Helper: `mkApps` preserves typing via iterated `app` rule. -/
theorem mkApps_hasType (bctx : BVarCtx) (base : LExpr') (args : List LExpr')
    (argTys : List LMonoTy) (τ : LMonoTy)
    (hbase : HasTypeA' bctx base (argTys.foldr (fun σ acc => LMonoTy.arrow σ acc) τ))
    (hargs : List.Forall₂ (HasTypeA' bctx) args argTys) :
    HasTypeA' bctx (mkApps base args) τ := by
  induction hargs generalizing base with
  | nil => exact hbase
  | cons harg _ ih => exact ih _ (LExpr.HasTypeA.app hbase harg)

/-- Membership in `List.mapM f l` on `SetGen.Set`: `args` is in the support
    iff each element is pointwise in the support of `f` at the corresponding input. -/
private theorem mem_mapM_iff (f : LMonoTy → SetGen.Set LExpr')
    (argTys : List LMonoTy) (args : List LExpr') :
    args ∈ (List.mapM (m := SetGen.Set) f argTys) ↔
    List.Forall₂ (fun arg σ => arg ∈ f σ) args argTys := by
  induction argTys generalizing args with
  | nil =>
    simp only [List.mapM_nil, SetGen.Set.mem_pure]
    constructor
    · rintro rfl; exact .nil
    · intro h; cases h; rfl
  | cons σ rest ih =>
    simp only [List.mapM_cons, SetGen.Set.mem_bind, SetGen.Set.mem_pure]
    constructor
    · rintro ⟨x, hx, tl, htl, rfl⟩
      exact .cons hx ((ih _).mp htl)
    · intro h
      match args, h with
      | _ :: _, .cons harg htail =>
        exact ⟨_, harg, _, (ih _).mpr htail, rfl⟩

/-- If `(name, argTys) ∈ findOpsInCtx octx τ`, then `(name, argTys.foldr arrow τ) ∈ octx`
    and `argTys` is non-empty. -/
private theorem findOpsInCtx_mem {octx : OpCtx} {τ : LMonoTy}
    {name : String} {argTys : List LMonoTy}
    (h : (name, argTys) ∈ findOpsInCtx octx τ) :
    (name, argTys.foldr (fun σ acc => LMonoTy.arrow σ acc) τ) ∈ octx ∧ argTys ≠ [] := by
  simp only [findOpsInCtx, List.mem_filterMap] at h
  obtain ⟨⟨n, ty⟩, hmem, hfilt⟩ := h
  simp only at hfilt
  split at hfilt
  · rename_i arg args hargs
    simp only [Option.some.injEq, Prod.mk.injEq] at hfilt
    obtain ⟨rfl, rfl⟩ := hfilt
    refine ⟨?_, List.cons_ne_nil _ _⟩
    have heq := argsForResult_eq ty τ (arg :: args) hargs
    rw [heq] at hmem
    exact hmem
  · simp at hfilt

/-- Soundness of `genIndirPoly`: every generated expression is well-typed.

    The proof exploits the key structural invariant: `genIndirPoly` always
    produces either a `genLExprBase` fallback (when no candidates match) or
    `mkApps (.op () ⟨name, ()⟩ (some fullArrowTy)) args` where
    `fullArrowTy = concreteArgTys.foldr arrow τ`.

    For the latter case:
    - `HasTypeA.op` gives the op node type `fullArrowTy` (reads the annotation).
    - Each argument is generated by `genLExprBase` at a concrete type `σᵢ`.
      By `genLExprBase_sound`, the argument has type `σᵢ` (given `SimpleType σᵢ`).
    - `mkApps_hasType` folds the applications to obtain result type `τ`.

    The `hSimpleGenerable` precondition ensures the types in `generableTypesFromCtx`
    are `SimpleType`s, which guarantees the concrete argument types (produced by
    substituting generable types into the polymorphic operator's type scheme) are
    also `SimpleType`s. This holds whenever bctx/fctx/octx only contain simple types. -/
theorem genIndirPoly_sound (fctx : FVarCtx) (octx : OpCtx)
    (pctx : PolyOpCtx) (tvars : List TyIdentifier)
    (bctx : BVarCtx) (depth : Nat) (τ : LMonoTy)
    (hτ : SimpleType τ)
    (hSimpleOps : ∀ p ∈ octx, SimpleType p.2)
    (hSimpleGenerable : ∀ σ ∈ generableTypesFromCtx bctx fctx octx, SimpleType σ)
    (e : LExpr')
    (he : e ∈ SetGen.support (genIndirPoly (G := SetGen.Set) fctx octx pctx tvars bctx depth τ)) :
    HasTypeA' bctx e τ := by
  -- Unfold genIndirPoly: mapM (sample types) >> dite (choose >> mapM >> pure | base)
  unfold genIndirPoly at he
  simp only [mem_support_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
             SetGen.mem_dite] at he
  -- Peel the outer mapM (type sampling)
  obtain ⟨sampledTys, _, he⟩ := he
  -- Split on whether polyOpsForResult found candidates
  rcases he with ⟨hpos, he⟩ | ⟨_, he⟩
  · -- Candidates found: choose one, generate args, assemble via mkApps.
    -- After destructuring the monadic binds, the expression is:
    --   mkApps (.op () ⟨name, ()⟩ (some fullArrowTy)) args
    -- where fullArrowTy = concreteArgTys.foldr (fun σ acc => .arrow σ acc) τ.
    --
    -- The typing derivation is:
    -- (1) HasTypeA.op : HasTypeA' bctx (.op _ _ (some ty)) ty
    --     — the op is typed at its annotation regardless of name/args
    -- (2) ∀ i, genLExprBase_sound gives HasTypeA' bctx args[i] concreteArgTys[i]
    --     — each argument is generated at its declared concrete type
    -- (3) mkApps_hasType assembles (1) and (2) into HasTypeA' bctx e τ
    --
    -- The only non-trivial obligation is showing SimpleType concreteArgTys[i]
    -- (required by genLExprBase_sound). This follows from hSimpleGenerable:
    -- the sampled types are drawn from generableTypesFromCtx (all SimpleType),
    -- and applySimpleSubst preserves SimpleType when the substitution maps
    -- type variables to SimpleTypes.
    sorry
  · -- No candidates: fell back to genLExprBase
    exact genLExprBase_sound fctx octx tvars bctx depth τ hτ e he

/-- Soundness of `genLExpr`: every generated expression is well-typed.
    This combines the soundness of the Indir and IndirPoly rules with
    `genLExprBase_sound`. -/
theorem genLExpr_sound (fctx : FVarCtx) (octx : OpCtx) (pctx : PolyOpCtx)
    (tvars : List TyIdentifier) (bctx : BVarCtx) (depth : Nat)
    (τ : LMonoTy) (hτ : SimpleType τ)
    (hSimpleOps : ∀ p ∈ octx, SimpleType p.2)
    (e : LExpr')
    (he : e ∈ SetGen.support (genLExpr (G := SetGen.Set) fctx octx pctx tvars bctx depth τ)) :
    HasTypeA' bctx e τ := by
  unfold genLExpr at he
  simp only [mem_support_iff, SetGen.mem_dite, pickBiased_mem_iff, pick_mem_iff] at he
  rcases he with ⟨hpos, he | (he | he)⟩ | ⟨_, he | he⟩
  · -- genLExprBase path (first branch of pickBiased)
    exact genLExprBase_sound fctx octx tvars bctx depth τ hτ e he
  · -- Monomorphic Indir path: fully-applied operator
    simp only [SetGen.Set.mem_bind, SetGen.Set.mem_pure] at he
    obtain ⟨idx, ⟨_, hidx_hi⟩, args, hargs, rfl⟩ := he
    set ops := findOpsInCtx octx τ
    have hlt : idx.down < ops.length := by omega
    set entry := ops.getD idx.down ("", [])
    have hentry_eq : entry = ops[idx.down] := by
      simp [entry, List.getElem?_eq_getElem hlt]
    have hentry_mem : entry ∈ ops := hentry_eq ▸ List.getElem_mem hlt
    set name := entry.1
    set argTys := entry.2
    set fullTy := argTys.foldr (fun σ acc => LMonoTy.arrow σ acc) τ
    set base : LExpr' := .op () ⟨name, ()⟩ (some fullTy)
    have ⟨hoctx_mem, _⟩ := findOpsInCtx_mem hentry_mem
    have hbase : HasTypeA' bctx base (argTys.foldr (fun σ acc => LMonoTy.arrow σ acc) τ) := .op
    have hforall₂ := (mem_mapM_iff
      (genLExprBase fctx octx tvars bctx depth) argTys args).mp hargs
    have hfull : SimpleType fullTy := hSimpleOps _ hoctx_mem
    have hargs_typed : List.Forall₂ (HasTypeA' bctx) args argTys := by
      suffices h : ∀ (tys : List LMonoTy) (es : List LExpr'),
          (∀ σ ∈ tys, SimpleType σ) →
          List.Forall₂ (fun arg σ => arg ∈ (genLExprBase (G := SetGen.Set) fctx octx tvars bctx depth σ)) es tys →
          List.Forall₂ (HasTypeA' bctx) es tys from
        h argTys args (simpleType_of_foldr_mem argTys τ hfull) hforall₂
      intro tys es hsimple hf₂
      induction hf₂ with
      | nil => exact .nil
      | @cons e ty _ _ hmem _ ih =>
        exact .cons
          (genLExprBase_sound fctx octx tvars bctx depth ty
            (hsimple ty List.mem_cons_self) e hmem)
          (ih (fun σ' hσ' => hsimple σ' (List.mem_cons_of_mem _ hσ')))
    exact mkApps_hasType bctx base args argTys τ hbase hargs_typed
  · -- IndirPoly path (polymorphic operators)
    exact genIndirPoly_sound fctx octx pctx tvars bctx depth τ hτ hSimpleOps
      (fun σ _ => by sorry) e he
  · -- No monomorphic Indir candidates: genLExprBase fallback
    exact genLExprBase_sound fctx octx tvars bctx depth τ hτ e he
  · -- No monomorphic Indir candidates: IndirPoly fallback
    exact genIndirPoly_sound fctx octx pctx tvars bctx depth τ hτ hSimpleOps
      (fun σ _ => by sorry) e he
