import StrataGenerators.SetGen
import Basalt.Examples.ArbNat
import Strata.DL.Lambda.Denote.LExprAnnotated

open Lambda RandomChoice ArbNat SetGen

/-!
# Generator of well-typed terms satisfying `HasTypeA`

A Basalt `SetGen`-based random generator for well-typed Strata `LExpr`s
that satisfy the `HasTypeA` relation.
We work with the `LExprParams` instantiation `LExprParams.mono ⟨Unit, Unit⟩` (unit
metadata and identifier-metadata, monotype annotations).

## Contents

- `HasTypeA'` — the typing judgement `HasTypeA`, with `LExprParams` instantiated
- `SimpleType` — types generated by `genLMonoTy`
- `genLMonoTy` — generates simple mono-types (bool, int, arrow)
- `genLExpr` — generates well-typed `LExpr`s for a given type and depth
- Soundness of `genLExpr` (every generated expression is well-typed)
- `SetGen.IsSoundAndComplete` instance for `genLMonoTy`
-/

-- ── Parameter type ─────────────────────────────────────────────────────

/-- The base `LExprParams` we use: unit metadata & IDMeta. -/
abbrev LExprParams' : LExprParams := ⟨Unit, Unit⟩

/-- The `LExprParamsT` instantiation we use: unit metadata & IDMeta,
    `LMonoTy` as the type-annotation type. -/
abbrev LExprParamsT' : LExprParamsT := LExprParams.mono LExprParams'

instance : DecidableEq Unit := instDecidableEqPUnit

/-- Our working expression type (`LExpr` with `LExprParamsT` instantiated) -/
abbrev LExpr' := LExpr LExprParamsT'

instance : BEq LMonoTy := instBEqOfDecidableEq

-- ── Bound-variable context ─────────────────────────────────────────────

/-- De Bruijn context: `bctx[i]?` is the type of `bvar i`. -/
abbrev BVarCtx := List LMonoTy

-- ── Free-variable and operator contexts ────────────────────────────────

/-- Free-variable context: maps variable names to their types. -/
abbrev FVarCtx := List (String × LMonoTy)

/-- Operator context: maps operator names to their types. -/
abbrev OpCtx := List (String × LMonoTy)

-- ── Simple types ───────────────────────────────────────────────────────

/-- A type is *simple* if it is built from `bool`, `int`, `arrow`, and `ftvar`. -/
inductive SimpleType : LMonoTy → Prop where
  | bool  : SimpleType .bool
  | int   : SimpleType .int
  | arrow : SimpleType τ₁ → SimpleType τ₂ → SimpleType (.arrow τ₁ τ₂)
  | ftvar : SimpleType (.ftvar name)

/-- Depth of a simple type. -/
def monoTyDepth : LMonoTy → Nat
  | .arrow τ₁ τ₂ => max (monoTyDepth τ₁) (monoTyDepth τ₂) + 1
  | _             => 0

-- ── Well-typing relation ───────────────────────────────────────────────

/-- We use Strata's `LExpr.HasTypeA` directly as our typing judgement.
    `HasTypeA Δ e τ` means expression `e` has type `τ` under bound-variable
    context `Δ` (a `List LMonoTy` indexed by de Bruijn level). -/
abbrev HasTypeA' := LExpr.HasTypeA (T := LExprParams')

-- ── Bound-variable helpers ─────────────────────────────────────────────

/-- All de Bruijn indices in `bctx` whose type equals `τ`. -/
def bvarsOfType (bctx : BVarCtx) (τ : LMonoTy) : List Nat :=
  go bctx 0
where
  go : List LMonoTy → Nat → List Nat
    | [],         _  => []
    | τ' :: rest, i  => if τ' == τ then i :: go rest (i + 1) else go rest (i + 1)

/-- Pick a random `bvar` of type `τ` from `bctx`, given at least one exists. -/
def pickBVar [Gen G] (bctx : BVarCtx) (τ : LMonoTy)
    (_h : (bvarsOfType bctx τ).length > 0) : G LExpr' := do
  let indices := bvarsOfType bctx τ
  let idx ← choose 0 (indices.length - 1) (by omega)
  pure (.bvar () (indices.getD idx.down 0))

-- ── Free-variable helpers ──────────────────────────────────────────────

/-- All variable names in `fctx` whose type equals `τ`. -/
def fvarsOfType (fctx : FVarCtx) (τ : LMonoTy) : List String :=
  fctx.filterMap (fun (x, ty) => if ty == τ then some x else none)

/-- Pick a random `fvar` of type `τ` from `fctx`, given at least one exists with that type. -/
def pickFVar [Gen G] (fctx : FVarCtx) (τ : LMonoTy)
    (_h : (fvarsOfType fctx τ).length > 0) : G LExpr' := do
  let names := fvarsOfType fctx τ
  let idx ← choose 0 (names.length - 1) (by omega)
  pure (.fvar () ⟨names.getD idx.down "", ()⟩ (some τ))

-- ── Operator helpers ───────────────────────────────────────────────────

/-- All operator names in `octx` whose type equals `τ`. -/
def opsOfType (octx : OpCtx) (τ : LMonoTy) : List String :=
  octx.filterMap (fun (x, ty) => if ty == τ then some x else none)

/-- Pick a random `op` of type `τ` from `octx`, given at least one exists with that type. -/
def pickOp [Gen G] (octx : OpCtx) (τ : LMonoTy)
    (_h : (opsOfType octx τ).length > 0) : G LExpr' := do
  let names := opsOfType octx τ
  let idx ← choose 0 (names.length - 1) (by omega)
  pure (.op () ⟨names.getD idx.down "", ()⟩ (some τ))

-- ── Type generator ─────────────────────────────────────────────────────

/-- Pick a random type variable name from the palette. -/
def pickTyVar [Gen G] (tvars : List TyIdentifier)
    (_h : tvars.length > 0) : G LMonoTy := do
  let idx ← choose 0 (tvars.length - 1) (by omega)
  pure (.ftvar (tvars.getD idx.down ""))

/-- Generate a simple type of depth ≤ `n`. The `tvars` palette controls which
    free type variable names may appear; when empty, only `bool`/`int`/`arrow`
    are generated. -/
def genLMonoTy [Gen G] (tvars : List TyIdentifier) : Nat → G LMonoTy
  | 0 =>
    pick (fun () => pure .bool)
         (fun () =>
           pick (fun () => pure .int)
                (fun () =>
                  if h : tvars.length > 0 then pickTyVar tvars h
                  else pure .bool))
  | n + 1 =>
    pick
      (fun () => pure .bool)
      (fun () =>
        pick
          (fun () => pure .int)
          (fun () =>
            pick
              (fun () => do
                let τ₁ ← genLMonoTy tvars n
                let τ₂ ← genLMonoTy tvars n
                pure (.arrow τ₁ τ₂))
              (fun () =>
                if h : tvars.length > 0 then pickTyVar tvars h
                else pure .int)))

-- ── Expression generator ───────────────────────────────────────────────

/-- Generate a well-typed `LExpr` of type `τ` at depth ≤ `size` under
    bound-variable context `bctx`, free-variable context `fctx`, and
    operator context `octx`. The `tvars` palette lists type variable names
    that `genLMonoTy` may produce as intermediate types.

    No `resolve`/`resolve_aux` calls are made.
    Names are always `""`. -/
def genLExpr [Gen G] (fctx : FVarCtx) (octx : OpCtx) (tvars : List TyIdentifier) (bctx : BVarCtx) : Nat → LMonoTy → G LExpr'
  -- ── Arrow type ────────────────────────────────────────────────────
  | 0, .arrow τ₁ τ₂ =>
    let bvars := bvarsOfType bctx (.arrow τ₁ τ₂)
    pick
      (fun () =>
        if hv : bvars.length > 0 then pickBVar bctx _ hv
        else do
          let body ← genLExpr fctx octx tvars (τ₁ :: bctx) 0 τ₂
          pure (.abs () "" (some τ₁) body))
      (fun () =>
        pick
          (fun () =>
            if hf : (fvarsOfType fctx (.arrow τ₁ τ₂)).length > 0
            then pickFVar fctx _ hf
            else do
              let body ← genLExpr fctx octx tvars (τ₁ :: bctx) 0 τ₂
              pure (.abs () "" (some τ₁) body))
          (fun () =>
            if ho : (opsOfType octx (.arrow τ₁ τ₂)).length > 0
            then pickOp octx _ ho
            else do
              let body ← genLExpr fctx octx tvars (τ₁ :: bctx) 0 τ₂
              pure (.abs () "" (some τ₁) body)))
  | n + 1, .arrow τ₁ τ₂ =>
    let bvars := bvarsOfType bctx (.arrow τ₁ τ₂)
    pick
      (fun () => do
        let body ← genLExpr fctx octx tvars (τ₁ :: bctx) n τ₂
        pure (.abs () "" (some τ₁) body))
      (fun () =>
        pick
          (fun () => do
            let τ' ← genLMonoTy tvars n
            let arg ← genLExpr fctx octx tvars bctx n τ'
            let fn  ← genLExpr fctx octx tvars bctx n (.arrow τ' (.arrow τ₁ τ₂))
            pure (.app () fn arg))
          (fun () =>
            pick
              (fun () => do
                let c ← genLExpr fctx octx tvars bctx n .bool
                let t ← genLExpr fctx octx tvars bctx n (.arrow τ₁ τ₂)
                let e ← genLExpr fctx octx tvars bctx n (.arrow τ₁ τ₂)
                pure (.ite () c t e))
              (fun () =>
                pick
                  (fun () =>
                    if hv : bvars.length > 0 then pickBVar bctx _ hv
                    else do
                      let body ← genLExpr fctx octx tvars (τ₁ :: bctx) n τ₂
                      pure (.abs () "" (some τ₁) body))
                  (fun () =>
                    pick
                      (fun () =>
                        if hf : (fvarsOfType fctx (.arrow τ₁ τ₂)).length > 0
                        then pickFVar fctx _ hf
                        else do
                          let body ← genLExpr fctx octx tvars (τ₁ :: bctx) n τ₂
                          pure (.abs () "" (some τ₁) body))
                      (fun () =>
                        if ho : (opsOfType octx (.arrow τ₁ τ₂)).length > 0
                        then pickOp octx _ ho
                        else do
                          let body ← genLExpr fctx octx tvars (τ₁ :: bctx) n τ₂
                          pure (.abs () "" (some τ₁) body))))))
  -- ── Bool type ─────────────────────────────────────────────────────
  | 0, .bool =>
    let bvars := bvarsOfType bctx .bool
    pick
      (fun () =>
        pick (fun () => pure (.boolConst () true))
             (fun () => pure (.boolConst () false)))
      (fun () =>
        pick
          (fun () =>
            if hv : bvars.length > 0 then pickBVar bctx .bool hv
            else pick (fun () => pure (.boolConst () true))
                      (fun () => pure (.boolConst () false)))
          (fun () =>
            pick
              (fun () =>
                if hf : (fvarsOfType fctx .bool).length > 0
                then pickFVar fctx .bool hf
                else pick (fun () => pure (.boolConst () true))
                          (fun () => pure (.boolConst () false)))
              (fun () =>
                if ho : (opsOfType octx .bool).length > 0
                then pickOp octx .bool ho
                else pick (fun () => pure (.boolConst () true))
                          (fun () => pure (.boolConst () false)))))
  | n + 1, .bool =>
    let bvars := bvarsOfType bctx .bool
    pick
      (fun () =>
        pick (fun () => pure (.boolConst () true))
             (fun () => pure (.boolConst () false)))
      (fun () =>
        pick
          (fun () => do
            let c ← genLExpr fctx octx tvars bctx n .bool
            let t ← genLExpr fctx octx tvars bctx n .bool
            let e ← genLExpr fctx octx tvars bctx n .bool
            pure (.ite () c t e))
          (fun () =>
            pick
              (fun () => do
                let τ' ← genLMonoTy tvars n
                let e₁ ← genLExpr fctx octx tvars bctx n τ'
                let e₂ ← genLExpr fctx octx tvars bctx n τ'
                pure (.eq () e₁ e₂))
              (fun () =>
                pick
                  (fun () => do
                    let τ' ← genLMonoTy tvars n
                    let arg ← genLExpr fctx octx tvars bctx n τ'
                    let fn  ← genLExpr fctx octx tvars bctx n (.arrow τ' .bool)
                    pure (.app () fn arg))
                  (fun () =>
                    pick
                      (fun () => do
                        let τ' ← genLMonoTy tvars n
                        let τ_tr ← genLMonoTy tvars n
                        let tr ← genLExpr fctx octx tvars (τ' :: bctx) n τ_tr
                        let body ← genLExpr fctx octx tvars (τ' :: bctx) n .bool
                        pure (.quant () .all "" (some τ') tr body))
                      (fun () =>
                        pick
                          (fun () => do
                            let τ' ← genLMonoTy tvars n
                            let τ_tr ← genLMonoTy tvars n
                            let tr ← genLExpr fctx octx tvars (τ' :: bctx) n τ_tr
                            let body ← genLExpr fctx octx tvars (τ' :: bctx) n .bool
                            pure (.quant () .exist "" (some τ') tr body))
                          (fun () =>
                            pick
                              (fun () =>
                                if hv : bvars.length > 0 then pickBVar bctx .bool hv
                                else pick (fun () => pure (.boolConst () true))
                                          (fun () => pure (.boolConst () false)))
                              (fun () =>
                                pick
                                  (fun () =>
                                    if hf : (fvarsOfType fctx .bool).length > 0
                                    then pickFVar fctx .bool hf
                                    else pick (fun () => pure (.boolConst () true))
                                              (fun () => pure (.boolConst () false)))
                                  (fun () =>
                                    if ho : (opsOfType octx .bool).length > 0
                                    then pickOp octx .bool ho
                                    else pick (fun () => pure (.boolConst () true))
                                              (fun () => pure (.boolConst () false))))))))))
  -- ── Int type ──────────────────────────────────────────────────────
  | 0, .int =>
    let bvars := bvarsOfType bctx .int
    pick
      (fun () =>
        pick
          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))
      (fun () =>
        pick
          (fun () =>
            if hv : bvars.length > 0 then pickBVar bctx .int hv
            else pick
              (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
              (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))
          (fun () =>
            pick
              (fun () =>
                if hf : (fvarsOfType fctx .int).length > 0
                then pickFVar fctx .int hf
                else pick
                  (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
                  (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))
              (fun () =>
                if ho : (opsOfType octx .int).length > 0
                then pickOp octx .int ho
                else pick
                  (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
                  (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))))
  | n + 1, .int =>
    let bvars := bvarsOfType bctx .int
    pick
      (fun () =>
        pick
          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))
      (fun () =>
        pick
          (fun () => do
            let τ' ← genLMonoTy tvars n
            let arg ← genLExpr fctx octx tvars bctx n τ'
            let fn  ← genLExpr fctx octx tvars bctx n (.arrow τ' .int)
            pure (.app () fn arg))
          (fun () =>
            pick
              (fun () => do
                let c ← genLExpr fctx octx tvars bctx n .bool
                let t ← genLExpr fctx octx tvars bctx n .int
                let e ← genLExpr fctx octx tvars bctx n .int
                pure (.ite () c t e))
              (fun () =>
                pick
                  (fun () =>
                    if hv : bvars.length > 0 then pickBVar bctx _ hv
                    else pick
                      (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
                      (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))
                  (fun () =>
                    pick
                      (fun () =>
                        if hf : (fvarsOfType fctx .int).length > 0
                        then pickFVar fctx .int hf
                        else pick
                          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
                          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))
                      (fun () =>
                        if ho : (opsOfType octx .int).length > 0
                        then pickOp octx .int ho
                        else pick
                          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
                          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))))))
  -- ── FtVar type (rigid type variable) ────────────────────────────────
  | 0, .ftvar name =>
    let bvars := bvarsOfType bctx (.ftvar name)
    pick
      (fun () =>
        if hv : bvars.length > 0 then pickBVar bctx _ hv
        else if hf : (fvarsOfType fctx (.ftvar name)).length > 0
        then pickFVar fctx _ hf
        else if ho : (opsOfType octx (.ftvar name)).length > 0
        then pickOp octx _ ho
        else default)
      (fun () =>
        pick
          (fun () =>
            if hf : (fvarsOfType fctx (.ftvar name)).length > 0
            then pickFVar fctx _ hf
            else if hv : bvars.length > 0 then pickBVar bctx _ hv
            else if ho : (opsOfType octx (.ftvar name)).length > 0
            then pickOp octx _ ho
            else default)
          (fun () =>
            if ho : (opsOfType octx (.ftvar name)).length > 0
            then pickOp octx _ ho
            else if hv : bvars.length > 0 then pickBVar bctx _ hv
            else if hf : (fvarsOfType fctx (.ftvar name)).length > 0
            then pickFVar fctx _ hf
            else default))
  | n + 1, .ftvar name =>
    let bvars := bvarsOfType bctx (.ftvar name)
    pick
      (fun () => do
        let τ' ← genLMonoTy tvars n
        let arg ← genLExpr fctx octx tvars bctx n τ'
        let fn  ← genLExpr fctx octx tvars bctx n (.arrow τ' (.ftvar name))
        pure (.app () fn arg))
      (fun () =>
        pick
          (fun () => do
            let c ← genLExpr fctx octx tvars bctx n .bool
            let t ← genLExpr fctx octx tvars bctx n (.ftvar name)
            let e ← genLExpr fctx octx tvars bctx n (.ftvar name)
            pure (.ite () c t e))
          (fun () =>
            pick
              (fun () =>
                if hv : bvars.length > 0 then pickBVar bctx _ hv
                else if hf : (fvarsOfType fctx (.ftvar name)).length > 0
                then pickFVar fctx _ hf
                else if ho : (opsOfType octx (.ftvar name)).length > 0
                then pickOp octx _ ho
                else default)
              (fun () =>
                pick
                  (fun () =>
                    if hf : (fvarsOfType fctx (.ftvar name)).length > 0
                    then pickFVar fctx _ hf
                    else if hv : bvars.length > 0 then pickBVar bctx _ hv
                    else default)
                  (fun () =>
                    if ho : (opsOfType octx (.ftvar name)).length > 0
                    then pickOp octx _ ho
                    else if hv : bvars.length > 0 then pickBVar bctx _ hv
                    else default))))
  -- ── Fallback (bitvec, etc. — not generated) ────────────────────────
  | _, _ => pure (.boolConst () false)

/-- Generate a well-typed closed expression with bounded depth. -/
def genClosedLExpr [Gen G] (tvars : List TyIdentifier) (size : Nat) : G LExpr' := do
  let τ ← genLMonoTy tvars size
  genLExpr [] [] tvars [] size τ

-- ── bvarsOfType spec ──────────────────────────────────────────────────

private theorem bvarsOfType_go_spec (τ : LMonoTy) :
    ∀ (bctx : BVarCtx) (base i : Nat),
      i ∈ bvarsOfType.go τ bctx base ↔
        ∃ k, k < bctx.length ∧ i = base + k ∧ bctx[k]? = some τ := by
  intro bctx
  induction bctx with
  | nil => simp [bvarsOfType.go]
  | cons τ' rest ih =>
    intro base i
    simp only [bvarsOfType.go]
    split
    · rename_i heq
      have hτeq : τ' = τ := beq_iff_eq.mp heq
      simp only [List.mem_cons]; rw [ih]
      constructor
      · rintro (rfl | ⟨k, hk, rfl, hget⟩)
        · exact ⟨0, by simp, by omega, by simp [hτeq]⟩
        · exact ⟨k + 1, by simp; omega, by omega,
            by simp [List.getElem?_cons_succ]; exact hget⟩
      · rintro ⟨k, hk, hx, hget⟩
        match k with
        | 0 => simp at hget; left; omega
        | k + 1 =>
          right; exact ⟨k, by simp at hk; omega, by omega,
            by simp [List.getElem?_cons_succ] at hget; exact hget⟩
    · rename_i heq
      have hτne : τ' ≠ τ := fun h => absurd (beq_iff_eq.mpr h) heq
      rw [ih]
      constructor
      · rintro ⟨k, hk, rfl, hget⟩
        exact ⟨k + 1, by simp; omega, by omega,
          by simp [List.getElem?_cons_succ]; exact hget⟩
      · rintro ⟨k, hk, hx, hget⟩
        match k with
        | 0 =>
          simp at hget
          exact absurd hget hτne
        | k + 1 =>
          exact ⟨k, by simp at hk; omega, by omega,
            by simp [List.getElem?_cons_succ] at hget; exact hget⟩

private theorem bvarsOfType_mem_iff (bctx : BVarCtx) (τ : LMonoTy) (i : Nat) :
    i ∈ bvarsOfType bctx τ ↔ bctx[i]? = some τ := by
  unfold bvarsOfType
  rw [bvarsOfType_go_spec]
  constructor
  · rintro ⟨k, _, rfl, hget⟩; simpa using hget
  · intro hget
    have hlt : i < bctx.length := by
      rw [List.getElem?_eq_some_iff] at hget; exact hget.1
    exact ⟨i, hlt, by omega, hget⟩

-- ── pickBVar soundness/completeness ───────────────────────────────────

private theorem pickBVar_sound (bctx : BVarCtx) (τ : LMonoTy)
    (hv : (bvarsOfType bctx τ).length > 0) (e : LExpr')
    (he : e ∈ SetGen.support (pickBVar (G := SetGen.Set) bctx τ hv)) :
    HasTypeA' bctx e τ := by
  simp only [pickBVar, mem_support_iff, Set.mem_bind, Set.mem_pure] at he
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := he
  subst heq
  apply LExpr.HasTypeA.bvar
  rw [← bvarsOfType_mem_iff]
  set indices := bvarsOfType bctx τ
  have hlt : idx.down < indices.length := by omega
  have : indices.getD idx.down 0 = indices[idx.down] := by
    simp [List.getD, List.getElem?_eq_getElem hlt]
  rw [this]
  exact List.getElem_mem hlt

private theorem pickBVar_complete (bctx : BVarCtx) (τ : LMonoTy) (i : Nat)
    (hget : bctx[i]? = some τ)
    (hv : (bvarsOfType bctx τ).length > 0) :
    .bvar () i ∈ SetGen.support (pickBVar (G := SetGen.Set) bctx τ hv) := by
  simp only [pickBVar, mem_support_iff, Set.mem_bind, Set.mem_pure]
  have hmem : i ∈ bvarsOfType bctx τ := (bvarsOfType_mem_iff bctx τ i).mpr hget
  obtain ⟨idx, hidx_lt, hidx_eq⟩ := List.getElem_of_mem hmem
  have : idx ≤ (bvarsOfType bctx τ).length - 1 := by omega
  refine ⟨⟨idx⟩, ⟨Nat.zero_le _, this⟩, ?_⟩
  simp [List.getD, List.getElem?_eq_getElem hidx_lt, hidx_eq]

-- ── pickFVar soundness/completeness ───────────────────────────────────

private theorem fvarsOfType_mem_iff (fctx : FVarCtx) (τ : LMonoTy) (x : String) :
    x ∈ fvarsOfType fctx τ ↔ (x, τ) ∈ fctx := by
  simp only [fvarsOfType, List.mem_filterMap]
  constructor
  · rintro ⟨⟨y, ty⟩, hmem, hif⟩
    simp only at hif
    split at hif
    · rename_i heq
      have := beq_iff_eq.mp heq
      simp at hif; subst hif; subst this; exact hmem
    · simp at hif
  · intro hmem
    refine ⟨(x, τ), hmem, ?_⟩
    simp only
    split
    · simp
    · rename_i hne; exact absurd (beq_iff_eq.mpr rfl) hne

private theorem pickFVar_sound (fctx : FVarCtx) (τ : LMonoTy)
    (hv : (fvarsOfType fctx τ).length > 0) (e : LExpr')
    (he : e ∈ SetGen.support (pickFVar (G := SetGen.Set) fctx τ hv)) :
    HasTypeA' bctx e τ := by
  simp only [pickFVar, mem_support_iff, Set.mem_bind, Set.mem_pure] at he
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := he
  subst heq
  exact .fvar

private theorem pickFVar_complete (fctx : FVarCtx) (τ : LMonoTy) (x : String)
    (hmem : (x, τ) ∈ fctx)
    (hv : (fvarsOfType fctx τ).length > 0) :
    .fvar () ⟨x, ()⟩ (some τ) ∈ SetGen.support (pickFVar (G := SetGen.Set) fctx τ hv) := by
  simp only [pickFVar, mem_support_iff, Set.mem_bind, Set.mem_pure]
  have hmem' : x ∈ fvarsOfType fctx τ := (fvarsOfType_mem_iff fctx τ x).mpr hmem
  obtain ⟨idx, hidx_lt, hidx_eq⟩ := List.getElem_of_mem hmem'
  have : idx ≤ (fvarsOfType fctx τ).length - 1 := by omega
  refine ⟨⟨idx⟩, ⟨Nat.zero_le _, this⟩, ?_⟩
  simp [List.getD, List.getElem?_eq_getElem hidx_lt, hidx_eq]

-- ── pickOp soundness/completeness ─────────────────────────────────────

private theorem opsOfType_mem_iff (octx : OpCtx) (τ : LMonoTy) (x : String) :
    x ∈ opsOfType octx τ ↔ (x, τ) ∈ octx := by
  simp only [opsOfType, List.mem_filterMap]
  constructor
  · rintro ⟨⟨y, ty⟩, hmem, hif⟩
    simp only at hif
    split at hif
    · rename_i heq
      have := beq_iff_eq.mp heq
      simp at hif; subst hif; subst this; exact hmem
    · simp at hif
  · intro hmem
    refine ⟨(x, τ), hmem, ?_⟩
    simp only
    split
    · simp
    · rename_i hne; exact absurd (beq_iff_eq.mpr rfl) hne

private theorem pickOp_sound (octx : OpCtx) (τ : LMonoTy)
    (hv : (opsOfType octx τ).length > 0) (e : LExpr')
    (he : e ∈ SetGen.support (pickOp (G := SetGen.Set) octx τ hv)) :
    HasTypeA' bctx e τ := by
  simp only [pickOp, mem_support_iff, Set.mem_bind, Set.mem_pure] at he
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := he
  subst heq
  exact .op

private theorem pickOp_complete (octx : OpCtx) (τ : LMonoTy) (x : String)
    (hmem : (x, τ) ∈ octx)
    (hv : (opsOfType octx τ).length > 0) :
    .op () ⟨x, ()⟩ (some τ) ∈ SetGen.support (pickOp (G := SetGen.Set) octx τ hv) := by
  simp only [pickOp, mem_support_iff, Set.mem_bind, Set.mem_pure]
  have hmem' : x ∈ opsOfType octx τ := (opsOfType_mem_iff octx τ x).mpr hmem
  obtain ⟨idx, hidx_lt, hidx_eq⟩ := List.getElem_of_mem hmem'
  have : idx ≤ (opsOfType octx τ).length - 1 := by omega
  refine ⟨⟨idx⟩, ⟨Nat.zero_le _, this⟩, ?_⟩
  simp [List.getD, List.getElem?_eq_getElem hidx_lt, hidx_eq]

-- ── genLMonoTy support ────────────────────────────────────────────────

/-- All ftvar names in a type belong to the palette. -/
def allFtvarsIn (tvars : List TyIdentifier) : LMonoTy → Prop
  | .ftvar name => name ∈ tvars
  | .tcons _ args => ∀ a ∈ args, allFtvarsIn tvars a
  | .bitvec _ => True

/-- `genLMonoTy tvars n` generates exactly the simple types of depth ≤ `n`
    whose ftvar names are drawn from `tvars`. -/
private theorem pickTyVar_mem (tvars : List TyIdentifier) (h : tvars.length > 0) (τ : LMonoTy)
    (hτ : τ ∈ SetGen.support (pickTyVar (G := SetGen.Set) tvars h)) :
    ∃ name, name ∈ tvars ∧ τ = .ftvar name := by
  simp only [pickTyVar, mem_support_bind_iff, mem_support_choose_iff,
             mem_support_pure_iff] at hτ
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := hτ
  subst heq
  have hlt : idx.down < tvars.length := by omega
  refine ⟨tvars.getD idx.down "", ?_, rfl⟩
  have : tvars.getD idx.down "" = tvars[idx.down] := by
    simp [List.getD, List.getElem?_eq_getElem hlt]
  rw [this]
  exact List.getElem_mem hlt

theorem genLMonoTy_support (tvars : List TyIdentifier) (n : Nat) (τ : LMonoTy) :
    τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) tvars n) ↔
      SimpleType τ ∧ monoTyDepth τ ≤ n ∧ allFtvarsIn tvars τ := by
  sorry

/-- Corollary: anything generated by `genLMonoTy` is a `SimpleType`. -/
theorem genLMonoTy_simple (tvars : List TyIdentifier) (n : Nat) (τ : LMonoTy)
    (h : τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) tvars n)) : SimpleType τ :=
  ((genLMonoTy_support tvars n τ).mp h).1

-- ── Soundness for genLExpr ────────────────────────────────────────────

-- `LMonoTy.bool`, `.int`, `.arrow` are abbreviations for `.tcons "bool" []` etc.
-- In Strata, they're defined as abbreviations via the `abbrev` keyword,
-- e.g. `abbrev LMonoTy.arrow τ₁ τ₂ := .tcons "arrow" [τ₁, τ₂]`.
-- Now, when we define `genLExpr` via pattern-matching,
-- Lean's automatically generated equational lemmas are defined in terms of the expanded constructor,
-- i.e. `LmonoTy.tcons "arrow" [τ₁, τ₂]` instead of `LMonoTy.arrow τ₁ τ₂`.
-- Thus, when we have a hypothesis that mentions `genLExpr`, e.g. `he : e ∈ support (genLExpr fctx octx tvars bctx 0 (LMonoTy.arrow τ₁ τ₂))`,
-- when we try to naively do `simp only [genLExpr]`,
-- Lean tries to match `LMonoTy.tcons "arrow" [τ₁, τ₂]` against the subterm `LMonoTy.arrow τ₁ τ₂` in the hypothesis.
-- Even though the two terms are definitionally equal, the `simp/rw` tactics require syntactic equality,
-- so we have to add the following rewrite lemmas which normalize the abbreviation,
-- so that the equation lemmas can match.
private theorem norm_bool : LMonoTy.bool = LMonoTy.tcons "bool" [] := rfl
private theorem norm_int : LMonoTy.int = LMonoTy.tcons "int" [] := rfl
private theorem norm_arrow (τ₁ τ₂ : LMonoTy) :
    LMonoTy.arrow τ₁ τ₂ = LMonoTy.tcons "arrow" [τ₁, τ₂] := rfl


set_option maxHeartbeats 800000 in
/-- Every expression in the support of `genLExpr fctx octx tvars bctx size τ` is
    well-typed whenever `τ` is a `SimpleType`. -/
theorem genLExpr_sound (fctx : FVarCtx) (octx : OpCtx)
    (tvars : List TyIdentifier)
    (bctx : BVarCtx) (size : Nat) (τ : LMonoTy)
    (hτ : SimpleType τ) (e : LExpr')
    (he : e ∈ SetGen.support (genLExpr (G := SetGen.Set) fctx octx tvars bctx size τ)) :
    HasTypeA' bctx e τ := by
  match size, τ, hτ with
  | 0, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExpr, pick_mem_iff,
      mem_support_iff, SetGen.mem_dite] at he
    rcases he with (rfl | rfl) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | (⟨_, h⟩ | ⟨_, rfl | rfl⟩)))
    all_goals first
      | exact (by unfold LExpr.boolConst; exact .const)
      | exact pickBVar_sound bctx .bool _ _ h
      | exact pickFVar_sound fctx .bool _ _ h
      | exact pickOp_sound octx .bool _ _ h
  | 0, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨k, _, rfl⟩ | ⟨k, _, rfl⟩) | ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | (⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩)))
    all_goals first
      | exact (by unfold LExpr.intConst; exact .const)
      | exact pickBVar_sound bctx .int _ _ h
      | exact pickFVar_sound fctx .int _ _ h
      | exact pickOp_sound octx .int _ _ h
  | 0, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | ((⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | (⟨_, h⟩ | ⟨_, body, hbody, rfl⟩))
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact .abs (genLExpr_sound fctx octx tvars (τ₁ :: bctx) 0 τ₂ hs₂ _ hbody)
  | n + 1, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (rfl | rfl) | ⟨c, hc, t, ht, e', he', rfl⟩ | ⟨τ', hτ'm, e₁, he₁, e₂, he₂, rfl⟩ |
      ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | ((⟨_, h⟩ | ⟨_, rfl | rfl⟩) | (⟨_, h⟩ | ⟨_, rfl | rfl⟩)))
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact .ite (genLExpr_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExpr_sound fctx octx tvars bctx n _ SimpleType.bool _ ht)
                  (genLExpr_sound fctx octx tvars bctx n _ SimpleType.bool _ he')
    · exact .eq (genLExpr_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ he₁)
                 (genLExpr_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ he₂)
    · exact .app (genLExpr_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.bool) _ hfn)
                  (genLExpr_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .quant (genLExpr_sound fctx octx tvars (τ' :: bctx) n _ (genLMonoTy_simple tvars n _ hτ_tr_m) _ htr)
                    (genLExpr_sound fctx octx tvars (τ' :: bctx) n _ SimpleType.bool _ hbody)
    · exact .quant (genLExpr_sound fctx octx tvars (τ' :: bctx) n _ (genLMonoTy_simple tvars n _ hτ_tr_m) _ htr)
                    (genLExpr_sound fctx octx tvars (τ' :: bctx) n _ SimpleType.bool _ hbody)
    all_goals first
      | exact pickBVar_sound bctx .bool _ _ h
      | exact pickFVar_sound fctx .bool _ _ h
      | exact pickOp_sound octx .bool _ _ h
      | exact (by unfold LExpr.boolConst; exact .const)
  | n + 1, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨k, _, rfl⟩ | ⟨k, _, rfl⟩) | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | ((⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩) | (⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩)))
    · exact (by unfold LExpr.intConst; exact .const)
    · exact (by unfold LExpr.intConst; exact .const)
    · exact .app (genLExpr_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.int) _ hfn)
                  (genLExpr_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .ite (genLExpr_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExpr_sound fctx octx tvars bctx n _ SimpleType.int _ ht)
                  (genLExpr_sound fctx octx tvars bctx n _ SimpleType.int _ he')
    all_goals first
      | exact pickBVar_sound bctx .int _ _ h
      | exact pickFVar_sound fctx .int _ _ h
      | exact pickOp_sound octx .int _ _ h
      | exact (by unfold LExpr.intConst; exact .const)
  | n + 1, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with ⟨body, hbody, rfl⟩ | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | ((⟨_, h⟩ | ⟨_, body, hbody, rfl⟩) | (⟨_, h⟩ | ⟨_, body, hbody, rfl⟩)))
    · exact .abs (genLExpr_sound fctx octx tvars (τ₁ :: bctx) n _ hs₂ _ hbody)
    · exact .app (genLExpr_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) (SimpleType.arrow hs₁ hs₂)) _ hfn)
                  (genLExpr_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .ite (genLExpr_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExpr_sound fctx octx tvars bctx n _ (SimpleType.arrow hs₁ hs₂) _ ht)
                  (genLExpr_sound fctx octx tvars bctx n _ (SimpleType.arrow hs₁ hs₂) _ he')
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact .abs (genLExpr_sound fctx octx tvars (τ₁ :: bctx) n _ hs₂ _ hbody)
  | 0, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExpr, pick_mem_iff, mem_support_iff, SetGen.mem_dite,
               bot_mem_iff] at he
    rcases he with (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
      ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
       (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩))
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact absurd h (by simp)
  | n + 1, _, SimpleType.ftvar =>
    rename_i name
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
               mem_support_iff, SetGen.mem_dite, bot_mem_iff] at he
    rcases he with ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ |
      ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩⟩) |
       ((⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩) |
        (⟨_, h⟩ | ⟨_, ⟨_, h⟩ | ⟨_, h⟩⟩)))
    · exact .app (genLExpr_sound fctx octx tvars bctx n _ (SimpleType.arrow (genLMonoTy_simple tvars n _ hτ'm) SimpleType.ftvar) _ hfn)
                  (genLExpr_sound fctx octx tvars bctx n _ (genLMonoTy_simple tvars n _ hτ'm) _ harg)
    · exact .ite (genLExpr_sound fctx octx tvars bctx n _ SimpleType.bool _ hc)
                  (genLExpr_sound fctx octx tvars bctx n _ SimpleType.ftvar _ ht)
                  (genLExpr_sound fctx octx tvars bctx n _ SimpleType.ftvar _ he')
    all_goals first
      | exact pickBVar_sound bctx _ _ _ h
      | exact pickFVar_sound fctx _ _ _ h
      | exact pickOp_sound octx _ _ _ h
      | exact absurd h (by simp)
  termination_by (size, sizeOf τ)
  decreasing_by all_goals simp_wf; first | omega | simp_all [LMonoTy.arrow]; omega

-- ── Nat.arbitrary support for SetGen.Set ──────────────────────────────

/-- Every natural number is in the support of `Nat.arbitrary` at `SetGen.Set`. -/
private theorem Nat_arbitrary_support_set (n : Nat) :
    n ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)) := by
  induction n with
  | zero =>
    simp only [SetGen.support]
    rw [Nat.arbitrary]
    simp [pick_mem_iff]
  | succ n ih =>
    simp only [SetGen.support] at ih ⊢
    rw [Nat.arbitrary]
    simp only [pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure]
    right
    exact ⟨n, ih, rfl⟩

/-- Every integer is reachable via `pick` between `(k : Int)` and `-(k+1)`. -/
private theorem Int_cover (z : Int) :
    (∃ k : Nat, k ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)) ∧ (↑k : Int) = z) ∨
    (∃ k : Nat, k ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)) ∧ (-(↑k + 1 : Int)) = z) := by
  cases z with
  | ofNat n => left; exact ⟨n, Nat_arbitrary_support_set n, rfl⟩
  | negSucc n => right; exact ⟨n, Nat_arbitrary_support_set n, by simp [Int.negSucc_eq]⟩

-- ── emptyNames predicate ──────────────────────────────────────────────

/-- All binder names in the expression are empty strings. -/
def emptyNames : LExpr' → Prop
  | .boolConst () _                  => True
  | .intConst () _                   => True
  | .bvar () _                       => True
  | .fvar () _ _                     => True
  | .op () _ _                       => True
  | .abs () name _ body              => name = "" ∧ emptyNames body
  | .app () fn arg                   => emptyNames fn ∧ emptyNames arg
  | .ite () c t e                    => emptyNames c ∧ emptyNames t ∧ emptyNames e
  | .eq () e₁ e₂                     => emptyNames e₁ ∧ emptyNames e₂
  | .quant () _ name _ tr body       => name = "" ∧ emptyNames tr ∧ emptyNames body
  | .const () _                      => True

-- ── termDepth measure ─────────────────────────────────────────────────

/-- The "depth" of a term: how much fuel `genLExpr` needs to produce it.
    This accounts for the depth of types used in the term
    (since `genLMonoTy` needs fuel proportional to type depth). -/
private def termDepth (bctx : BVarCtx) : LExpr' → Nat
  | .boolConst () _       => 0
  | .intConst () _        => 0
  | .bvar () _            => 0
  | .fvar () _ _          => 0
  | .op () _ _            => 0
  | .abs () _ (some τ₁) body => termDepth (τ₁ :: bctx) body + 1
  | .app () fn arg        => max (termDepth bctx fn) (termDepth bctx arg) + 1
  | .ite () c t e         => max (termDepth bctx c) (max (termDepth bctx t) (termDepth bctx e)) + 1
  | .eq () e₁ e₂          => max (termDepth bctx e₁) (termDepth bctx e₂) + 1
  | .quant () _ _ (some τ) tr body =>
      max (monoTyDepth τ) (max (termDepth (τ :: bctx) tr) (termDepth (τ :: bctx) body)) + 1
  | _                     => 0

/-- All type annotations occurring in an expression are simple and have depth bounded
    appropriately. The `n` parameter decreases by 1 at each compound expression level,
    matching the generator's fuel consumption. At level `n+1`, intermediate types
    produced by `genLMonoTy n` have depth ≤ `n`, and sub-expressions need `AllTypesSimple n`. -/
inductive AllTypesSimple : Nat → BVarCtx → LExpr' → Prop where
  | boolConst : AllTypesSimple n bctx (.boolConst () b)
  | intConst  : AllTypesSimple n bctx (.intConst () k)
  | bvar      : AllTypesSimple n bctx (.bvar () i)
  | fvar      : AllTypesSimple n bctx (.fvar () x (some τ))
  | op        : AllTypesSimple n bctx (.op () o (some τ))
  | abs       : SimpleType τ₁ → monoTyDepth τ₁ ≤ n →
                AllTypesSimple n (τ₁ :: bctx) body →
                AllTypesSimple (n + 1) bctx (.abs () "" (some τ₁) body)
  | app       : (τ' : LMonoTy) →
                HasTypeA' bctx arg τ' →
                SimpleType τ' → monoTyDepth τ' ≤ n →
                AllTypesSimple n bctx fn → AllTypesSimple n bctx arg →
                AllTypesSimple (n + 1) bctx (.app () fn arg)
  | ite       : AllTypesSimple n bctx c → AllTypesSimple n bctx t →
                AllTypesSimple n bctx e →
                AllTypesSimple (n + 1) bctx (.ite () c t e)
  | eq        : (τ' : LMonoTy) →
                HasTypeA' bctx e₁ τ' → HasTypeA' bctx e₂ τ' →
                SimpleType τ' → monoTyDepth τ' ≤ n →
                AllTypesSimple n bctx e₁ → AllTypesSimple n bctx e₂ →
                AllTypesSimple (n + 1) bctx (.eq () e₁ e₂)
  | quant     : SimpleType τ → monoTyDepth τ ≤ n →
                (τ_tr : LMonoTy) → SimpleType τ_tr → monoTyDepth τ_tr ≤ n →
                HasTypeA' (τ :: bctx) tr τ_tr →
                AllTypesSimple n (τ :: bctx) tr →
                AllTypesSimple n (τ :: bctx) body →
                AllTypesSimple (n + 1) bctx (.quant () k "" (some τ) tr body)

-- ── Completeness for genLExpr ─────────────────────────────────────────

/-- Typing is deterministic for annotated expressions. -/
private theorem typing_deterministic {bctx : BVarCtx} {e : LExpr'} {τ₁ τ₂ : LMonoTy}
    (h₁ : HasTypeA' bctx e τ₁) (h₂ : HasTypeA' bctx e τ₂) : τ₁ = τ₂ := by
  have := LExpr.HasTypeA_to_typeCheck h₁
  have := LExpr.HasTypeA_to_typeCheck h₂
  simp_all

/-- If `.boolConst () b` has type `τ`, then `τ = .bool`. -/
private theorem boolConst_hasType_bool {bctx : BVarCtx} {τ : LMonoTy} {b : Bool}
    (h : HasTypeA' bctx (.boolConst () b) τ) : τ = .bool := by
  have htc := LExpr.HasTypeA_to_typeCheck h
  simp [LExpr.typeCheck] at htc
  exact htc.symm

/-- If `.intConst () n` has type `τ`, then `τ = .int`. -/
private theorem intConst_hasType_int {bctx : BVarCtx} {τ : LMonoTy} {n : Int}
    (h : HasTypeA' bctx (.intConst () n) τ) : τ = .int := by
  have htc := LExpr.HasTypeA_to_typeCheck h
  simp [LExpr.typeCheck] at htc
  exact htc.symm

/-- If `.eq () e₁ e₂` has type `τ`, then `τ = .bool`. -/
private theorem eq_hasType_bool {bctx : BVarCtx} {τ : LMonoTy} {e₁ e₂ : LExpr'}
    (h : HasTypeA' bctx (.eq () e₁ e₂) τ) : τ = .bool := by
  cases h with
  | eq _ _ => rfl

/-- If `.quant () k name (some qty) tr body` has type `τ`, then `τ = .bool`. -/
private theorem quant_hasType_bool {bctx : BVarCtx} {τ : LMonoTy}
    {k name qty tr body}
    (h : HasTypeA' bctx (.quant () k name (some qty) tr body) τ) : τ = .bool := by
  cases h with
  | quant _ _ => rfl

/-- If `.abs () name (some aty) body` has type `τ`, then `τ = .arrow aty rty` for some `rty`. -/
private theorem abs_hasType_arrow {bctx : BVarCtx} {τ : LMonoTy}
    {name aty body}
    (h : HasTypeA' bctx (.abs () name (some aty) body) τ) : ∃ rty, τ = .arrow aty rty := by
  cases h with
  | abs _ => exact ⟨_, rfl⟩

/-- If `.fvar () x (some ty)` has type `τ`, then `τ = ty`. -/
private theorem fvar_hasType {bctx : BVarCtx} {τ : LMonoTy} {x ty}
    (h : HasTypeA' bctx (.fvar () x (some ty)) τ) : τ = ty := by
  cases h with
  | fvar => rfl

/-- If `.op () o (some ty)` has type `τ`, then `τ = ty`. -/
private theorem op_hasType {bctx : BVarCtx} {τ : LMonoTy} {o ty}
    (h : HasTypeA' bctx (.op () o (some ty)) τ) : τ = ty := by
  cases h with
  | op => rfl

/-- Predicate asserting that all fvar names in the expression are in `fctx`
    (with the correct type) and all op names are in `octx`. -/
def allVarsInCtx (fctx : FVarCtx) (octx : OpCtx) : LExpr' → Prop
  | .boolConst () _              => True
  | .intConst () _               => True
  | .bvar () _                   => True
  | .fvar () x (some τ)         => (x.name, τ) ∈ fctx
  | .fvar () _ none              => True
  | .op () o (some τ)           => (o.name, τ) ∈ octx
  | .op () _ none                => True
  | .abs () _ _ body             => allVarsInCtx fctx octx body
  | .app () fn arg               => allVarsInCtx fctx octx fn ∧ allVarsInCtx fctx octx arg
  | .ite () c t e                => allVarsInCtx fctx octx c ∧ allVarsInCtx fctx octx t ∧ allVarsInCtx fctx octx e
  | .eq () e₁ e₂                 => allVarsInCtx fctx octx e₁ ∧ allVarsInCtx fctx octx e₂
  | .quant () _ _ _ tr body      => allVarsInCtx fctx octx tr ∧ allVarsInCtx fctx octx body
  | .const () _                  => True

set_option maxHeartbeats 1600000 in
/-- Completeness of `genLExpr`: every well-typed expression satisfying the
    fragment constraints is in the support of `genLExpr` for a sufficiently
    large `size` parameter. -/
theorem genLExpr_complete (fctx : FVarCtx) (octx : OpCtx)
    (tvars : List TyIdentifier)
    (bctx : BVarCtx) (size : Nat) (τ : LMonoTy)
    (hτ : SimpleType τ)
    (e : LExpr')
    (hwt : HasTypeA' bctx e τ)
    (hnames : emptyNames e)
    (hvars : allVarsInCtx fctx octx e)
    (hats : AllTypesSimple size bctx e)
    (hsize : termDepth bctx e ≤ size) :
    e ∈ SetGen.support (genLExpr (G := SetGen.Set) fctx octx tvars bctx size τ) := by
  match size, τ, hτ with
  | 0, _, SimpleType.bool =>
    rw [norm_bool]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | @boolConst _ _ b =>
      cases hwt with
      | const =>
        left
        cases b with
        | true => left; rfl
        | false => right; rfl
    | intConst =>
      exact absurd (intConst_hasType_int hwt) (by simp [LMonoTy.bool, LMonoTy.int])
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; left; left
        have hlen : (bvarsOfType bctx .bool).length > 0 := by
          have := (bvarsOfType_mem_iff bctx .bool _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx .bool _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx .bool).length > 0 := by
          have := (fvarsOfType_mem_iff fctx .bool _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx .bool _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx .bool).length > 0 := by
          have := (opsOfType_mem_iff octx .bool _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx .bool _ hmem hlen⟩
  | 0, _, SimpleType.int =>
    rw [norm_int]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | intConst =>
      cases hwt with
      | const =>
        left
        have hic := Int_cover (by assumption : Int)
        rcases hic with ⟨k, hk, rfl⟩ | ⟨k, hk, rfl⟩
        · left; exact ⟨k, hk, rfl⟩
        · right; exact ⟨k, hk, rfl⟩
    | boolConst =>
      exact absurd (boolConst_hasType_bool hwt) (by simp [LMonoTy.bool, LMonoTy.int])
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; left; left
        have hlen : (bvarsOfType bctx .int).length > 0 := by
          have := (bvarsOfType_mem_iff bctx .int _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx .int _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx .int).length > 0 := by
          have := (fvarsOfType_mem_iff fctx .int _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx .int _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx .int).length > 0 := by
          have := (opsOfType_mem_iff octx .int _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx .int _ hmem hlen⟩
  | 0, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | boolConst =>
      exact absurd (boolConst_hasType_bool hwt) (by intro h; simp [LMonoTy.bool, LMonoTy.arrow] at h)
    | intConst =>
      exact absurd (intConst_hasType_int hwt) (by intro h; simp [LMonoTy.int, LMonoTy.arrow] at h)
    | bvar =>
      cases hwt with
      | bvar hget =>
        left; left
        have hlen : (bvarsOfType bctx (.arrow τ₁ τ₂)).length > 0 := by
          have := (bvarsOfType_mem_iff bctx (.arrow τ₁ τ₂) _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx (.arrow τ₁ τ₂) _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx (.arrow τ₁ τ₂)).length > 0 := by
          have := (fvarsOfType_mem_iff fctx (.arrow τ₁ τ₂) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx (.arrow τ₁ τ₂) _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx (.arrow τ₁ τ₂)).length > 0 := by
          have := (opsOfType_mem_iff octx (.arrow τ₁ τ₂) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx (.arrow τ₁ τ₂) _ hmem hlen⟩
  | n + 1, _, SimpleType.bool =>
    rw [norm_bool]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | boolConst =>
      cases hwt with
      | const => left; cases (by assumption : Bool) <;> simp [LExpr.boolConst]
    | intConst =>
      exact absurd (intConst_hasType_int hwt) (by simp [LMonoTy.bool, LMonoTy.int])
    | abs _ _ _ =>
      exact absurd (abs_hasType_arrow hwt) (by intro ⟨_, h⟩; simp [LMonoTy.bool, LMonoTy.arrow] at h)
    | ite hc ht he_ =>
      cases hwt with
      | ite hcw htw hew =>
        simp [termDepth] at hsize
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; left
        refine ⟨_, genLExpr_complete fctx octx tvars bctx n .bool SimpleType.bool _ hcw hnames.1 hvars.1 hc (by omega),
               _, genLExpr_complete fctx octx tvars bctx n .bool SimpleType.bool _ htw hnames.2.1 hvars.2.1 ht (by omega),
               _, genLExpr_complete fctx octx tvars bctx n .bool SimpleType.bool _ hew hnames.2.2 hvars.2.2 he_ (by omega), rfl⟩
    | eq τ' he1w he2w hsτ' hdτ' hats1 hats2 =>
      cases hwt with
      | eq hwt1 hwt2 =>
        have hτeq := typing_deterministic he1w hwt1
        subst hτeq
        simp [termDepth] at hsize
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; right; left
        refine ⟨τ', (genLMonoTy_support tvars n τ').mpr ⟨hsτ', hdτ', sorry⟩,
               _, genLExpr_complete fctx octx tvars bctx n τ' hsτ' _ hwt1 hnames.1 hvars.1 hats1 (by omega),
               _, genLExpr_complete fctx octx tvars bctx n τ' hsτ' _ hwt2 hnames.2 hvars.2 hats2 (by omega), rfl⟩
    | app τ' hargw hsτ' hdτ' hfn_ats harg_ats =>
      cases hwt with
      | app hfnw hargw' =>
        have hτeq := typing_deterministic hargw hargw'
        subst hτeq
        simp [termDepth] at hsize
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; right; right; left
        refine ⟨τ', (genLMonoTy_support tvars n τ').mpr ⟨hsτ', hdτ', sorry⟩,
               _, genLExpr_complete fctx octx tvars bctx n τ' hsτ' _ hargw' hnames.2 hvars.2 harg_ats (by omega),
               _, genLExpr_complete fctx octx tvars bctx n (.arrow τ' .bool) (SimpleType.arrow hsτ' SimpleType.bool) _ hfnw hnames.1 hvars.1 hfn_ats (by omega), rfl⟩
    | quant hsτ' hdτ' τ_tr hsτ_tr hdτ_tr htrw htr_ats hbody_ats =>
      cases hwt with
      | quant htrw' hbodyw =>
        have hτ_tr_eq := typing_deterministic htrw htrw'
        subst hτ_tr_eq
        simp [termDepth] at hsize
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        rename_i k
        cases k with
        | all =>
          right; right; right; right; left
          refine ⟨_, (genLMonoTy_support tvars n _).mpr ⟨hsτ', hdτ', sorry⟩,
                 _, (genLMonoTy_support tvars n _).mpr ⟨hsτ_tr, hdτ_tr, sorry⟩,
                 _, genLExpr_complete fctx octx tvars (_ :: bctx) n τ_tr hsτ_tr _ htrw' hnames.2.1 hvars.1 htr_ats (by omega),
                 _, genLExpr_complete fctx octx tvars (_ :: bctx) n .bool SimpleType.bool _ hbodyw hnames.2.2 hvars.2 hbody_ats (by omega), rfl⟩
        | exist =>
          right; right; right; right; right; left
          refine ⟨_, (genLMonoTy_support tvars n _).mpr ⟨hsτ', hdτ', sorry⟩,
                 _, (genLMonoTy_support tvars n _).mpr ⟨hsτ_tr, hdτ_tr, sorry⟩,
                 _, genLExpr_complete fctx octx tvars (_ :: bctx) n τ_tr hsτ_tr _ htrw' hnames.2.1 hvars.1 htr_ats (by omega),
                 _, genLExpr_complete fctx octx tvars (_ :: bctx) n .bool SimpleType.bool _ hbodyw hnames.2.2 hvars.2 hbody_ats (by omega), rfl⟩
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; right; right; right; right; right; left; left
        have hlen : (bvarsOfType bctx .bool).length > 0 := by
          have := (bvarsOfType_mem_iff bctx .bool _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx .bool _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; right; right; right; right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx .bool).length > 0 := by
          have := (fvarsOfType_mem_iff fctx .bool _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx .bool _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; right; right; right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx .bool).length > 0 := by
          have := (opsOfType_mem_iff octx .bool _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx .bool _ hmem hlen⟩
  | n + 1, _, SimpleType.int =>
    rw [norm_int]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | intConst =>
      cases hwt with
      | const =>
        left
        have hic := Int_cover (by assumption : Int)
        rcases hic with ⟨k, hk, rfl⟩ | ⟨k, hk, rfl⟩
        · left; exact ⟨k, hk, rfl⟩
        · right; exact ⟨k, hk, rfl⟩
    | boolConst =>
      exact absurd (boolConst_hasType_bool hwt) (by simp [LMonoTy.bool, LMonoTy.int])
    | abs _ _ _ =>
      exact absurd (abs_hasType_arrow hwt) (by intro ⟨_, h⟩; simp [LMonoTy.int, LMonoTy.arrow] at h)
    | eq _ _ _ _ _ _ _ =>
      exact absurd (eq_hasType_bool hwt) (by simp [LMonoTy.int, LMonoTy.bool])
    | quant _ _ _ _ _ _ _ _ =>
      exact absurd (quant_hasType_bool hwt) (by simp [LMonoTy.int, LMonoTy.bool])
    | app τ' hargw hsτ' hdτ' hfn_ats harg_ats =>
      cases hwt with
      | app hfnw hargw' =>
        have hτeq := typing_deterministic hargw hargw'
        subst hτeq
        simp [termDepth] at hsize
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; left
        refine ⟨τ', (genLMonoTy_support tvars n τ').mpr ⟨hsτ', hdτ', sorry⟩,
               _, genLExpr_complete fctx octx tvars bctx n τ' hsτ' _ hargw' hnames.2 hvars.2 harg_ats (by omega),
               _, genLExpr_complete fctx octx tvars bctx n (.arrow τ' .int) (SimpleType.arrow hsτ' SimpleType.int) _ hfnw hnames.1 hvars.1 hfn_ats (by omega), rfl⟩
    | ite hc ht he_ =>
      cases hwt with
      | ite hcw htw hew =>
        simp [termDepth] at hsize
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; right; left
        refine ⟨_, genLExpr_complete fctx octx tvars bctx n .bool SimpleType.bool _ hcw hnames.1 hvars.1 hc (by omega),
               _, genLExpr_complete fctx octx tvars bctx n .int SimpleType.int _ htw hnames.2.1 hvars.2.1 ht (by omega),
               _, genLExpr_complete fctx octx tvars bctx n .int SimpleType.int _ hew hnames.2.2 hvars.2.2 he_ (by omega), rfl⟩
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; right; right; left; left
        have hlen : (bvarsOfType bctx .int).length > 0 := by
          have := (bvarsOfType_mem_iff bctx .int _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx .int _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx .int).length > 0 := by
          have := (fvarsOfType_mem_iff fctx .int _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx .int _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx .int).length > 0 := by
          have := (opsOfType_mem_iff octx .int _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx .int _ hmem hlen⟩
  | n + 1, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hats with
    | boolConst =>
      exact absurd (boolConst_hasType_bool hwt) (by intro h; simp [LMonoTy.bool, LMonoTy.arrow] at h)
    | intConst =>
      exact absurd (intConst_hasType_int hwt) (by intro h; simp [LMonoTy.int, LMonoTy.arrow] at h)
    | eq _ _ _ _ _ _ _ =>
      exact absurd (eq_hasType_bool hwt) (by intro h; simp [LMonoTy.bool, LMonoTy.arrow] at h)
    | quant _ _ _ _ _ _ _ _ =>
      exact absurd (quant_hasType_bool hwt) (by intro h; simp [LMonoTy.bool, LMonoTy.arrow] at h)
    | abs hsτ₁ hdτ₁ hbody_ats =>
      cases hwt with
      | abs hbody_wt =>
        simp [termDepth] at hsize
        simp only [emptyNames] at hnames
        left
        refine ⟨_, genLExpr_complete fctx octx tvars (τ₁ :: bctx) n τ₂ hs₂ _ hbody_wt
          hnames.2 hvars hbody_ats (by omega), rfl⟩
    | app τ' hargw hsτ' hdτ' hfn_ats harg_ats =>
      cases hwt with
      | app hfnw hargw' =>
        have hτeq := typing_deterministic hargw hargw'
        subst hτeq
        simp [termDepth] at hsize
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; left
        refine ⟨τ', (genLMonoTy_support tvars n τ').mpr ⟨hsτ', hdτ', sorry⟩,
               _, genLExpr_complete fctx octx tvars bctx n τ' hsτ' _ hargw' hnames.2 hvars.2 harg_ats (by omega),
               _, genLExpr_complete fctx octx tvars bctx n (.arrow τ' (.arrow τ₁ τ₂)) (SimpleType.arrow hsτ' (SimpleType.arrow hs₁ hs₂)) _ hfnw hnames.1 hvars.1 hfn_ats (by omega), rfl⟩
    | ite hc ht he_ =>
      cases hwt with
      | ite hcw htw hew =>
        simp [termDepth] at hsize
        simp only [emptyNames] at hnames
        simp only [allVarsInCtx] at hvars
        right; right; left
        refine ⟨_, genLExpr_complete fctx octx tvars bctx n .bool SimpleType.bool _ hcw hnames.1 hvars.1 hc (by omega),
               _, genLExpr_complete fctx octx tvars bctx n (.arrow τ₁ τ₂) (SimpleType.arrow hs₁ hs₂) _ htw hnames.2.1 hvars.2.1 ht (by omega),
               _, genLExpr_complete fctx octx tvars bctx n (.arrow τ₁ τ₂) (SimpleType.arrow hs₁ hs₂) _ hew hnames.2.2 hvars.2.2 he_ (by omega), rfl⟩
    | bvar =>
      cases hwt with
      | bvar hget =>
        right; right; right; left; left
        have hlen : (bvarsOfType bctx (.arrow τ₁ τ₂)).length > 0 := by
          have := (bvarsOfType_mem_iff bctx (.arrow τ₁ τ₂) _).mpr hget
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickBVar_complete bctx (.arrow τ₁ τ₂) _ hget hlen⟩
    | fvar =>
      cases hwt with
      | fvar =>
        right; right; right; right; left; left
        have hmem : (_, _) ∈ fctx := hvars
        have hlen : (fvarsOfType fctx (.arrow τ₁ τ₂)).length > 0 := by
          have := (fvarsOfType_mem_iff fctx (.arrow τ₁ τ₂) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickFVar_complete fctx (.arrow τ₁ τ₂) _ hmem hlen⟩
    | op =>
      cases hwt with
      | op =>
        right; right; right; right; right; left
        have hmem : (_, _) ∈ octx := hvars
        have hlen : (opsOfType octx (.arrow τ₁ τ₂)).length > 0 := by
          have := (opsOfType_mem_iff octx (.arrow τ₁ τ₂) _).mpr hmem
          exact List.length_pos_of_mem this
        exact ⟨hlen, pickOp_complete octx (.arrow τ₁ τ₂) _ hmem hlen⟩
  | 0, _, SimpleType.ftvar => sorry
  | n + 1, _, SimpleType.ftvar => sorry
  termination_by (size, sizeOf τ)
  decreasing_by all_goals simp_wf; omega

-- ── IsSoundAndComplete for genLMonoTy ─────────────────────────────────

/-- `genLMonoTy tvars n` is sound and complete with respect to
    `fun τ => SimpleType τ ∧ monoTyDepth τ ≤ n ∧ allFtvarsIn tvars τ`. -/
instance {tvars : List TyIdentifier} {n : Nat} :
    SetGen.IsSoundAndComplete
      (genLMonoTy (G := SetGen.Set) tvars n)
      (fun τ => SimpleType τ ∧ monoTyDepth τ ≤ n ∧ allFtvarsIn tvars τ) where
  support_iff τ := genLMonoTy_support tvars n τ

-- ── Quick test ────────────────────────────────────────────────────────

-- We need this `ToFormat` instance in order to pretty-print the generated `LExpr`s
-- before (since our metadata type is `Unit`)
open Std in
instance : ToFormat Unit where
  format _ := .nil

-- Print 5 randomly generated expressions
-- Some example generated exprs:
-- (if (if #true then #true else #true) then #true else #true)
-- ((λ (bvar:bool) #true) ((λ (bvar:bool) %0) #true))
#guard_msgs(drop warning) in
#eval (for _ in [:5] do
  IO.println <| Std.format (← genClosedLExpr [] 2) |>.pretty : IO Unit)

-- Test with a bound variable of type `ftvar "a"` to exercise the ftvar case
#guard_msgs(drop warning) in
#eval (for _ in [:5] do
  IO.println <| Std.format (← genLExpr [] [] ["a"] [.ftvar "a"] 2 (.ftvar "a")) |>.pretty : IO Unit)
