import Basalt
import Basalt.Examples.ArbNat
import Strata.DL.Lambda.LExprWF

open Lambda RandomChoice ArbNat SetGen

/-!
# Well-Typed LExpr Generator

A Basalt `SetGen`-based random generator for well-typed Strata `LExpr`s.
We work with the instantiation `P = LExprParams.mono ⟨Unit, Unit⟩` (unit
metadata and identifier-metadata, monotype annotations).

## Contents

- `WellTyped` — our typing judgement
- `SimpleType` — types generated by `genLMonoTy`
- `genLMonoTy` — generates simple mono-types (bool, int, arrow)
- `genLExpr` — generates well-typed `LExpr`s for a given type and depth
- Soundness of `genLExpr` (every generated expression is well-typed)
- `SetGen.IsSoundAndComplete` instance for `genLMonoTy`
-/

-- ── Parameter type ─────────────────────────────────────────────────────

/-- The `LExprParamsT` instantiation we use: unit metadata & IDMeta,
    `LMonoTy` as the type-annotation type. -/
abbrev P : LExprParamsT := LExprParams.mono ⟨Unit, Unit⟩

/-- Our working expression type. -/
abbrev ULExpr := LExpr P

instance : BEq LMonoTy := instBEqOfDecidableEq

-- ── Bound-variable context ─────────────────────────────────────────────

/-- De Bruijn context: `bctx[i]?` is the type of `bvar i`. -/
abbrev BVarCtx := List LMonoTy

-- ── Simple types ───────────────────────────────────────────────────────

/-- A type is *simple* if it is built only from `bool`, `int`, and `arrow`. -/
inductive SimpleType : LMonoTy → Prop where
  | bool  : SimpleType .bool
  | int   : SimpleType .int
  | arrow : SimpleType τ₁ → SimpleType τ₂ → SimpleType (.arrow τ₁ τ₂)

/-- Depth of a simple type. -/
def monoTyDepth : LMonoTy → Nat
  | .arrow τ₁ τ₂ => max (monoTyDepth τ₁) (monoTyDepth τ₂) + 1
  | _             => 0

-- ── Well-typing relation ───────────────────────────────────────────────

/-- Typing judgement `WellTyped bctx e τ`: expression `e` has type `τ`
    under bound-variable context `bctx`. -/
inductive WellTyped : BVarCtx → ULExpr → LMonoTy → Prop where
  | tBoolConst (b : Bool)  : WellTyped bctx (.boolConst () b) .bool
  | tIntConst  (n : Int)   : WellTyped bctx (.intConst () n) .int
  | tBVar      : bctx[i]? = some τ →
                 WellTyped bctx (.bvar () i) τ
  | tAbs       : WellTyped (τ₁ :: bctx) body τ₂ →
                 WellTyped bctx (.abs () "" (some τ₁) body) (.arrow τ₁ τ₂)
  | tApp       : WellTyped bctx fn (.arrow τ₁ τ₂) →
                 WellTyped bctx arg τ₁ →
                 WellTyped bctx (.app () fn arg) τ₂
  | tIte       : WellTyped bctx c .bool →
                 WellTyped bctx t τ →
                 WellTyped bctx e τ →
                 WellTyped bctx (.ite () c t e) τ
  | tEq        : WellTyped bctx e₁ τ →
                 WellTyped bctx e₂ τ →
                 WellTyped bctx (.eq () e₁ e₂) .bool
  | tQuantAll  : WellTyped (τ :: bctx) body .bool →
                 WellTyped bctx
                   (.quant () .all "" (some τ) (.bvar () 0) body) .bool
  | tQuantExist : WellTyped (τ :: bctx) body .bool →
                  WellTyped bctx
                    (.quant () .exist "" (some τ) (.bvar () 0) body) .bool

-- ── Bound-variable helpers ─────────────────────────────────────────────

/-- All de Bruijn indices in `bctx` whose type equals `τ`. -/
def bvarsOfType (bctx : BVarCtx) (τ : LMonoTy) : List Nat :=
  go bctx 0
where
  go : List LMonoTy → Nat → List Nat
    | [],         _  => []
    | τ' :: rest, i  => if τ' == τ then i :: go rest (i + 1) else go rest (i + 1)

/-- Pick a random `bvar` of type `τ` from `bctx`, given at least one exists. -/
def pickBVar [Gen G] (bctx : BVarCtx) (τ : LMonoTy)
    (_h : (bvarsOfType bctx τ).length > 0) : G ULExpr := do
  let indices := bvarsOfType bctx τ
  let idx ← choose 0 (indices.length - 1) (by omega)
  pure (.bvar () (indices.getD idx 0))

-- ── Type generator ─────────────────────────────────────────────────────

/-- Generate a simple type of depth ≤ `n`. -/
def genLMonoTy [Gen G] : Nat → G LMonoTy
  | 0 =>
    pick (fun () => pure .bool)
         (fun () => pure .int)
  | n + 1 =>
    pick
      (fun () => pure .bool)
      (fun () =>
        pick
          (fun () => pure .int)
          (fun () => do
            let τ₁ ← genLMonoTy n
            let τ₂ ← genLMonoTy n
            pure (.arrow τ₁ τ₂)))

-- ── Expression generator ───────────────────────────────────────────────

/-- Generate a well-typed `ULExpr` of type `τ` at depth ≤ `size` under
    bound-variable context `bctx`.

    No `resolve`/`resolve_aux` calls are made.
    Free variables (`fvar`) and `op` are not generated.
    For quantifiers the trigger is fixed to `bvar () 0`. -/
def genLExpr [Gen G] (bctx : BVarCtx) : Nat → LMonoTy → G ULExpr
  -- ── Arrow type ────────────────────────────────────────────────────
  | 0, .arrow τ₁ τ₂ =>
    let bvars := bvarsOfType bctx (.arrow τ₁ τ₂)
    if hv : bvars.length > 0 then
      pick (fun () => pickBVar bctx _ hv)
           (fun () => do
             let body ← genLExpr (τ₁ :: bctx) 0 τ₂
             pure (.abs () "" (some τ₁) body))
    else do
      let body ← genLExpr (τ₁ :: bctx) 0 τ₂
      pure (.abs () "" (some τ₁) body)
  | n + 1, .arrow τ₁ τ₂ =>
    pick
      (fun () => do
        let body ← genLExpr (τ₁ :: bctx) n τ₂
        pure (.abs () "" (some τ₁) body))
      (fun () =>
        pick
          (fun () => do
            let τ' ← genLMonoTy n
            let arg ← genLExpr bctx n τ'
            let fn  ← genLExpr bctx n (.arrow τ' (.arrow τ₁ τ₂))
            pure (.app () fn arg))
          (fun () => do
            let c ← genLExpr bctx n .bool
            let t ← genLExpr bctx n (.arrow τ₁ τ₂)
            let e ← genLExpr bctx n (.arrow τ₁ τ₂)
            pure (.ite () c t e)))
  -- ── Bool type ─────────────────────────────────────────────────────
  | 0, .bool =>
    let bvars := bvarsOfType bctx .bool
    if hv : bvars.length > 0 then
      pick (fun () => pure (.boolConst () true))
           (fun () => pickBVar bctx .bool hv)
    else
      pure (.boolConst () true)
  | n + 1, .bool =>
    let bvars := bvarsOfType bctx .bool
    pick
      (fun () => pure (.boolConst () true))
      (fun () =>
        pick
          (fun () => do
            let c ← genLExpr bctx n .bool
            let t ← genLExpr bctx n .bool
            let e ← genLExpr bctx n .bool
            pure (.ite () c t e))
          (fun () =>
            pick
              (fun () => do
                let τ' ← genLMonoTy n
                let e₁ ← genLExpr bctx n τ'
                let e₂ ← genLExpr bctx n τ'
                pure (.eq () e₁ e₂))
              (fun () =>
                pick
                  (fun () => do
                    let τ' ← genLMonoTy n
                    let arg ← genLExpr bctx n τ'
                    let fn  ← genLExpr bctx n (.arrow τ' .bool)
                    pure (.app () fn arg))
                  (fun () =>
                    pick
                      (fun () => do
                        let τ' ← genLMonoTy n
                        let body ← genLExpr (τ' :: bctx) n .bool
                        pure (.quant () .all "" (some τ') (.bvar () 0) body))
                      (fun () =>
                        if hv : bvars.length > 0 then
                          pickBVar bctx .bool hv
                        else do
                          let τ' ← genLMonoTy n
                          let body ← genLExpr (τ' :: bctx) n .bool
                          pure (.quant () .exist "" (some τ') (.bvar () 0) body))))))
  -- ── Int type ──────────────────────────────────────────────────────
  | 0, .int =>
    let bvars := bvarsOfType bctx .int
    if hv : bvars.length > 0 then
      pick (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
           (fun () => pickBVar bctx .int hv)
    else do
      let k ← Nat.arbitrary
      pure (.intConst () (k : Int))
  | n + 1, .int =>
    pick
      (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
      (fun () =>
        pick
          (fun () => do
            let τ' ← genLMonoTy n
            let arg ← genLExpr bctx n τ'
            let fn  ← genLExpr bctx n (.arrow τ' .int)
            pure (.app () fn arg))
          (fun () => do
            let c ← genLExpr bctx n .bool
            let t ← genLExpr bctx n .int
            let e ← genLExpr bctx n .int
            pure (.ite () c t e)))
  -- ── Fallback ──────────────────────────────────────────────────────
  | _, _ => pure (.boolConst () false)

/-- Generate a well-typed closed expression with bounded depth. -/
def ULExpr.gen [Gen G] (size : Nat) : G ULExpr := do
  let τ ← genLMonoTy size
  genLExpr [] size τ

-- ── bvarsOfType spec ──────────────────────────────────────────────────

private theorem bvarsOfType_go_spec (τ : LMonoTy) :
    ∀ (bctx : BVarCtx) (base i : Nat),
      i ∈ bvarsOfType.go τ bctx base ↔
        ∃ k, k < bctx.length ∧ i = base + k ∧ bctx[k]? = some τ := by
  intro bctx
  induction bctx with
  | nil => simp [bvarsOfType.go]
  | cons τ' rest ih =>
    intro base i
    simp only [bvarsOfType.go]
    split
    · rename_i heq
      have hτeq : τ' = τ := beq_iff_eq.mp heq
      simp only [List.mem_cons]; rw [ih]
      constructor
      · rintro (rfl | ⟨k, hk, rfl, hget⟩)
        · exact ⟨0, by simp, by omega, by simp [List.getElem?_cons_zero, hτeq]⟩
        · exact ⟨k + 1, by simp; omega, by omega,
            by simp [List.getElem?_cons_succ]; exact hget⟩
      · rintro ⟨k, hk, hx, hget⟩
        match k with
        | 0 => simp [List.getElem?_cons_zero] at hget; left; omega
        | k + 1 =>
          right; exact ⟨k, by simp at hk; omega, by omega,
            by simp [List.getElem?_cons_succ] at hget; exact hget⟩
    · rename_i heq
      have hτne : τ' ≠ τ := fun h => absurd (beq_iff_eq.mpr h) heq
      rw [ih]
      constructor
      · rintro ⟨k, hk, rfl, hget⟩
        exact ⟨k + 1, by simp; omega, by omega,
          by simp [List.getElem?_cons_succ]; exact hget⟩
      · rintro ⟨k, hk, hx, hget⟩
        match k with
        | 0 =>
          simp [List.getElem?_cons_zero] at hget
          exact absurd hget hτne
        | k + 1 =>
          exact ⟨k, by simp at hk; omega, by omega,
            by simp [List.getElem?_cons_succ] at hget; exact hget⟩

private theorem bvarsOfType_mem_iff (bctx : BVarCtx) (τ : LMonoTy) (i : Nat) :
    i ∈ bvarsOfType bctx τ ↔ bctx[i]? = some τ := by
  unfold bvarsOfType
  rw [bvarsOfType_go_spec]
  constructor
  · rintro ⟨k, _, rfl, hget⟩; simpa using hget
  · intro hget
    have hlt : i < bctx.length := by
      rw [List.getElem?_eq_some_iff] at hget; exact hget.1
    exact ⟨i, hlt, by omega, hget⟩

-- ── pickBVar soundness/completeness ───────────────────────────────────

private theorem pickBVar_sound (bctx : BVarCtx) (τ : LMonoTy)
    (hv : (bvarsOfType bctx τ).length > 0) (e : ULExpr)
    (he : e ∈ SetGen.support (pickBVar (G := SetGen.Set) bctx τ hv)) :
    WellTyped bctx e τ := by
  simp only [pickBVar, mem_support_iff, Set.mem_bind, Set.mem_pure,
             mem_support_choose_iff] at he
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := he
  subst heq
  apply WellTyped.tBVar
  rw [← bvarsOfType_mem_iff]
  set indices := bvarsOfType bctx τ
  have hlt : idx < indices.length := by omega
  have : indices.getD idx 0 = indices[idx] := by
    simp [List.getD, List.getElem?_eq_getElem hlt]
  rw [this]
  exact List.getElem_mem hlt

private theorem pickBVar_complete (bctx : BVarCtx) (τ : LMonoTy) (i : Nat)
    (hget : bctx[i]? = some τ)
    (hv : (bvarsOfType bctx τ).length > 0) :
    .bvar () i ∈ SetGen.support (pickBVar (G := SetGen.Set) bctx τ hv) := by
  simp only [pickBVar, mem_support_iff, Set.mem_bind, Set.mem_pure,
             mem_support_choose_iff]
  have hmem : i ∈ bvarsOfType bctx τ := (bvarsOfType_mem_iff bctx τ i).mpr hget
  obtain ⟨idx, hidx_lt, hidx_eq⟩ := List.getElem_of_mem hmem
  refine ⟨idx, ⟨Nat.zero_le _, by omega⟩, ?_⟩
  simp [List.getD, List.getElem?_eq_getElem hidx_lt, hidx_eq]

-- ── genLMonoTy support ────────────────────────────────────────────────

/-- `genLMonoTy n` generates exactly the simple types of depth ≤ `n`. -/
theorem genLMonoTy_support (n : Nat) (τ : LMonoTy) :
    τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) n) ↔
      SimpleType τ ∧ monoTyDepth τ ≤ n := by
  induction n generalizing τ with
  | zero =>
    simp only [genLMonoTy, mem_support_pick_iff, mem_support_pure_iff]
    constructor
    · rintro (rfl | rfl)
      · exact ⟨.bool, le_refl _⟩
      · exact ⟨.int, le_refl _⟩
    · intro ⟨hs, _⟩
      cases hs with
      | bool  => left; rfl
      | int   => right; rfl
      | arrow => simp [monoTyDepth, LMonoTy.arrow] at *
  | succ n ih =>
    simp only [genLMonoTy, mem_support_pick_iff, mem_support_pure_iff,
               mem_support_bind_iff]
    constructor
    · rintro (rfl | rfl | ⟨τ₁, h₁, τ₂, h₂, heq⟩)
      · exact ⟨.bool, Nat.zero_le _⟩
      · exact ⟨.int, Nat.zero_le _⟩
      · subst heq
        have ⟨hs₁, hd₁⟩ := (ih τ₁).mp h₁
        have ⟨hs₂, hd₂⟩ := (ih τ₂).mp h₂
        exact ⟨.arrow hs₁ hs₂, by simp [monoTyDepth, LMonoTy.arrow]; omega⟩
    · intro ⟨hs, hd⟩
      cases hs with
      | bool  => left; rfl
      | int   => right; left; rfl
      | arrow τ₁ τ₂ hs₁ hs₂ =>
        right; right
        have hd' : monoTyDepth (.arrow τ₁ τ₂) ≤ n + 1 := hd
        simp only [monoTyDepth, LMonoTy.arrow] at hd'
        exact ⟨τ₁, (ih τ₁).mpr ⟨hs₁, by omega⟩,
               τ₂, (ih τ₂).mpr ⟨hs₂, by omega⟩, rfl⟩

/-- Corollary: anything generated by `genLMonoTy` is a `SimpleType`. -/
theorem genLMonoTy_simple (n : Nat) (τ : LMonoTy)
    (h : τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) n)) : SimpleType τ :=
  ((genLMonoTy_support n τ).mp h).1

-- ── Soundness for genLExpr ────────────────────────────────────────────

/-- Every expression in the support of `genLExpr bctx size τ` is
    well-typed whenever `τ` is a `SimpleType`. -/
theorem genLExpr_sound (bctx : BVarCtx) (size : Nat) (τ : LMonoTy)
    (hτ : SimpleType τ) (e : ULExpr)
    (he : e ∈ SetGen.support (genLExpr (G := SetGen.Set) bctx size τ)) :
    WellTyped bctx e τ := by
  induction size generalizing bctx τ e with
  | zero =>
    cases hτ with
    | bool =>
      simp only [genLExpr] at he
      split at he
      · simp only [mem_support_pick_iff, mem_support_pure_iff] at he
        cases he with
        | inl h => subst h; exact .tBoolConst true
        | inr h => exact pickBVar_sound bctx .bool _ _ h
      · simp only [mem_support_pure_iff] at he; subst he; exact .tBoolConst true
    | int =>
      simp only [genLExpr] at he
      split at he
      · simp only [mem_support_pick_iff, mem_support_bind_iff,
                   mem_support_pure_iff] at he
        cases he with
        | inl h => obtain ⟨k, _, heq⟩ := h; subst heq; exact .tIntConst _
        | inr h => exact pickBVar_sound bctx .int _ _ h
      · simp only [mem_support_bind_iff, mem_support_pure_iff] at he
        obtain ⟨k, _, heq⟩ := he; subst heq; exact .tIntConst _
    | arrow τ₁ τ₂ hτ₁ hτ₂ =>
      simp only [genLExpr] at he
      split at he
      · simp only [mem_support_pick_iff, mem_support_bind_iff,
                   mem_support_pure_iff] at he
        cases he with
        | inl h => exact pickBVar_sound bctx _ _ _ h
        | inr h =>
          obtain ⟨body, hbody, heq⟩ := h; subst heq
          exact .tAbs (ih (τ₁ :: bctx) body hbody)
      · simp only [mem_support_bind_iff, mem_support_pure_iff] at he
        obtain ⟨body, hbody, heq⟩ := he; subst heq
        exact .tAbs (ih (τ₁ :: bctx) body hbody)
  | succ n ih =>
    cases hτ with
    | bool =>
      simp only [genLExpr, mem_support_pick_iff, mem_support_bind_iff,
                 mem_support_pure_iff] at he
      rcases he with h | h | h | h | h | h
      · subst h; exact .tBoolConst true
      · obtain ⟨c, hc, t, ht, e', he', heq⟩ := h; subst heq
        exact .tIte (ih bctx c hc) (ih bctx t ht) (ih bctx e' he')
      · obtain ⟨τ', hτ'mem, e₁, he₁, e₂, he₂, heq⟩ := h; subst heq
        exact .tEq (ih bctx e₁ he₁) (ih bctx e₂ he₂)
      · obtain ⟨τ', hτ'mem, arg, harg, fn, hfn, heq⟩ := h; subst heq
        exact .tApp (ih bctx fn hfn) (ih bctx arg harg)
      · obtain ⟨τ', hτ'mem, body, hbody, heq⟩ := h; subst heq
        have hτ'simple := genLMonoTy_simple n τ' hτ'mem
        exact .tQuantAll (ih (τ' :: bctx) body hbody)
      · rcases h with ⟨hv, h⟩ | ⟨_, τ', hτ'mem, body, hbody, heq⟩
        · exact pickBVar_sound bctx .bool hv _ h
        · subst heq
          have hτ'simple := genLMonoTy_simple n τ' hτ'mem
          exact .tQuantExist (ih (τ' :: bctx) body hbody)
    | int =>
      simp only [genLExpr, mem_support_pick_iff, mem_support_bind_iff,
                 mem_support_pure_iff] at he
      rcases he with h | h | h
      · obtain ⟨k, _, heq⟩ := h; subst heq; exact .tIntConst _
      · obtain ⟨τ', hτ'mem, arg, harg, fn, hfn, heq⟩ := h; subst heq
        exact .tApp (ih bctx fn hfn) (ih bctx arg harg)
      · obtain ⟨c, hc, t, ht, e', he', heq⟩ := h; subst heq
        exact .tIte (ih bctx c hc) (ih bctx t ht) (ih bctx e' he')
    | arrow τ₁ τ₂ hτ₁ hτ₂ =>
      simp only [genLExpr, mem_support_pick_iff, mem_support_bind_iff,
                 mem_support_pure_iff] at he
      rcases he with h | h | h
      · obtain ⟨body, hbody, heq⟩ := h; subst heq
        exact .tAbs (ih (τ₁ :: bctx) body hbody)
      · obtain ⟨τ', hτ'mem, arg, harg, fn, hfn, heq⟩ := h; subst heq
        exact .tApp (ih bctx fn hfn) (ih bctx arg harg)
      · obtain ⟨c, hc, t, ht, e', he', heq⟩ := h; subst heq
        exact .tIte (ih bctx c hc) (ih bctx t ht) (ih bctx e' he')

-- ── IsSoundAndComplete for genLMonoTy ─────────────────────────────────

/-- `genLMonoTy n` is sound and complete with respect to
    `fun τ => SimpleType τ ∧ monoTyDepth τ ≤ n`. -/
instance {n : Nat} :
    SetGen.IsSoundAndComplete
      (genLMonoTy (G := SetGen.Set) n)
      (fun τ => SimpleType τ ∧ monoTyDepth τ ≤ n) where
  support_iff τ := genLMonoTy_support n τ

-- ── Quick test ────────────────────────────────────────────────────────

#guard_msgs(drop info) in
#eval (for _ in [:10] do
  IO.println <| repr (← ULExpr.gen 2) : IO Unit)
