import StrataGenerators.SetGen
import Basalt.Examples.ArbNat
import Strata.DL.Lambda.Denote.LExprAnnotated

open Lambda RandomChoice ArbNat SetGen

/-!
# Well-Typed LExpr Generator

A Basalt `SetGen`-based random generator for well-typed Strata `LExpr`s.
We work with the instantiation `P = LExprParams.mono ⟨Unit, Unit⟩` (unit
metadata and identifier-metadata, monotype annotations).

## Contents

- `HasTypeA'` — the typing judgement `HasTypeA`, with `LExprParams` instantiated
- `SimpleType` — types generated by `genLMonoTy`
- `genLMonoTy` — generates simple mono-types (bool, int, arrow)
- `genLExpr` — generates well-typed `LExpr`s for a given type and depth
- Soundness of `genLExpr` (every generated expression is well-typed)
- `SetGen.IsSoundAndComplete` instance for `genLMonoTy`
-/

-- ── Parameter type ─────────────────────────────────────────────────────

/-- The base `LExprParams` we use: unit metadata & IDMeta. -/
abbrev Pbase : LExprParams := ⟨Unit, Unit⟩

/-- The `LExprParamsT` instantiation we use: unit metadata & IDMeta,
    `LMonoTy` as the type-annotation type. -/
abbrev P : LExprParamsT := LExprParams.mono Pbase

instance : DecidableEq Unit := instDecidableEqPUnit

/-- Our working expression type. -/
abbrev ULExpr := LExpr P

instance : BEq LMonoTy := instBEqOfDecidableEq

-- ── Bound-variable context ─────────────────────────────────────────────

/-- De Bruijn context: `bctx[i]?` is the type of `bvar i`. -/
abbrev BVarCtx := List LMonoTy

-- ── Simple types ───────────────────────────────────────────────────────

/-- A type is *simple* if it is built only from `bool`, `int`, and `arrow`. -/
inductive SimpleType : LMonoTy → Prop where
  | bool  : SimpleType .bool
  | int   : SimpleType .int
  | arrow : SimpleType τ₁ → SimpleType τ₂ → SimpleType (.arrow τ₁ τ₂)

/-- Depth of a simple type. -/
def monoTyDepth : LMonoTy → Nat
  | .arrow τ₁ τ₂ => max (monoTyDepth τ₁) (monoTyDepth τ₂) + 1
  | _             => 0

-- ── Well-typing relation ───────────────────────────────────────────────

/-- We use Strata's `LExpr.HasTypeA` directly as our typing judgement.
    `HasTypeA Δ e τ` means expression `e` has type `τ` under bound-variable
    context `Δ` (a `List LMonoTy` indexed by de Bruijn level). -/
abbrev HasTypeA' := LExpr.HasTypeA (T := Pbase)

-- ── Bound-variable helpers ─────────────────────────────────────────────

/-- All de Bruijn indices in `bctx` whose type equals `τ`. -/
def bvarsOfType (bctx : BVarCtx) (τ : LMonoTy) : List Nat :=
  go bctx 0
where
  go : List LMonoTy → Nat → List Nat
    | [],         _  => []
    | τ' :: rest, i  => if τ' == τ then i :: go rest (i + 1) else go rest (i + 1)

/-- Pick a random `bvar` of type `τ` from `bctx`, given at least one exists. -/
def pickBVar [Gen G] (bctx : BVarCtx) (τ : LMonoTy)
    (_h : (bvarsOfType bctx τ).length > 0) : G ULExpr := do
  let indices := bvarsOfType bctx τ
  let idx ← choose 0 (indices.length - 1) (by omega)
  pure (.bvar () (indices.getD idx.down 0))

-- ── Type generator ─────────────────────────────────────────────────────

/-- Generate a simple type of depth ≤ `n`. -/
def genLMonoTy [Gen G] : Nat → G LMonoTy
  | 0 =>
    pick (fun () => pure .bool)
         (fun () => pure .int)
  | n + 1 =>
    pick
      (fun () => pure .bool)
      (fun () =>
        pick
          (fun () => pure .int)
          (fun () => do
            let τ₁ ← genLMonoTy n
            let τ₂ ← genLMonoTy n
            pure (.arrow τ₁ τ₂)))

-- ── Expression generator ───────────────────────────────────────────────

/-- Generate a well-typed `ULExpr` of type `τ` at depth ≤ `size` under
    bound-variable context `bctx`.

    No `resolve`/`resolve_aux` calls are made.
    Free variables (`fvar`) and `op` are not generated.
    Names are always `""`. Triggers are arbitrary well-typed expressions. -/
def genLExpr [Gen G] (bctx : BVarCtx) : Nat → LMonoTy → G ULExpr
  -- ── Arrow type ────────────────────────────────────────────────────
  | 0, .arrow τ₁ τ₂ =>
    let bvars := bvarsOfType bctx (.arrow τ₁ τ₂)
    if hv : bvars.length > 0 then
      pick (fun () => pickBVar bctx _ hv)
           (fun () => do
             let body ← genLExpr (τ₁ :: bctx) 0 τ₂
             pure (.abs () "" (some τ₁) body))
    else do
      let body ← genLExpr (τ₁ :: bctx) 0 τ₂
      pure (.abs () "" (some τ₁) body)
  | n + 1, .arrow τ₁ τ₂ =>
    let bvars := bvarsOfType bctx (.arrow τ₁ τ₂)
    pick
      (fun () => do
        let body ← genLExpr (τ₁ :: bctx) n τ₂
        pure (.abs () "" (some τ₁) body))
      (fun () =>
        pick
          (fun () => do
            let τ' ← genLMonoTy n
            let arg ← genLExpr bctx n τ'
            let fn  ← genLExpr bctx n (.arrow τ' (.arrow τ₁ τ₂))
            pure (.app () fn arg))
          (fun () =>
            pick
              (fun () => do
                let c ← genLExpr bctx n .bool
                let t ← genLExpr bctx n (.arrow τ₁ τ₂)
                let e ← genLExpr bctx n (.arrow τ₁ τ₂)
                pure (.ite () c t e))
              (fun () =>
                if hv : bvars.length > 0 then
                  pickBVar bctx _ hv
                else do
                  let body ← genLExpr (τ₁ :: bctx) n τ₂
                  pure (.abs () "" (some τ₁) body))))
  -- ── Bool type ─────────────────────────────────────────────────────
  | 0, .bool =>
    let bvars := bvarsOfType bctx .bool
    if hv : bvars.length > 0 then
      pick (fun () =>
        pick (fun () => pure (.boolConst () true))
             (fun () => pure (.boolConst () false)))
           (fun () => pickBVar bctx .bool hv)
    else
      pick (fun () => pure (.boolConst () true))
           (fun () => pure (.boolConst () false))
  | n + 1, .bool =>
    let bvars := bvarsOfType bctx .bool
    pick
      (fun () =>
        pick (fun () => pure (.boolConst () true))
             (fun () => pure (.boolConst () false)))
      (fun () =>
        pick
          (fun () => do
            let c ← genLExpr bctx n .bool
            let t ← genLExpr bctx n .bool
            let e ← genLExpr bctx n .bool
            pure (.ite () c t e))
          (fun () =>
            pick
              (fun () => do
                let τ' ← genLMonoTy n
                let e₁ ← genLExpr bctx n τ'
                let e₂ ← genLExpr bctx n τ'
                pure (.eq () e₁ e₂))
              (fun () =>
                pick
                  (fun () => do
                    let τ' ← genLMonoTy n
                    let arg ← genLExpr bctx n τ'
                    let fn  ← genLExpr bctx n (.arrow τ' .bool)
                    pure (.app () fn arg))
                  (fun () =>
                    pick
                      (fun () => do
                        let τ' ← genLMonoTy n
                        let τ_tr ← genLMonoTy n
                        let tr ← genLExpr (τ' :: bctx) n τ_tr
                        let body ← genLExpr (τ' :: bctx) n .bool
                        pure (.quant () .all "" (some τ') tr body))
                      (fun () =>
                        pick
                          (fun () => do
                            let τ' ← genLMonoTy n
                            let τ_tr ← genLMonoTy n
                            let tr ← genLExpr (τ' :: bctx) n τ_tr
                            let body ← genLExpr (τ' :: bctx) n .bool
                            pure (.quant () .exist "" (some τ') tr body))
                          (fun () =>
                            if hv : bvars.length > 0 then
                              pickBVar bctx .bool hv
                            else
                              pick (fun () => pure (.boolConst () true))
                                   (fun () => pure (.boolConst () false))))))))
  -- ── Int type ──────────────────────────────────────────────────────
  | 0, .int =>
    let bvars := bvarsOfType bctx .int
    if hv : bvars.length > 0 then
      pick (fun () =>
        pick
          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))
           (fun () => pickBVar bctx .int hv)
    else
      pick
        (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
        (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int))))
  | n + 1, .int =>
    let bvars := bvarsOfType bctx .int
    pick
      (fun () =>
        pick
          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
          (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))
      (fun () =>
        pick
          (fun () => do
            let τ' ← genLMonoTy n
            let arg ← genLExpr bctx n τ'
            let fn  ← genLExpr bctx n (.arrow τ' .int)
            pure (.app () fn arg))
          (fun () =>
            pick
              (fun () => do
                let c ← genLExpr bctx n .bool
                let t ← genLExpr bctx n .int
                let e ← genLExpr bctx n .int
                pure (.ite () c t e))
              (fun () =>
                if hv : bvars.length > 0 then
                  pickBVar bctx _ hv
                else
                  pick
                    (fun () => do let k ← Nat.arbitrary; pure (.intConst () (k : Int)))
                    (fun () => do let k ← Nat.arbitrary; pure (.intConst () (-(↑k + 1 : Int)))))))
  -- ── Fallback ──────────────────────────────────────────────────────
  | _, _ => pure (.boolConst () false)

/-- Generate a well-typed closed expression with bounded depth. -/
def ULExpr.gen [Gen G] (size : Nat) : G ULExpr := do
  let τ ← genLMonoTy size
  genLExpr [] size τ

-- ── bvarsOfType spec ──────────────────────────────────────────────────

private theorem bvarsOfType_go_spec (τ : LMonoTy) :
    ∀ (bctx : BVarCtx) (base i : Nat),
      i ∈ bvarsOfType.go τ bctx base ↔
        ∃ k, k < bctx.length ∧ i = base + k ∧ bctx[k]? = some τ := by
  intro bctx
  induction bctx with
  | nil => simp [bvarsOfType.go]
  | cons τ' rest ih =>
    intro base i
    simp only [bvarsOfType.go]
    split
    · rename_i heq
      have hτeq : τ' = τ := beq_iff_eq.mp heq
      simp only [List.mem_cons]; rw [ih]
      constructor
      · rintro (rfl | ⟨k, hk, rfl, hget⟩)
        · exact ⟨0, by simp, by omega, by simp [hτeq]⟩
        · exact ⟨k + 1, by simp; omega, by omega,
            by simp [List.getElem?_cons_succ]; exact hget⟩
      · rintro ⟨k, hk, hx, hget⟩
        match k with
        | 0 => simp at hget; left; omega
        | k + 1 =>
          right; exact ⟨k, by simp at hk; omega, by omega,
            by simp [List.getElem?_cons_succ] at hget; exact hget⟩
    · rename_i heq
      have hτne : τ' ≠ τ := fun h => absurd (beq_iff_eq.mpr h) heq
      rw [ih]
      constructor
      · rintro ⟨k, hk, rfl, hget⟩
        exact ⟨k + 1, by simp; omega, by omega,
          by simp [List.getElem?_cons_succ]; exact hget⟩
      · rintro ⟨k, hk, hx, hget⟩
        match k with
        | 0 =>
          simp at hget
          exact absurd hget hτne
        | k + 1 =>
          exact ⟨k, by simp at hk; omega, by omega,
            by simp [List.getElem?_cons_succ] at hget; exact hget⟩

private theorem bvarsOfType_mem_iff (bctx : BVarCtx) (τ : LMonoTy) (i : Nat) :
    i ∈ bvarsOfType bctx τ ↔ bctx[i]? = some τ := by
  unfold bvarsOfType
  rw [bvarsOfType_go_spec]
  constructor
  · rintro ⟨k, _, rfl, hget⟩; simpa using hget
  · intro hget
    have hlt : i < bctx.length := by
      rw [List.getElem?_eq_some_iff] at hget; exact hget.1
    exact ⟨i, hlt, by omega, hget⟩

-- ── pickBVar soundness/completeness ───────────────────────────────────

private theorem pickBVar_sound (bctx : BVarCtx) (τ : LMonoTy)
    (hv : (bvarsOfType bctx τ).length > 0) (e : ULExpr)
    (he : e ∈ SetGen.support (pickBVar (G := SetGen.Set) bctx τ hv)) :
    HasTypeA' bctx e τ := by
  simp only [pickBVar, mem_support_iff, Set.mem_bind, Set.mem_pure] at he
  obtain ⟨idx, ⟨_, hhi⟩, heq⟩ := he
  subst heq
  apply LExpr.HasTypeA.bvar
  rw [← bvarsOfType_mem_iff]
  set indices := bvarsOfType bctx τ
  have hlt : idx.down < indices.length := by omega
  have : indices.getD idx.down 0 = indices[idx.down] := by
    simp [List.getD, List.getElem?_eq_getElem hlt]
  rw [this]
  exact List.getElem_mem hlt

private theorem pickBVar_complete (bctx : BVarCtx) (τ : LMonoTy) (i : Nat)
    (hget : bctx[i]? = some τ)
    (hv : (bvarsOfType bctx τ).length > 0) :
    .bvar () i ∈ SetGen.support (pickBVar (G := SetGen.Set) bctx τ hv) := by
  simp only [pickBVar, mem_support_iff, Set.mem_bind, Set.mem_pure]
  have hmem : i ∈ bvarsOfType bctx τ := (bvarsOfType_mem_iff bctx τ i).mpr hget
  obtain ⟨idx, hidx_lt, hidx_eq⟩ := List.getElem_of_mem hmem
  have : idx ≤ (bvarsOfType bctx τ).length - 1 := by omega
  refine ⟨⟨idx⟩, ⟨Nat.zero_le _, this⟩, ?_⟩
  simp [List.getD, List.getElem?_eq_getElem hidx_lt, hidx_eq]

-- ── genLMonoTy support ────────────────────────────────────────────────

/-- `genLMonoTy n` generates exactly the simple types of depth ≤ `n`. -/
theorem genLMonoTy_support (n : Nat) (τ : LMonoTy) :
    τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) n) ↔
      SimpleType τ ∧ monoTyDepth τ ≤ n := by
  induction n generalizing τ with
  | zero =>
    simp only [genLMonoTy, mem_support_pick_iff, mem_support_pure_iff]
    constructor
    · rintro (rfl | rfl)
      · exact ⟨.bool, le_refl _⟩
      · exact ⟨.int, le_refl _⟩
    · intro ⟨hs, hd⟩
      cases hs with
      | bool  => left; rfl
      | int   => right; rfl
      | arrow =>
        rename_i τ₁ τ₂ _ _
        have hd' : monoTyDepth (.tcons "arrow" [τ₁, τ₂]) ≤ 0 := hd
        rw [monoTyDepth.eq_1] at hd'; omega
  | succ n ih =>
    simp only [genLMonoTy, mem_support_pick_iff, mem_support_pure_iff,
               mem_support_bind_iff]
    constructor
    · rintro (rfl | rfl | ⟨τ₁, h₁, τ₂, h₂, heq⟩)
      · exact ⟨.bool, Nat.zero_le _⟩
      · exact ⟨.int, Nat.zero_le _⟩
      · subst heq
        have ⟨hs₁, hd₁⟩ := (ih τ₁).mp h₁
        have ⟨hs₂, hd₂⟩ := (ih τ₂).mp h₂
        refine ⟨.arrow hs₁ hs₂, ?_⟩
        change monoTyDepth (.tcons "arrow" [τ₁, τ₂]) ≤ n + 1
        rw [monoTyDepth.eq_1]; omega
    · intro ⟨hs, hd⟩
      cases hs with
      | bool  => left; rfl
      | int   => right; left; rfl
      | arrow hs₁ hs₂ =>
        rename_i τ₁ τ₂
        right; right
        have hd' : monoTyDepth (.tcons "arrow" [τ₁, τ₂]) ≤ n + 1 := hd
        rw [monoTyDepth.eq_1] at hd'
        exact ⟨τ₁, (ih τ₁).mpr ⟨hs₁, by omega⟩,
               τ₂, (ih τ₂).mpr ⟨hs₂, by omega⟩, rfl⟩

/-- Corollary: anything generated by `genLMonoTy` is a `SimpleType`. -/
theorem genLMonoTy_simple (n : Nat) (τ : LMonoTy)
    (h : τ ∈ SetGen.support (genLMonoTy (G := SetGen.Set) n)) : SimpleType τ :=
  ((genLMonoTy_support n τ).mp h).1

-- ── Soundness for genLExpr ────────────────────────────────────────────

-- `LMonoTy.bool`, `.int`, `.arrow` are abbreviations for `.tcons "bool" []` etc.
-- In Strata, they're defined as abbreviations via the `abbrev` keyword,
-- e.g. `abbrev LMonoTy.arrow τ₁ τ₂ := .tcons "arrow" [τ₁, τ₂]`.
-- Now, when we define `genLExpr` via pattern-matching,
-- Lean's automatically generated equational lemmas are defined in terms of the expanded constructor,
-- i.e. `LmonoTy.tcons "arrow" [τ₁, τ₂]` instead of `LMonoTy.arrow τ₁ τ₂`.
-- Thus, when we have a hypothesis that mentions `genLExpr`, e.g. `he : e ∈ support (genLExpr bctx 0 (LMonoTy.arrow τ₁ τ₂))`,
-- when we try to naively do `simp only [genLExpr]`,
-- Lean tries to match `LMonoTy.tcons "arrow" [τ₁, τ₂]` against the subterm `LMonoTy.arrow τ₁ τ₂` in the hypothesis.
-- Even though the two terms are definitionally equal, the `simp/rw` tactics require syntactic equality,
-- so we have to add the following rewrite lemmas which normalize the abbreviation,
-- so that the equation lemmas cna match.
private theorem norm_bool : LMonoTy.bool = LMonoTy.tcons "bool" [] := rfl
private theorem norm_int : LMonoTy.int = LMonoTy.tcons "int" [] := rfl
private theorem norm_arrow (τ₁ τ₂ : LMonoTy) :
    LMonoTy.arrow τ₁ τ₂ = LMonoTy.tcons "arrow" [τ₁, τ₂] := rfl


/-- Every expression in the support of `genLExpr bctx size τ` is
    well-typed whenever `τ` is a `SimpleType`. -/
theorem genLExpr_sound (bctx : BVarCtx) (size : Nat) (τ : LMonoTy)
    (hτ : SimpleType τ) (e : ULExpr)
    (he : e ∈ SetGen.support (genLExpr (G := SetGen.Set) bctx size τ)) :
    HasTypeA' bctx e τ := by
  match size, τ, hτ with
  | 0, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite] at he
    rcases he with ⟨_, (rfl | rfl) | h⟩ | ⟨_, rfl | rfl⟩
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact pickBVar_sound bctx .bool _ _ h
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact (by unfold LExpr.boolConst; exact .const)
  | 0, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite] at he
    rcases he with ⟨_, (⟨k, _, rfl⟩ | ⟨k, _, rfl⟩) | h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩
    · exact (by unfold LExpr.intConst; exact .const)
    · exact (by unfold LExpr.intConst; exact .const)
    · exact pickBVar_sound bctx .int _ _ h
    · exact (by unfold LExpr.intConst; exact .const)
    · exact (by unfold LExpr.intConst; exact .const)
  | 0, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite] at he
    rcases he with ⟨_, h | ⟨body, hbody, rfl⟩⟩ | ⟨_, body, hbody, rfl⟩
    · exact pickBVar_sound bctx _ _ _ h
    · exact .abs (genLExpr_sound (τ₁ :: bctx) 0 τ₂ hs₂ _ hbody)
    · exact .abs (genLExpr_sound (τ₁ :: bctx) 0 τ₂ hs₂ _ hbody)
  | n + 1, _, SimpleType.bool =>
    rw [norm_bool] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite] at he
    rcases he with (rfl | rfl) | ⟨c, hc, t, ht, e', he', rfl⟩ | ⟨τ', hτ'm, e₁, he₁, e₂, he₂, rfl⟩ |
      ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ⟨τ', hτ'm, τ_tr, hτ_tr_m, tr, htr, body, hbody, rfl⟩ |
      ⟨_, h⟩ | ⟨_, rfl | rfl⟩
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact .ite (genLExpr_sound bctx n _ SimpleType.bool _ hc)
                  (genLExpr_sound bctx n _ SimpleType.bool _ ht)
                  (genLExpr_sound bctx n _ SimpleType.bool _ he')
    · exact .eq (genLExpr_sound bctx n _ (genLMonoTy_simple n _ hτ'm) _ he₁)
                 (genLExpr_sound bctx n _ (genLMonoTy_simple n _ hτ'm) _ he₂)
    · exact .app (genLExpr_sound bctx n _ (SimpleType.arrow (genLMonoTy_simple n _ hτ'm) SimpleType.bool) _ hfn)
                  (genLExpr_sound bctx n _ (genLMonoTy_simple n _ hτ'm) _ harg)
    · exact .quant (genLExpr_sound (τ' :: bctx) n _ (genLMonoTy_simple n _ hτ_tr_m) _ htr)
                    (genLExpr_sound (τ' :: bctx) n _ SimpleType.bool _ hbody)
    · exact .quant (genLExpr_sound (τ' :: bctx) n _ (genLMonoTy_simple n _ hτ_tr_m) _ htr)
                    (genLExpr_sound (τ' :: bctx) n _ SimpleType.bool _ hbody)
    · exact pickBVar_sound bctx .bool _ _ h
    · exact (by unfold LExpr.boolConst; exact .const)
    · exact (by unfold LExpr.boolConst; exact .const)
  | n + 1, _, SimpleType.int =>
    rw [norm_int] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with (⟨k, _, rfl⟩ | ⟨k, _, rfl⟩) | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ | ⟨_, h⟩ | ⟨_, ⟨k, _, rfl⟩ | ⟨k, _, rfl⟩⟩
    · exact (by unfold LExpr.intConst; exact .const)
    · exact (by unfold LExpr.intConst; exact .const)
    · exact .app (genLExpr_sound bctx n _ (SimpleType.arrow (genLMonoTy_simple n _ hτ'm) SimpleType.int) _ hfn)
                  (genLExpr_sound bctx n _ (genLMonoTy_simple n _ hτ'm) _ harg)
    · exact .ite (genLExpr_sound bctx n _ SimpleType.bool _ hc)
                  (genLExpr_sound bctx n _ SimpleType.int _ ht)
                  (genLExpr_sound bctx n _ SimpleType.int _ he')
    · exact pickBVar_sound bctx .int _ _ h
    · exact (by unfold LExpr.intConst; exact .const)
    · exact (by unfold LExpr.intConst; exact .const)
  | n + 1, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow] at he; simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind,
      SetGen.Set.mem_pure, mem_support_iff, SetGen.mem_dite] at he
    rcases he with ⟨body, hbody, rfl⟩ | ⟨τ', hτ'm, arg, harg, fn, hfn, rfl⟩ |
      ⟨c, hc, t, ht, e', he', rfl⟩ | ⟨_, h⟩ | ⟨_, body, hbody, rfl⟩
    · exact .abs (genLExpr_sound (τ₁ :: bctx) n _ hs₂ _ hbody)
    · exact .app (genLExpr_sound bctx n _ (SimpleType.arrow (genLMonoTy_simple n _ hτ'm) (SimpleType.arrow hs₁ hs₂)) _ hfn)
                  (genLExpr_sound bctx n _ (genLMonoTy_simple n _ hτ'm) _ harg)
    · exact .ite (genLExpr_sound bctx n _ SimpleType.bool _ hc)
                  (genLExpr_sound bctx n _ (SimpleType.arrow hs₁ hs₂) _ ht)
                  (genLExpr_sound bctx n _ (SimpleType.arrow hs₁ hs₂) _ he')
    · exact pickBVar_sound bctx _ _ _ h
    · exact .abs (genLExpr_sound (τ₁ :: bctx) n _ hs₂ _ hbody)
  termination_by (size, sizeOf τ)
  decreasing_by all_goals simp_wf; first | omega | simp_all [LMonoTy.arrow]; omega

-- ── Nat.arbitrary support for SetGen.Set ──────────────────────────────

/-- Every natural number is in the support of `Nat.arbitrary` at `SetGen.Set`. -/
private theorem Nat_arbitrary_support_set (n : Nat) :
    n ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)) := by
  induction n with
  | zero =>
    simp only [SetGen.support]
    rw [Nat.arbitrary]
    simp [pick_mem_iff]
  | succ n ih =>
    simp only [SetGen.support] at ih ⊢
    rw [Nat.arbitrary]
    simp only [pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure]
    right
    exact ⟨n, ih, rfl⟩

/-- Every integer is reachable via `pick` between `(k : Int)` and `-(k+1)`. -/
private theorem Int_cover (z : Int) :
    (∃ k : Nat, k ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)) ∧ (↑k : Int) = z) ∨
    (∃ k : Nat, k ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)) ∧ (-(↑k + 1 : Int)) = z) := by
  cases z with
  | ofNat n => left; exact ⟨n, Nat_arbitrary_support_set n, rfl⟩
  | negSucc n => right; exact ⟨n, Nat_arbitrary_support_set n, by simp [Int.negSucc_eq]⟩

-- ── InFragment predicate ──────────────────────────────────────────────

/-- Predicate characterizing the syntactic fragment produced by `genLExpr`.
    The generator only produces:
    - Both `true` and `false` for bool constants
    - All integers (positive and negative)
    - Abstractions with name `""` and type annotation `some τ₁`
    - Quantifiers with name `""`, type annotation `some τ`, and arbitrary well-typed triggers
    - No `fvar`, no `op` -/
inductive InFragment : ULExpr → Prop where
  | boolConst  : InFragment (.boolConst () b)
  | intConst   : InFragment (.intConst () n)
  | bvar       : InFragment (.bvar () i)
  | abs        : InFragment body → InFragment (.abs () "" (some τ₁) body)
  | app        : InFragment fn → InFragment arg → InFragment (.app () fn arg)
  | ite        : InFragment c → InFragment t → InFragment e →
                 InFragment (.ite () c t e)
  | eq         : InFragment e₁ → InFragment e₂ → InFragment (.eq () e₁ e₂)
  | quant      : InFragment tr → InFragment body →
                 InFragment (.quant () k "" (some τ) tr body)

-- ── termDepth measure ─────────────────────────────────────────────────

/-- The "depth" of a term: how much fuel `genLExpr` needs to produce it.
    This accounts for the depth of types used in the term
    (since `genLMonoTy` needs fuel proportional to type depth). -/
private def termDepth (bctx : BVarCtx) : ULExpr → Nat
  | .boolConst () _       => 0
  | .intConst () _        => 0
  | .bvar () _            => 0
  | .abs () _ (some τ₁) body => termDepth (τ₁ :: bctx) body + 1
  | .app () fn arg        => max (termDepth bctx fn) (termDepth bctx arg) + 1
  | .ite () c t e         => max (termDepth bctx c) (max (termDepth bctx t) (termDepth bctx e)) + 1
  | .eq () e₁ e₂          => max (termDepth bctx e₁) (termDepth bctx e₂) + 1
  | .quant () _ _ (some τ) tr body =>
      max (monoTyDepth τ) (max (termDepth (τ :: bctx) tr) (termDepth (τ :: bctx) body)) + 1
  | _                     => 0

/-- All type annotations occurring in an expression are simple and have depth bounded
    appropriately. The `n` parameter decreases by 1 at each compound expression level,
    matching the generator's fuel consumption. At level `n+1`, intermediate types
    produced by `genLMonoTy n` have depth ≤ `n`, and sub-expressions need `AllTypesSimple n`. -/
inductive AllTypesSimple : Nat → BVarCtx → ULExpr → Prop where
  | boolConst : AllTypesSimple n bctx (.boolConst () b)
  | intConst  : AllTypesSimple n bctx (.intConst () k)
  | bvar      : AllTypesSimple n bctx (.bvar () i)
  | abs       : SimpleType τ₁ → monoTyDepth τ₁ ≤ n →
                AllTypesSimple n (τ₁ :: bctx) body →
                AllTypesSimple (n + 1) bctx (.abs () "" (some τ₁) body)
  | app       : (τ' : LMonoTy) →
                HasTypeA' bctx arg τ' →
                SimpleType τ' → monoTyDepth τ' ≤ n →
                AllTypesSimple n bctx fn → AllTypesSimple n bctx arg →
                AllTypesSimple (n + 1) bctx (.app () fn arg)
  | ite       : AllTypesSimple n bctx c → AllTypesSimple n bctx t →
                AllTypesSimple n bctx e →
                AllTypesSimple (n + 1) bctx (.ite () c t e)
  | eq        : (τ' : LMonoTy) →
                HasTypeA' bctx e₁ τ' → HasTypeA' bctx e₂ τ' →
                SimpleType τ' → monoTyDepth τ' ≤ n →
                AllTypesSimple n bctx e₁ → AllTypesSimple n bctx e₂ →
                AllTypesSimple (n + 1) bctx (.eq () e₁ e₂)
  | quant     : SimpleType τ → monoTyDepth τ ≤ n →
                (τ_tr : LMonoTy) → SimpleType τ_tr → monoTyDepth τ_tr ≤ n →
                HasTypeA' (τ :: bctx) tr τ_tr →
                AllTypesSimple n (τ :: bctx) tr →
                AllTypesSimple n (τ :: bctx) body →
                AllTypesSimple (n + 1) bctx (.quant () k "" (some τ) tr body)

-- ── Completeness for genLExpr ─────────────────────────────────────────

/-- Typing is deterministic for annotated expressions. -/
private theorem typing_deterministic {bctx : BVarCtx} {e : ULExpr} {τ₁ τ₂ : LMonoTy}
    (h₁ : HasTypeA' bctx e τ₁) (h₂ : HasTypeA' bctx e τ₂) : τ₁ = τ₂ := by
  have := LExpr.HasTypeA_to_typeCheck h₁
  have := LExpr.HasTypeA_to_typeCheck h₂
  simp_all

/-- If `.boolConst () b` has type `τ`, then `τ = .bool`. -/
private theorem boolConst_hasType_bool {bctx : BVarCtx} {τ : LMonoTy} {b : Bool}
    (h : HasTypeA' bctx (.boolConst () b) τ) : τ = .bool := by
  have htc := LExpr.HasTypeA_to_typeCheck h
  simp [LExpr.typeCheck] at htc
  exact htc.symm

/-- If `.intConst () n` has type `τ`, then `τ = .int`. -/
private theorem intConst_hasType_int {bctx : BVarCtx} {τ : LMonoTy} {n : Int}
    (h : HasTypeA' bctx (.intConst () n) τ) : τ = .int := by
  have htc := LExpr.HasTypeA_to_typeCheck h
  simp [LExpr.typeCheck] at htc
  exact htc.symm

/-- If `.eq () e₁ e₂` has type `τ`, then `τ = .bool`. -/
private theorem eq_hasType_bool {bctx : BVarCtx} {τ : LMonoTy} {e₁ e₂ : ULExpr}
    (h : HasTypeA' bctx (.eq () e₁ e₂) τ) : τ = .bool := by
  cases h with
  | eq _ _ => rfl

/-- If `.quant () k name (some qty) tr body` has type `τ`, then `τ = .bool`. -/
private theorem quant_hasType_bool {bctx : BVarCtx} {τ : LMonoTy}
    {k name qty tr body}
    (h : HasTypeA' bctx (.quant () k name (some qty) tr body) τ) : τ = .bool := by
  cases h with
  | quant _ _ => rfl

/-- If `.abs () name (some aty) body` has type `τ`, then `τ = .arrow aty rty` for some `rty`. -/
private theorem abs_hasType_arrow {bctx : BVarCtx} {τ : LMonoTy}
    {name aty body}
    (h : HasTypeA' bctx (.abs () name (some aty) body) τ) : ∃ rty, τ = .arrow aty rty := by
  cases h with
  | abs _ => exact ⟨_, rfl⟩


/-- Completeness of `genLExpr`: every well-typed expression in the syntactic fragment
    (with all intermediate types simple and bounded) is in the support of `genLExpr`
    for a sufficiently large `size` parameter. -/
theorem genLExpr_complete (bctx : BVarCtx) (size : Nat) (τ : LMonoTy)
    (hτ : SimpleType τ)
    (e : ULExpr)
    (hwt : HasTypeA' bctx e τ)
    (hfrag : InFragment e)
    (hats : AllTypesSimple size bctx e)
    (hsize : termDepth bctx e ≤ size) :
    e ∈ SetGen.support (genLExpr (G := SetGen.Set) bctx size τ) := by
  match size, τ, hτ with
  -- ══════════════════════════════════════════════════════════════════════
  -- Case: size = 0, τ = .bool
  -- ══════════════════════════════════════════════════════════════════════
  | 0, _, SimpleType.bool =>
    rw [norm_bool]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hfrag with
    | boolConst =>
      rename_i b
      cases b with
      | true =>
        by_cases hv : (bvarsOfType bctx .bool).length > 0
        · left; exact ⟨hv, Or.inl (Or.inl rfl)⟩
        · right; exact ⟨hv, Or.inl rfl⟩
      | false =>
        by_cases hv : (bvarsOfType bctx .bool).length > 0
        · left; exact ⟨hv, Or.inl (Or.inr rfl)⟩
        · right; exact ⟨hv, Or.inr rfl⟩
    | intConst => exact absurd (intConst_hasType_int hwt) (by simp [LMonoTy.int, LMonoTy.bool])
    | bvar =>
      rename_i i
      have hget : bctx[i]? = some .bool := by cases hwt; assumption
      have hmem : i ∈ bvarsOfType bctx .bool := (bvarsOfType_mem_iff bctx .bool i).mpr hget
      have hv : (bvarsOfType bctx .bool).length > 0 := List.length_pos_of_mem hmem
      left; exact ⟨hv, Or.inr (pickBVar_complete bctx .bool i hget hv)⟩
    | abs => simp [termDepth] at hsize
    | app => simp [termDepth] at hsize
    | ite => simp [termDepth] at hsize
    | eq => simp [termDepth] at hsize
    | quant => simp [termDepth] at hsize
  -- ══════════════════════════════════════════════════════════════════════
  -- Case: size = 0, τ = .int
  -- ══════════════════════════════════════════════════════════════════════
  | 0, _, SimpleType.int =>
    rw [norm_int]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hfrag with
    | intConst =>
      rename_i z
      have hgoal : (∃ a ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)),
                      (.intConst () z : ULExpr) = .intConst () (↑a : Int)) ∨
                   (∃ a ∈ SetGen.support (Nat.arbitrary (G := SetGen.Set)),
                      (.intConst () z : ULExpr) = .intConst () (-(↑a + 1 : Int))) := by
        rcases Int_cover z with ⟨k, hk, hkz⟩ | ⟨k, hk, hkz⟩
        · left; exact ⟨k, hk, by simp [← hkz]⟩
        · right; exact ⟨k, hk, by simp [← hkz]⟩
      by_cases hv : (bvarsOfType bctx .int).length > 0
      · left; exact ⟨hv, Or.inl hgoal⟩
      · right; exact ⟨hv, hgoal⟩
    | boolConst => exact absurd (boolConst_hasType_bool hwt) (by simp [LMonoTy.int, LMonoTy.bool])
    | bvar =>
      rename_i i
      have hget : bctx[i]? = some .int := by cases hwt; assumption
      have hmem : i ∈ bvarsOfType bctx .int := (bvarsOfType_mem_iff bctx .int i).mpr hget
      have hv : (bvarsOfType bctx .int).length > 0 := List.length_pos_of_mem hmem
      left; exact ⟨hv, Or.inr (pickBVar_complete bctx .int i hget hv)⟩
    | abs => simp [termDepth] at hsize
    | app => simp [termDepth] at hsize
    | ite => simp [termDepth] at hsize
    | eq => simp [termDepth] at hsize
    | quant => simp [termDepth] at hsize
  -- ══════════════════════════════════════════════════════════════════════
  -- Case: size = 0, τ = .arrow τ₁ τ₂
  -- ══════════════════════════════════════════════════════════════════════
  | 0, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hfrag with
    | boolConst =>
      exact absurd (boolConst_hasType_bool hwt) (by simp [LMonoTy.bool, LMonoTy.arrow])
    | intConst =>
      exact absurd (intConst_hasType_int hwt) (by simp [LMonoTy.int, LMonoTy.arrow])
    | bvar =>
      rename_i i
      have hget : bctx[i]? = some (.arrow τ₁ τ₂) := by cases hwt; assumption
      have hmem : i ∈ bvarsOfType bctx (.arrow τ₁ τ₂) :=
        (bvarsOfType_mem_iff bctx (.arrow τ₁ τ₂) i).mpr hget
      have hv : (bvarsOfType bctx (.arrow τ₁ τ₂)).length > 0 := List.length_pos_of_mem hmem
      left; exact ⟨hv, Or.inl (pickBVar_complete bctx (.arrow τ₁ τ₂) i hget hv)⟩
    | abs => simp [termDepth] at hsize
    | app => simp [termDepth] at hsize
    | ite => simp [termDepth] at hsize
    | eq => exact absurd (eq_hasType_bool hwt) (by simp [LMonoTy.bool, LMonoTy.arrow])
    | quant => exact absurd (quant_hasType_bool hwt) (by simp [LMonoTy.bool, LMonoTy.arrow])
  -- ══════════════════════════════════════════════════════════════════════
  -- Case: size = n+1, τ = .bool
  -- ══════════════════════════════════════════════════════════════════════
  | n + 1, _, SimpleType.bool =>
    rw [norm_bool]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hfrag with
    | boolConst =>
      rename_i b
      cases b with
      | true => left; left; rfl
      | false => left; right; rfl
    | intConst => exact absurd (intConst_hasType_int hwt) (by simp [LMonoTy.int, LMonoTy.bool])
    | bvar =>
      rename_i i
      have hget : bctx[i]? = some .bool := by cases hwt; assumption
      have hmem : i ∈ bvarsOfType bctx .bool := (bvarsOfType_mem_iff bctx .bool i).mpr hget
      have hv : (bvarsOfType bctx .bool).length > 0 := List.length_pos_of_mem hmem
      right; right; right; right; right; right
      left; exact ⟨hv, pickBVar_complete bctx .bool i hget hv⟩
    | ite hfrag_c hfrag_t hfrag_e =>
      -- Destructure hwt and hats to get concrete sub-expression info
      match hwt, hats with
      | .ite hwt_c hwt_t hwt_e, .ite hats_c hats_t hats_e =>
        right; left
        refine ⟨_, ?_, _, ?_, _, ?_, rfl⟩
        · exact genLExpr_complete bctx n .bool SimpleType.bool _ hwt_c hfrag_c hats_c (by simp [termDepth] at hsize; omega)
        · exact genLExpr_complete bctx n .bool SimpleType.bool _ hwt_t hfrag_t hats_t (by simp [termDepth] at hsize; omega)
        · exact genLExpr_complete bctx n .bool SimpleType.bool _ hwt_e hfrag_e hats_e (by simp [termDepth] at hsize; omega)
    | eq hfrag₁ hfrag₂ =>
      -- Destructure hats to get the common type
      match hats with
      | .eq τ' hwt₁ hwt₂ hτ'_simple hτ'_depth hats₁ hats₂ =>
        right; right; left
        refine ⟨τ', (genLMonoTy_support n τ').mpr ⟨hτ'_simple, hτ'_depth⟩, _, ?_, _, ?_, rfl⟩
        · exact genLExpr_complete bctx n τ' hτ'_simple _ hwt₁ hfrag₁ hats₁ (by simp [termDepth] at hsize; omega)
        · exact genLExpr_complete bctx n τ' hτ'_simple _ hwt₂ hfrag₂ hats₂ (by simp [termDepth] at hsize; omega)
    | app hfrag_fn hfrag_arg =>
      -- Destructure hats and hwt to get the argument type
      match hats, hwt with
      | .app τ' hwt_arg' hτ'_simple hτ'_depth hats_fn hats_arg, .app hwt_fn hwt_arg =>
        have heq := typing_deterministic hwt_arg' hwt_arg
        subst heq
        right; right; right; left
        refine ⟨τ', (genLMonoTy_support n τ').mpr ⟨hτ'_simple, hτ'_depth⟩, _, ?_, _, ?_, rfl⟩
        · exact genLExpr_complete bctx n τ' hτ'_simple _ hwt_arg hfrag_arg hats_arg (by simp [termDepth] at hsize; omega)
        · exact genLExpr_complete bctx n (.arrow τ' .bool) (SimpleType.arrow hτ'_simple SimpleType.bool) _ hwt_fn hfrag_fn hats_fn (by simp [termDepth] at hsize; omega)
    | quant hfrag_tr hfrag_body =>
      -- Destructure hats and hwt, then case-split on QuantifierKind via hfrag
      rename_i tr_e body_e qk qty_ty
      cases hats with
      | quant hτ_simple hτ_depth τ_tr hτ_tr_simple hτ_tr_depth hwt_tr' hats_tr hats_body =>
        cases hwt with
        | quant _ hwt_body =>
          cases qk with
          | all =>
            right; right; right; right; left
            refine ⟨_, (genLMonoTy_support n _).mpr ⟨hτ_simple, hτ_depth⟩,
                    τ_tr, (genLMonoTy_support n τ_tr).mpr ⟨hτ_tr_simple, hτ_tr_depth⟩,
                    _, ?_, _, ?_, rfl⟩
            · exact genLExpr_complete _ n τ_tr hτ_tr_simple _ hwt_tr' hfrag_tr hats_tr (by simp [termDepth] at hsize; omega)
            · exact genLExpr_complete _ n .bool SimpleType.bool _ hwt_body hfrag_body hats_body (by simp [termDepth] at hsize; omega)
          | exist =>
            right; right; right; right; right; left
            refine ⟨_, (genLMonoTy_support n _).mpr ⟨hτ_simple, hτ_depth⟩,
                    τ_tr, (genLMonoTy_support n τ_tr).mpr ⟨hτ_tr_simple, hτ_tr_depth⟩,
                    _, ?_, _, ?_, rfl⟩
            · exact genLExpr_complete _ n τ_tr hτ_tr_simple _ hwt_tr' hfrag_tr hats_tr (by simp [termDepth] at hsize; omega)
            · exact genLExpr_complete _ n .bool SimpleType.bool _ hwt_body hfrag_body hats_body (by simp [termDepth] at hsize; omega)
    | abs =>
      exact absurd (abs_hasType_arrow hwt) (by intro ⟨_, h⟩; simp [LMonoTy.arrow, LMonoTy.bool] at h)
  -- ══════════════════════════════════════════════════════════════════════
  -- Case: size = n+1, τ = .int
  -- ══════════════════════════════════════════════════════════════════════
  | n + 1, _, SimpleType.int =>
    rw [norm_int]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hfrag with
    | intConst =>
      rename_i z
      left
      rcases Int_cover z with ⟨k, hk, hkz⟩ | ⟨k, hk, hkz⟩
      · left; exact ⟨k, hk, by simp [← hkz]⟩
      · right; exact ⟨k, hk, by simp [← hkz]⟩
    | boolConst => exact absurd (boolConst_hasType_bool hwt) (by simp [LMonoTy.int, LMonoTy.bool])
    | bvar =>
      rename_i i
      have hget : bctx[i]? = some .int := by cases hwt; assumption
      have hmem : i ∈ bvarsOfType bctx .int := (bvarsOfType_mem_iff bctx .int i).mpr hget
      have hv : (bvarsOfType bctx .int).length > 0 := List.length_pos_of_mem hmem
      right; right; right
      left; exact ⟨hv, pickBVar_complete bctx .int i hget hv⟩
    | app hfrag_fn hfrag_arg =>
      match hats, hwt with
      | .app τ' hwt_arg' hτ'_simple hτ'_depth hats_fn hats_arg, .app hwt_fn hwt_arg =>
        have heq := typing_deterministic hwt_arg' hwt_arg
        subst heq
        right; left
        refine ⟨τ', (genLMonoTy_support n τ').mpr ⟨hτ'_simple, hτ'_depth⟩, _, ?_, _, ?_, rfl⟩
        · exact genLExpr_complete bctx n τ' hτ'_simple _ hwt_arg hfrag_arg hats_arg (by simp [termDepth] at hsize; omega)
        · exact genLExpr_complete bctx n (.arrow τ' .int) (SimpleType.arrow hτ'_simple SimpleType.int) _ hwt_fn hfrag_fn hats_fn (by simp [termDepth] at hsize; omega)
    | ite hfrag_c hfrag_t hfrag_e =>
      match hwt, hats with
      | .ite hwt_c hwt_t hwt_e, .ite hats_c hats_t hats_e =>
        right; right; left
        refine ⟨_, ?_, _, ?_, _, ?_, rfl⟩
        · exact genLExpr_complete bctx n .bool SimpleType.bool _ hwt_c hfrag_c hats_c (by simp [termDepth] at hsize; omega)
        · exact genLExpr_complete bctx n .int SimpleType.int _ hwt_t hfrag_t hats_t (by simp [termDepth] at hsize; omega)
        · exact genLExpr_complete bctx n .int SimpleType.int _ hwt_e hfrag_e hats_e (by simp [termDepth] at hsize; omega)
    | eq => exact absurd (eq_hasType_bool hwt) (by simp [LMonoTy.int, LMonoTy.bool])
    | quant => exact absurd (quant_hasType_bool hwt) (by simp [LMonoTy.int, LMonoTy.bool])
    | abs =>
      exact absurd (abs_hasType_arrow hwt) (by intro ⟨_, h⟩; simp [LMonoTy.arrow, LMonoTy.int] at h)
  -- ══════════════════════════════════════════════════════════════════════
  -- Case: size = n+1, τ = .arrow τ₁ τ₂
  -- ══════════════════════════════════════════════════════════════════════
  | n + 1, _, SimpleType.arrow hs₁ hs₂ =>
    rename_i τ₁ τ₂
    rw [norm_arrow]
    simp only [genLExpr, pick_mem_iff, SetGen.Set.mem_bind, SetGen.Set.mem_pure,
      mem_support_iff, SetGen.mem_dite]
    cases hfrag with
    | boolConst =>
      exact absurd (boolConst_hasType_bool hwt) (by simp [LMonoTy.bool, LMonoTy.arrow])
    | intConst =>
      exact absurd (intConst_hasType_int hwt) (by simp [LMonoTy.int, LMonoTy.arrow])
    | bvar =>
      rename_i i
      have hget : bctx[i]? = some (.arrow τ₁ τ₂) := by cases hwt; assumption
      have hmem : i ∈ bvarsOfType bctx (.arrow τ₁ τ₂) :=
        (bvarsOfType_mem_iff bctx (.arrow τ₁ τ₂) i).mpr hget
      have hv : (bvarsOfType bctx (.arrow τ₁ τ₂)).length > 0 := List.length_pos_of_mem hmem
      right; right; right
      left; exact ⟨hv, pickBVar_complete bctx (.arrow τ₁ τ₂) i hget hv⟩
    | abs hfrag_bd =>
      cases hwt with
      | abs hwt_bd =>
        cases hats with
        | abs _ _ hats_bd =>
          left
          refine ⟨_, ?_, rfl⟩
          exact genLExpr_complete (τ₁ :: bctx) n τ₂ hs₂ _ hwt_bd hfrag_bd hats_bd (by simp [termDepth] at hsize; omega)
    | app hfrag_fn hfrag_arg =>
      cases hats with
      | app τ' hwt_arg' hτ'_simple hτ'_depth hats_fn hats_arg =>
        cases hwt with
        | app hwt_fn hwt_arg =>
          have heq := typing_deterministic hwt_arg' hwt_arg
          subst heq
          right; left
          refine ⟨τ', (genLMonoTy_support n τ').mpr ⟨hτ'_simple, hτ'_depth⟩, _, ?_, _, ?_, rfl⟩
          · exact genLExpr_complete bctx n τ' hτ'_simple _ hwt_arg hfrag_arg hats_arg (by simp [termDepth] at hsize; omega)
          · exact genLExpr_complete bctx n (.arrow τ' (.arrow τ₁ τ₂)) (SimpleType.arrow hτ'_simple (SimpleType.arrow hs₁ hs₂)) _ hwt_fn hfrag_fn hats_fn (by simp [termDepth] at hsize; omega)
    | ite hfrag_c hfrag_t hfrag_e =>
      cases hwt with
      | ite hwt_c hwt_t hwt_e =>
        cases hats with
        | ite hats_c hats_t hats_e =>
          right; right; left
          refine ⟨_, ?_, _, ?_, _, ?_, rfl⟩
          · exact genLExpr_complete bctx n .bool SimpleType.bool _ hwt_c hfrag_c hats_c (by simp [termDepth] at hsize; omega)
          · exact genLExpr_complete bctx n (.arrow τ₁ τ₂) (SimpleType.arrow hs₁ hs₂) _ hwt_t hfrag_t hats_t (by simp [termDepth] at hsize; omega)
          · exact genLExpr_complete bctx n (.arrow τ₁ τ₂) (SimpleType.arrow hs₁ hs₂) _ hwt_e hfrag_e hats_e (by simp [termDepth] at hsize; omega)
    | eq => exact absurd (eq_hasType_bool hwt) (by simp [LMonoTy.bool, LMonoTy.arrow])
    | quant => exact absurd (quant_hasType_bool hwt) (by simp [LMonoTy.bool, LMonoTy.arrow])
  termination_by (size, sizeOf τ)
  decreasing_by all_goals simp_wf; omega

-- ── IsSoundAndComplete for genLMonoTy ─────────────────────────────────

/-- `genLMonoTy n` is sound and complete with respect to
    `fun τ => SimpleType τ ∧ monoTyDepth τ ≤ n`. -/
instance {n : Nat} :
    SetGen.IsSoundAndComplete
      (genLMonoTy (G := SetGen.Set) n)
      (fun τ => SimpleType τ ∧ monoTyDepth τ ≤ n) where
  support_iff τ := genLMonoTy_support n τ

-- ── Quick test ────────────────────────────────────────────────────────

-- We need this `ToFormat` instance in order to pretty-print the generated `LExpr`s
-- before (since our metadata type is `Unit`)
open Std in
instance : ToFormat Unit where
  format _ := .nil

-- Print 5 randomly generated expressions
-- Some example generated exprs:
-- (if (if #true then #true else #true) then #true else #true)
-- ((λ (bvar:bool) #true) ((λ (bvar:bool) %0) #true))
#guard_msgs(drop warning) in
#eval (for _ in [:5] do
  IO.println <| Std.format (← ULExpr.gen 2) |>.pretty : IO Unit)
