name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: hgoldstein95/basalt
          path: ../basalt
      - uses: leanprover/lean-action@v1
